### ISSUE TITLE
[ グループブロック ] 線の色がカスタムカラーが選べない（デフォルトの色はOK） -> カラーパネルに非推奨の案内表記追加

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1033]
勉強会にて報告がありました。
変更できるのか調査

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/765

@shimotmk @mthaichi @drill-lancer  @sysbird @doshimaf 
Cc: @goutetsuguma @ChiakiKouno @kaorock72

グループブロックで、VK Blocks 独自実装の線の色を指定する機能について、
現状例えばLightningのキーカラーなど、独自に追加したカラーパレットは反映されない状態ですが、
theme.json 有効モードだと、WordPressの標準機能で色はつけれる状態です。

簡単に対応できますよーという感じなら対応いただいた方が良いのですが、
個人的には、これコアでサポートされちゃってる機能なので（theme.json無効だと使えないけどLightningも新規はデフォルト有効）、もう独自実装のグループブロックの線の色指定機能に関しては非推奨扱いにして、
この対応実装はスルーにしようかなと思いますが如何でしょう？

**Comment by kurudrive** [comment]
あー、その場合、VK Blocks 側の線の色指定のパネルの中に、

ここでの色指定は非推奨です。
theme.json が有効なテーマの場合「枠線」パネルからも色指定が可能です。

という注釈は追加する必要があるかなと思います。

**Comment by kurudrive** [comment]
```
ここでの色指定は非推奨になりました。
theme.json が有効なテーマの場合は別途「枠線（英語だと Borderの部分）」パネルから色指定が可能です。
```

**Comment by doshimaf** [comment]
@kurudrive 
注釈の追加のみの場合、readme.txt に変更内容の記載は必要でしょうか？

**Comment by doshimaf** [comment]
リリースされたのでClose
