### ISSUE TITLE
古いブロックは使ってほしくないのでオンオフ機能など検討

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1047]
* 新規インストールしたユーザーには古い非推奨のブロックは選択できないようにしたい
* WordPressデフォルトで存在する利用するブロックの管理機能があるので、新規インストールの場合にその保存値を自動的に書き換えれば良いのではないか

対象

- [x] PR Block
- [x] PR Content
- [x] スタッフ
- [x] アイコンカード
- [x] カード

**Comment by shimotmk** [comment]
やっぱりブロックマネージャーは独自にDBに保存して欲しいと思うので優先度を戻そうと思います

理由
・VK Blocksの非推奨のブロックは新規インストール時にはオフにしたい
・コアはカスタムストアでやっているのでブラウザのストアを削除すると引き継がれない(DBには保存しないのでシークレットウィンドウで見ると表示が異なる)
・今後も機能は同じでもブロックを作り直したいみたいなケースあると思う

いや実装はしない方がが良いなどあったら言っていただければと思います

**Comment by kurudrive** [comment]
@kaorock72 こちらも 1.48.0 でリリース済みなので、お知らせよろしくお願いいたします🙏

**Comment by kaorock72** [comment]
@kurudrive
こちらもお知らせ公開しました！おかしな箇所や不足などありましたら修正します。後ほどシェアいたします。
https://www.vektor-inc.co.jp/product-update/vk-blocks-1-48-0-add-block-manager-function/

**Comment by kurudrive** [comment]
@kaorock72 確認しました！ありがとうございます！
