### ISSUE TITLE
追加スタイルが結構邪魔になってきたので選択式にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1056]
* グループブロックなど特にFSEでは線の色・太さ・線の種類など概ね自由に設定可能
* グループブロック選択する度にサイドバーでスタイルがどかーっと最初パネル埋め尽くすけど実際ほとんど選択する事がない。

と、いう事で、現状で既に追加しているスタイルがあるが、SWELLみたいに追加するスタイルを選択できるようにしたい。

**Comment by shimotmk** [comment]
昨日の決定事項メモ
vk_blocks_optionsをGETするREST APIを先に作る
https://github.com/vektor-inc/vk-blocks-pro/blob/master/inc/vk-blocks/App/RestAPI/BlockMeta/class-vk-blocks-entrypoint.php
ブロックエディタなどでオプション値を扱うため

以下のブランチでもそのAPIを使ってオプション値を取得する予定
#1367 #1395

**Comment by kurudrive** [comment]
- [ ] 一旦設定画面からの停止ができるようにする

現状適当されてるブロック :  グループ / 見出しブロック / 画像 / テーブル

案A : ブロック単位でカスタムスタイルを停止できるようにする
案B : カスタムスタイル単位で停止できるようにする

**Comment by shimotmk** [comment]
@mthaichi これやりますね

**Comment by mthaichi** [comment]
@shimotmk ありがとうございます。よろしくおねがいします！

**Comment by shimotmk** [comment]
## コアブロックに追加しているスタイル一覧 
### 見出し (core/heading) 9個
- 装飾無し
- 背景塗り 灰色
- 二重線 上下線 黒
- 二重線 下線 黒
- 直線 上下 黒
- 直線 下線 黒
- 点線 下線 黒
- 左右線
- 括弧 黒

### リスト (core/list) 3個
- 矢印
- 三角
- チェック
- チェック（四角）
- チェック-丸
- 指
- 鉛筆
- 笑顔
- 不満顔
- 数字-丸
- 数字-四角

### テーブル (core/table) 3個
- 直線 上下
- 枠線
- 枠線 / ストライプ

### - 画像(core/image) 10個
- 角丸2
- 枠線
- フォトフレーム
- フォトフレーム傾き右
- フォトフレーム傾き左
- シャドウ
- 流体シェイプ1
- 流体シェイプ2
- 流体シェイプ3
- 流体シェイプ4

### グループ (core/group) 12個
- 直線
- 直線 角丸
- 点線
- Dashed
- 二重線
- スティッチ
- 直線 上下
- シャドウ
- Info
- Success
- Warning
- Danger

**Comment by shimotmk** [comment]
リリースされたのでcloseします

**Comment by kurudrive** [comment]
@kaorock72 これお知らせ記事よろしくお願いいたします。

**Comment by kaorock72** [comment]
@kurudrive 
お知らせと各シェア完了しました！
https://www.vektor-inc.co.jp/product-update/vk-blocks-1-56-0-block-style-manager/
https://twitter.com/vektor_inc/status/1661662102313127937
