### ISSUE TITLE
よくつかう書式設定機能追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1057]
毎回 「蛍光マーカー」「太字」「色は赤」 をするのが面倒。

設定画面で フォーマット１（vk-text-style--1 などのクラス名） に対してどの項目を割り当てるのか指定

* 蛍光マーカーの有無 / 色
* 文字の色
* 文字の背景色
* 文字のサイズ
* 標準 / 太字 / 斜体

を指定してある cssを出力する。

フォーマットは5種類くらい登録可能にする。

設定画面は react でプレビューできるようにする。

**Comment by shimotmk** [comment]
@goutetsuguma 
お疲れ様です。
書式設定のデザインをお願いしたいです🙏

ブランチ
#1367

デザインまわりやってほしいこと
- ブロックエディター書式設定アイコン
アイコンは
`src/extensions/common/text-style/icon.svg`
に入れていただければ反映されると思います
- 管理画面のデザイン調整
CSSは`options-css`
JSXは`src/admin/text-style/`
で調整できます
- そのほかUI的に欲しい機能などあれば

CSSやクラス名は自分が適当につけたので付け直していただいても構わないですし、FigmaとかでUI作って再現できそうか確認いただいても構わないです。
どんな感じがやりやすいですかね？


ちなみに書式設定はテスト関連などで調整が必要なので急ぎではないです。

**Comment by goutetsuguma** [comment]
- [ ] ブロックエディター書式設定アイコン（プッシュ済み）
- [ ] 管理画面のデザイン調整（プッシュ済み）

---

> そのほかUI的に欲しい機能などあれば

使いやすいです！書式バラバラだったのでこれで統一できそうです！

- 強いて言うなら「ツールバーのタイトル」は入れ忘れそうかも？と思ったので（ここが入力無いとツールバーに表示されないようなので）必須 とか書いておくとか？

- たくさん登録すると下にある「変更を保存」ボタンを押し忘れそうなので、説明のテキストの部分に「設定を変更したら「変更を保存」ボタンをクリックしてください。」みたいな説明文も追加するとか？（吹き出しブロック設定のところのように）

**Comment by shimotmk** [comment]
@goutetsuguma 
調整ありがとうございます！
ツールバーのタイトル、削除ボタンについては悩んでいるので少し考えます！
他の作業が必要になったので少し時間を置いてまた相談するかもしれないです


保存ボタンについては保存ボタンを画面下に追従するのはどうでしょうか？
吹き出しのように注意書きを書くのは簡単ですが保存ボタンが画面に無い状態があることが問題かと思うので

ただこれはこのissueと少し別の話になると思うので別issueにしたいと思います。

**Comment by shimotmk** [comment]
メモ
ブランチ #1367

コードの変更箇所が被る可能性が高いので以下の作業が終わってからデザイン再調整・依頼(急ぎではない)
#1355
#1374
#1392

**Comment by shimotmk** [comment]
@ChiakiKouno @doshimaf @drill-lancer @goutetsuguma @kaorock72 @kurudrive @mthaichi @sysbird 他

お疲れ様です。カスタム書式設定機能を作ってみました
設定 > VK Blocks管理画面の部分です。
![format](https://user-images.githubusercontent.com/42362903/202109160-e326cd5d-5453-46ba-b1f8-bdb3036e2e08.png)

本番リリース前に使ってみた感想や欲しい機能などあったらご意見いただきたいです🙏
お手隙の際で構わないのでよろしくお願いします🙇‍♂️

ブランチ #1488
現時点でのzipプラグイン
[vk-blocks-pro.zip](https://github.com/vektor-inc/vk-blocks-pro/files/10018922/vk-blocks-pro.zip)

**Comment by doshimaf** [comment]
@shimotmk 
ありがとうございます！
仕様、UI含め使いやすかったです。

個人的に、クラス名は設定しなければ自動的に連番で補完されるような形だと便利かなと思いましたがいかがでしょうか？
また、仕様的に複雑になりそうですが、ここでカスタムCSSとか使えると便利そうとも思いました。

**Comment by shimotmk** [comment]
カスタムCSSと配布したりすることも考えてselector指定も追加しました
![format](https://user-images.githubusercontent.com/42362903/203261390-2c7b290f-02f0-4dea-92dc-494213d536eb.png)

**Comment by kurudrive** [comment]
@shimotmk 試しましたー！

えーっくせれんとー！！！！いいよ！！いいよ！！

クラス名について僕も自動で変更をさせない仕様の方がユーザーにとっては概ね楽なのかなと思いつつ、
任意に設定したい人も出てくる＆設定するのは一度だけ という特性を考えると迷いますが今の仕様の方がいいと思いました！

**Comment by doshimaf** [comment]
@shimotmk 
確かにクラス名を付けたいユーザーが一定数いるとすると、今の仕様が最適そうですね。

カスタムCSS機能の追加もありがとうございます！
また試用してみます。

**Comment by shimotmk** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1316478627
これ仕様的なフィードバックは今日(11/25)までにして特に無ければ来週プルリクにしようと思います

**Comment by mthaichi** [comment]
@shimotmk  私も @doshimaf さんと同じことを感じました。僕はCSS指定が面倒なので、勝手に決めて欲しいと思ってしまいます。

>・ユーザーがカスタマイズされたクラス名が保存された後の連番の番号はどうするか
>・連番の番号をユーザーが適当に変えた場合その後の番号はどうするか
>・番号は003など単純な数字として扱えない場合どうするなど

- ユーザーがクラス名を指定しない場合は、たとえば vk-format--1  というフォーマットに決める。1の部分が連番的に変わる。
- 書式の登録時にクラス名が指定されていない場合は、書式リストの一覧のクラス名をforeachして、 ^vk-format--(\d+)$  のような正規表現をかけて、マッチした中で、一番大きい数値+1 をクラス名とする。vk-format--1とvk-format--6 が存在したら、 vk-format--7  で良いと思います。
003 は 3 とみなしても、無視してもよいかなと。
- クラス名を指定した場合はいままで通りの処理。

という感じではどうでしょう。

細かい実装を見てないので、無理なことを言ってたらすみません。
難しかったら、今のままでも十分便利だと思います。
ありがとうございます。

**Comment by shimotmk** [comment]
うーん。
CSSクラス指定が面倒な需要とCSSクラスをカスタマイズしたい需要どちらを取るかだと思います。

・CSSクラス指定が面倒な人は勝手に入ってほしい
・CSSクラスをカスタマイズしたい人は逆に入っていると削除しなければならず邪魔
だと思います

このカスタム書式設定機能を使う人はどちらが多いと思いますかね？

**Comment by mthaichi** [comment]
> このカスタム書式設定機能を使う人はどちらが多いと思いますかね？

@shimotmk CSSクラス指定をしたくない。というか、戸惑う人が結構多いと私は思います。
「CSSクラス」がよく分かっていないユーザーもいると思いますので。

クラス指定をしたい人のために、できることなら両方対応してくれたら嬉しいなというところです。
テキストボックスにはじめから自動でクラス名が入っているのではなく、必須項目を外して、空白のまま送信するとクラス名が決まるという感じではどうでしょう。指定したい人が指定をする。指定したくない人は空白。

**Comment by shimotmk** [comment]
@mthaichi 
まずプログラム的な部分でいえば、クラス名の最大値を取得してその最大値をクラス名として返すことは可能なことがわかりました。ただ、やはり数字が歯抜けになるので(例えば1,3,40,41など)気持ち悪さが残ります。
そこは、uuidなど使って適当なクラスを返せばなんとかなりそうなのでプログラム的なことは考慮しなくて大丈夫です。
ここでのコメントは誤っていました。すみません
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1322916718
```JS
const formatClassNumbers = vkBlocksOption.custom_format_lists.filter(list => list.match(/^vk-format-\d+$/)).map(list => Number(list.replace(/^vk-format-/, '')));
const maxNum  = Math.max(...formatClassNumbers);
const uniqueClassName = `vk-format-${maxNum + 1}`;
```

***


プログラム的なことは考慮しなくてもやはり自動でクラス名を入力したり、クラス名が空白の場合は自動で決まるなどの実装はしたくないです。
なぜなら、ユーザーが意図したクラス名は勝手に設定された感じ不快感を覚える可能性があるからです。

書式設定のクラス名は変えることが出来ないものです。DBに保存されるのでクラス名を変更すると過去の記事の装飾が外れます。クラス名は思考停止で作って欲しくないと言う意味を込めてモーダルにしてクラス名をきちんと考えるように促していました。

そのため私としてはクラス名のカスタマイズを一切許可しない、もしくはバリテーションを付けた今の実装のどちらかだと思います。

***

>   CSSクラス指定をしたくない。というか、戸惑う人が結構多いと私は思います。
「CSSクラス」がよく分かっていないユーザーもいると思いますので。

そういったユーザーがいることを想定しておりませんでした。
ブロックエディターでもCSSクラスは使用されているので知っているものだと思ったのですが、どういった理由でCSSクラスがよく分かっていない、戸惑うと思われましたか？

**Comment by mthaichi** [comment]
いろいろと考えて頂き、ありがとうございます！

先に重要だと思った部分から

>ブロックエディターでもCSSクラスは使用されているので知っているものだと思ったのですが、
>どういった理由でCSSクラスがよく分かっていない、戸惑うと思われましたか？

私の隣に座っている人は、Lightning＋VK Blocksユーザーでクライアントワークにも使っていますが、CSSをカスタムしたことはないそうです。（CSSの知識はありますよ）
なぜなら標準機能で、ある程度そこそこのHPができてしまうからです。
私自身もクライアントワークを多くこなしていますが、極力標準機能の中で対応し、CSSをカスタムするのは最終手段。別途見積が発生するぞ、ぐらいの位置づけです。（低価格の制作なもので）  
あと、隣の部屋の人は、自社サイトを自力でLightning＋VK Blocks作っていますが、おそらくCSSカスタムはしていませんし、CSSそのものをあまりよく理解していないと思われます。

WordPressの良いところは、CSSの知識がなくとも、そこそこリッチなコンテンツ制作できる部分にあると思います。
ですから、ユーザーにCSSの知識がない人がいることは十分考慮されるべきことかと思います。
その上で、カスタムしたい人はCSSを自由にカスタムできるというのが理想だと思いますが、いかがでしょうか。

ブロックエディタの「CSSクラス」は、「意味がわからないし、使う必要もないので、使わない」という人も多いかと思います。私もユーザーとしてはほとんど使いません。そういう人にとって、「CSSクラス名」を決めるのはちょっと戸惑いますね。命名ルールもよくわかっていないですし。

>なぜなら、ユーザーが意図したクラス名は勝手に設定された感じ不快感を覚える可能性があるからです。

すみません。ちょっとここは意味が分かりませんでした。

>書式設定のクラス名は変えることが出来ないものです。DBに保存されるのでクラス名を変更すると過去の記事の装飾が外れます。クラス名は思考停止で作って欲しくないと言う意味を込めてモーダルにしてクラス名をきちんと考えるように促していました。

この機能については、クラス名とスタイルが紐付き、クラス名が消滅・変更されると、装飾がなくなるというリスクがあるわけですね。だからCSSクラスがよく分かっていない人はこの機能は使わないで欲しい的な位置づけなら、わかります。
でも、この機能はすごく便利なので、そうしたリスクも分かってもらえるなら、CSSクラスがよく分かっていない人にもつかってもらったらいいのかなとおもった次第です。

これを実装して頂くにしても、細かい実装方法は @shimotmk さんのやりやすい形で全然良いと思います。

**Comment by mthaichi** [comment]
@shimotmk いろいろと考えて頂き、ありがとうございます！

先に重要だと思った部分から

>ブロックエディターでもCSSクラスは使用されているので知っているものだと思ったのですが、
>どういった理由でCSSクラスがよく分かっていない、戸惑うと思われましたか？

私の隣に座っている人は、Lightning＋VK Blocksユーザーでクライアントワークにも使っていますが、CSSをカスタムしたことはないそうです。（CSSの知識はありますよ）
なぜなら標準機能で、ある程度そこそこのHPができてしまうからです。
私自身もクライアントワークを多くこなしていますが、極力標準機能の中で対応し、CSSをカスタムするのは最終手段。別途見積が発生するぞ、ぐらいの位置づけです。（低価格の制作なもので）  
あと、隣の部屋の人は、自社サイトを自力でLightning＋VK Blocks作っていますが、おそらくCSSカスタムはしていませんし、CSSそのものをあまりよく理解していないと思われます。

WordPressの良いところは、CSSの知識がなくとも、そこそこリッチなコンテンツ制作できる部分にあると思います。
ですから、ユーザーにCSSの知識がない人がいることは十分考慮されるべきことかと思います。
その上で、カスタムしたい人はCSSを自由にカスタムできるというのが理想だと思いますが、いかがでしょうか。

ブロックエディタの「CSSクラス」は、「意味がわからないし、使う必要もないので、使わない」という人も多いかと思います。私もユーザーとしてはほとんど使いません。そういう人にとって、「CSSクラス名」を決めるのはちょっと戸惑いますね。命名ルールもよくわかっていないですし。

>なぜなら、ユーザーが意図したクラス名は勝手に設定された感じ不快感を覚える可能性があるからです。

すみません。ちょっとここは意味が分かりませんでした。

>書式設定のクラス名は変えることが出来ないものです。DBに保存されるのでクラス名を変更すると過去の記事の装飾が外れます。クラス名は思考停止で作って欲しくないと言う意味を込めてモーダルにしてクラス名をきちんと考えるように促していました。

この機能については、クラス名とスタイルが紐付き、クラス名が消滅・変更されると、装飾がなくなるというリスクがあるわけですね。だからCSSクラスがよく分かっていない人はこの機能は使わないで欲しい的な位置づけなら、わかります。
でも、この機能はすごく便利なので、そうしたリスクも分かってもらえるなら、CSSクラスがよく分かっていない人にもつかってもらったらいいのかなとおもった次第です。

これを実装して頂くにしても、細かい実装方法は @shimotmk さんのやりやすい形で全然良いと思います。

**Comment by shimotmk** [comment]
なるほど。
CSSの知識があるのにCSSクラスがわからない人がいることが衝撃でした。

CSSのカスタマイズを一切許さない実装で作り直します
いや、やめたほうが良いなどあれば止めてください

**Comment by mthaichi** [comment]
> なるほど。 CSSの知識があるのにCSSクラスがわからない人がいることが衝撃でした。
> 
> CSSのカスタマイズを一切許さない実装で作り直します いや、やめたほうが良いなどあれば止めてください

@shimotmk いえいえ、「CSSの知識自体がないユーザー」や「CSSの知識があるけど、CSSカスタムをあまり行わないユーザー」もいるよ、ということです。そういう立場のとして意見をお伝えした次第なので、それを踏まえてもうちょっと他の方のご意見も伺った上で決めても良いのではないでしょうか。

なにはともあれ、ご調整感謝いたします。

**Comment by shimotmk** [comment]
@mthaichi 
結論はどんな形が理想だと考えていますか？
それがないと他の方の意見も聞くことができないと思います

**Comment by mthaichi** [comment]
@shimotmk  私の理想はこれですよ。

> テキストボックスにはじめから自動でクラス名が入っているのではなく、必須項目を外して、
> 空白のまま送信するとクラス>名が決まるという感じではどうでしょう。指定したい人が指定をする。指定したくない人は空白。

**Comment by shimotmk** [comment]
@mthaichi 
それに対する考えはここに書きました。
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1328402014

わからないことがあれば聞いてください

**Comment by mthaichi** [comment]
@shimotmk 

>なぜなら、ユーザーが意図したクラス名は勝手に設定された感じ不快感を覚える可能性があるからです。

この部分の意味が分かりませんでした。
ユーザーが、意図していないクラス名をつけられることに対して不快感を覚えるってことですか？

>書式設定のクラス名は変えることが出来ないものです。DBに保存されるのでクラス名を変更すると過去の記事の装飾が外れます。クラス名は思考停止で作って欲しくないと言う意味を込めてモーダルにしてクラス名をきちんと考えるように促していました。

クラス名は変更できなくて良いと思います。
削除すると装飾が外れるということだけ注意書きできないでしょうか。

>そのため私としてはクラス名のカスタマイズを一切許可しない、もしくはバリテーションを付けた今の実装のどちらかだと思います。

私は「どちらかにする」必要性が今のところわかりません。

一番申し上げたいのは、WordPressはCSSが分からない人でもコンテンツ制作を容易にできるメリットがあるのだから、CSSわからない人への配慮は必要ではないかということです。クラス名を意識しなくても、よく使う書式設定機能が使えたらいいなという私個人の意見を述べたまでです。

プロダクトとして、そこは優先順位が高くないという意見が多いならば、私はそこにこだわりません。

**Comment by shimotmk** [comment]
@mthaichi 
>  ユーザーが、意図していないクラス名をつけられることに対して不快感を覚えるってことですか？

そうです。

>  削除すると装飾が外れるということだけ注意書きできないでしょうか。

現状でも削除するときに注意を促していますが、見ていただけないのでしょうか？

>  一番申し上げたいのは、WordPressはCSSが分からない人でもコンテンツ制作を容易にできるメリットがある

この機能を使うだけであればCSSは分からなくても使えると思います。

**Comment by mthaichi** [comment]
>> ユーザーが、意図していないクラス名をつけられることに対して不快感を覚えるってことですか？
>
>そうです。

私はそういう人は少数派のように思います。アンケートとったわけじゃないんので、肌感覚ですが。
不快感を覚える人はクラス名を設定すればいいのだと思います。

> 現状でも削除するときに注意を促していますが、見ていただけないのでしょうか？

「保存したコンテンツにこのフォーマットがある場合、スタイルが変更されます。」の一文ですか？ 
なるほど失礼しました。「スタイルが解除されます」だと明確かなと思いました。

> この機能を使うだけであればCSSは分からなくても使えると思います。

それはそうです。私が申し上げているのは「CSSクラス」を決めるというのはCSSを知らない人にとって戸惑うものだということです。戸惑ったとしても例に従って何らかの英数文字列を指定してもらえれば使えるので、私は難しいならこのままでも構わないと最初から申し上げています。

**Comment by shimotmk** [comment]
@mthaichi 
> 私はそういう人は少数派のように思います。アンケートとったわけじゃないので、肌感覚ですが。
不快感を覚える人はクラス名を設定すればいいのだと思います。

ここが後から設定出来ないので最初からクラス名を入れたり、クラス名が入力されていないときは自動で補完するなどが出来ないのです。

もしクラス名を設定し直したいのであれば全ての記事をリライトするなどが必要になる可能性があります

>  「スタイルが解除されます」だと明確かなと思いました。

どちらでも良い気がしますが直しておきます

**Comment by mthaichi** [comment]
@shimotmk   
> ここが後から設定出来ないので最初からクラス名を入れたり、クラス名が入力されていないときは自動で補完するなどが出来ないのです。

読解力が悪くて申し訳ないのですが、「ここが後から設定できない」の意味がわかりません。
「書式新規作成時にクラス名を決めたい人はクラス名を指定し、クラス名をお任せにしたい人は空白にして追加ボタンを押下。クラス名が指定されていない場合はクラス名を自動生成。」というのが私なりの理想の仕様です。
最初から生成されたクラス名を入れる必要もありませんし、入力補完の必要もありません。

上記についてはあくまで「私の理想」なので、技術的に難しいですとか、そうした機能は必要がないという意見が多数であれば、このままの仕様で良いと思います。

**Comment by shimotmk** [comment]
@mthaichi 
> 読解力が悪くて申し訳ないのですが、「ここが後から設定できない」の意味がわかりません。

書式設定のクラス名はDBに保存されます。そのためユーザーが後から設定できません(変更できません)。
よって、「クラス名が指定されていない場合はクラス名を自動生成」などを実装しない理由です。

技術的な話はここで書きました。
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1328402014

**Comment by kurudrive** [comment]
@shimotmk @doshimaf @mthaichi 

> 「ここが後から設定できない」

これは "後から変更" はできないけど、初期に自動生成は技術的に可能ですよね？
実際使ってみて現状でも非常に素晴らしいのですが、
試した全員がクラス名入力の所でのみ唯一戸惑ったので、

> 「書式新規作成時にクラス名を決めたい人はクラス名を指定し、クラス名をお任せにしたい人は空白にして追加ボタンを押下。クラス名が指定されていない場合はクラス名を自動生成。」

が実現できればより良くなるとは思いました。
ただ、現状の画面が、

![スクリーンショット 2022-11-29 10 08 08](https://user-images.githubusercontent.com/3272660/204413564-dcc610ac-b7cb-4a09-b0a4-7595df9e4d87.png)

だったので、以下のように表記を調整するだけで迷わずにいけるかなという気もしますがどう？

**CSSクラス**（必須）
固有の識別名です。半角英数字で入力してください。後から変更はできません。
[ 　　　　　　　　　　　　　]

**ツールバー タイトル**（変更可能）
ブロックエディタのツールバーに表示される名前です。
[ 　　　　　　　　　　　　　]

**Comment by doshimaf** [comment]
@kurudrive @shimotmk @mthaichi 
私が戸惑った（悩んだ）のは、「CSSクラスを指定しなければならない」箇所ではなく「このカスタム書式に、どんなクラス名をつけようか」というところでした。
なので、丸山さんの
> 「書式新規作成時にクラス名を決めたい人はクラス名を指定し、クラス名をお任せにしたい人は空白にして追加ボタンを押下。クラス名が指定されていない場合はクラス名を自動生成。」
かつ「生成した後に変更はできない」という仕様か「クラス名は指定させず完全に自動生成」という仕様が個人的には嬉しいなと思い、はじめのコメントのhttps://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1322826481に至ります。

つづきます、

**Comment by kurudrive** [comment]
@shimotmk @mthaichi @doshimaf 

未入力の場合に自動指定はいろいろトラブルのもとになりそうなので、

* 完全自動生成
* 手動指定

の二択で考えると、制作会社が請負で使う場合に、

* VK Blocks Pro を使わなくなった時や、この機能にない装飾プロパティを自分で後から追加したい場合など、自分でCSSを書く事を想定すると意味を持つクラス名を付けたい
* CSS設計などをする人は意味を持たない連番のクラス名が自動で付く事を嫌がる

という事があるので、現状の仕様を踏襲しつつ、先のコメントのように表記補足だけで良いのかなというのが個人的見解です。

**Comment by shimotmk** [comment]
@mthaichi 

> @shimotmk
> 
> > ここが後から設定出来ないので最初からクラス名を入れたり、クラス名が入力されていないときは自動で補完するなどが出来ないのです。
> 
> 読解力が悪くて申し訳ないのですが、「ここが後から設定できない」の意味がわかりません。 「書式新規作成時にクラス名を決めたい人はクラス名を指定し、クラス名をお任せにしたい人は空白にして追加ボタンを押下。クラス名が指定されていない場合はクラス名を自動生成。」というのが私なりの理想の仕様です。 最初から生成されたクラス名を入れる必要もありませんし、入力補完の必要もありません。
> 
> 上記についてはあくまで「私の理想」なので、技術的に難しいですとか、そうした機能は必要がないという意見が多数であれば、このままの仕様で良いと思います。

DBに保存されると言う箇所が理解できていないのかな。
設定した書式設定を記事(post_type=post)で使用すると
```HTML
<span class=”format-classname”>hogehoge</span>
```
みたいな感じで
wp_postsのpost_contentに保存されます
そのためユーザーが後から設定できません(変更できません)。

**Comment by mthaichi** [comment]
@shimotmk @kurudrive  @doshimaf

要するに、技術的云々は置いておいて、
カスタム書式設定をつかっていくうちに、意味をなさないかつ修正が効かない自動生成的なクラス ・・・`<span class="vk-format--1">hoge</span>` みたいなのが、post_contentにたくさんばらまかれるのは、避けたいという気持ちが強いということですね。

であれば、その部分が「初心者のためにクラス名を自動生成にしたい」という要求より優先されるならば、クラス名の自動生成は見送ればよいのだと思います。

これはプロダクトの設計思想みたいなものなので、何を大切にするかは皆でシェアしていったほうが良いですね。

**Comment by shimotmk** [comment]
@mthaichi 
> 要するに、技術的云々は置いておいて、
カスタム書式設定をつかっていくうちに、意味をなさないかつ修正が効かない自動生成的なクラス ・・・<span class="vk-format--1">hoge</span> みたいなのが、post_contentにたくさんばらまかれるのは、避けたいという気持ちが強いということですね。

そうです!その通りです。

>  であれば、その部分が「初心者のためにクラス名を自動生成にしたい」という要求より優先されるならば、クラス名の自動生成は見送ればよいのだと思います。

これが本当に初心者のためになっているかが微妙です。わかりません
その場では自動生成されたクラスが入って便利と思うかもしれませんが、後々後悔する可能性があるのはその人です。
初心者も学習する可能性はあります。

そう思った時に矛先が向くのは便利だと思って余計な実装をした人です。
それであれば実装しないが吉だと思い今の実装にしてあります。

**Comment by kurudrive** [comment]
> 何を大切にするか

「初心者に使いやすい」は第一条件なのですが「プロユースにも耐える」というのも同様に大きいです。

で、手動設定だと初心者ユーザーにとって少し手間は増えるけど使える。
けど自動設定のみにしてしまうとCSSコーダー目線だと敬遠するユーザーが出てくるので、
両方のニーズを満たす確率としては手動かなというのが個人的見解です。

**Comment by shimotmk** [comment]
@mthaichi
こちらご理解いただけたでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1330027137

**Comment by mthaichi** [comment]
> @mthaichi こちらご理解いただけたでしょうか？ [#1057 (comment)](https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1330027137)

@shimotmk はい、理解したつもりです。このまま進めていただいて良いと思いますよ。

**Comment by shimotmk** [comment]
@mthaichi ありがとうございます！

@mthaichi さんのコメントにより仕様を勘違いしている人が出てきたりしたので他の人にとっても良い議論だったと思います。
感謝します。

**Comment by shimotmk** [comment]
@doshimaf 
クラス名の自動生成については最初技術的な話をしてしまいしたが、よくよく考えたら自動生成することがかえってユーザーのためになっていないと言う判断で実装しませんでした。
やりとりを見ていただけたらわかると思いますが、ここに結論があります。
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1330027137

最初からそれをコメントにしておけば良かったのに混乱させてしまいすみません🙇‍♂️

**Comment by shimotmk** [comment]
数時間まって特に無ければ今の状態でプルリクにします

**Comment by kurudrive** [comment]
@shimotmk 
実装ありがとうございました！非常に使いやすいと思います！

@kaorock72 
こちらリリースされたので次回入った時にお知らせ記事よろしくお願いいたします (￣人￣)
お知らせ記事は勉強回に間に合えばそれに越した事はないので優先度は高くしてますが、
口頭実演だけでも良いので、他に優先順位が高いものがあれば無理に間に合わせなくてもダイジョウブです。

**Comment by kaorock72** [comment]
@kurudrive 
お知らせ公開しました！説明でおかしな箇所あれば修正します、勉強会までにシェアする予定ですーー
https://www.vektor-inc.co.jp/product-update/vk-blocks-pro-1-48-0-add-custom-format-setting/

**Comment by kurudrive** [comment]
@kaorock72 ありがとうございます！わかりやすいと思います！

これにて close します！
