### ISSUE TITLE
[ 子ページリストブロック ] の表示要素の「画像右上分類名」と「分類」は不要かもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1113]
おそらく他のブロックにもあるカードの表示要素のなごりでのこっていると思うのですが、お客さんからご質問をいただいたので、子ページリストには不要かのしれないと思いissueをたてました

取るかどうかの相談したいと思いますので、ToDoに入れておきます。

**Comment by mtdkei** [comment]
マージされたのでCloseします
