### ISSUE TITLE
非表示クラスや余白クラスの制御を「高度な設定」の 追加 CSS クラス に入力する値での制御にしたいです

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1118]
現状ブロックのDOMに対して直接 class 名を出力しているが、
「高度な設定」の 追加 CSS クラス に入力するクラス名に反映される形にしたいです。

理由はこれができれば

* たぶんブロック毎に非表示処理のコード書かなくて良い
* 今後デザイン指定のクラスを複数組み合わせた表現がしやすくなる
（既存の register_block__style だと一つのデザイン指定しかできないので、例えば「直線・ピンカド」などの指定になるが、複数classの組み合わせができれば、線の種類 と Rの大きさを組み合わせるなど（現実にはこのあたりはコアが対応するのでもっと他のデザイン指定になるが） ）デザインの幅を広げる事ができる

SWELLの余白設定がその仕様になっているので、GitHub見れば参考になると思います。
https://github.com/loos/SWELL

**Comment by shimotmk** [comment]
- [ ] 非表示クラス
- [x] 余白クラス

**Comment by shimotmk** [comment]
リリースされたのでCloseします
