### ISSUE TITLE
【要再調整】【VK ブロックパターン】[ ステップブロック ] 勉強会でのリクエスト：横向きの流れが欲しい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#1134]
2022年3月25日のVWS勉強会「ブロック徹底解説」内で、
**横向きの流れ**があると嬉しいというリクエストがありました。

Slackメモ（ゆくゆく消えるかも）：
https://vektor-vws.slack.com/archives/C01A20ZGWMN/p1648211861824489

**Comment by kurudrive** [comment]
@goutetsuguma / Cc: @sysbird @doshimaf 

ありがとうございます。一旦パターンで出してみて、利用頻度が高かったらブロックに反映のほうが良いかなーと思いますので、パターンで作ってみてくださいー。

**Comment by goutetsuguma** [comment]
こちらにカスタムCSSで作業しました。
https://patterns.vektor-inc.co.jp/vk-patterns/side-by-side-flow/

**Comment by sysbird** [comment]
グリッドカラムカードで、さすがです！
カードのスタイルやアイコンも、あとで自分で変更できるのでいいですね
このパターン使ってみたいです

**Comment by goutetsuguma** [comment]
編集画面で丸の中の段落テキスト（stepとか書いてある部分）が編集しずらいことに気がつきましたので、もうちょっと考えます🙇‍♂️
![投稿を編集-“横並びフロー-横並びステップ”-‹-VK-パターンライブラリ-—-WordPress](https://user-images.githubusercontent.com/5525368/196093584-7477ac2b-3448-4d89-b302-a3dcc21422f4.png)

**Comment by ChiakiKouno** [comment]
くのうさん、ご調整ありがとうございます！
ちょうどその部分、入れ子になっているカスタムCSSが、コピペすると消えちゃうのですが、私だけかしら…？私だけかな？（カスタムCSSのカードにお知らせしてみます）

<img width="984" alt="Screenshot 2022-10-17 at 1 13 10 PM" src="https://user-images.githubusercontent.com/43702482/196094753-089ce667-7df4-4ad0-a073-70ca98eee01c.png">

**Comment by ChiakiKouno** [comment]
@goutetsuguma 問題なくペーストできました◎　いい感じです！ご調整ありがとうございました！

**Comment by ChiakiKouno** [comment]
こちらぜひ早く公開できると良いですね！埋もれちゃってる気がするので @kurudrive   にメンションさせてくださいませmm

[Discord でくのうさんより](https://discord.com/channels/1010092469863587892/1010175825930367019/1046595120465715261)：

> そういえば、VKパターンライブラリのパターン登録した「横並びフロー/横並びステップ」　は「カスタムCSS機能リリース待ち」でしたが、リリースされましたので公開してもよいのでしょうか？そして、Pro版なのでプレミアムパターンってことになりますかね？（プレミアムパターンにチェック入れました）
> 
> ▼issueはこちら
> https://github.com/vektor-inc/vk-blocks-pro/issues/1134
> ▼VKパターンライブラリはこちら
> https://patterns.vektor-inc.co.jp/vk-patterns/side-by-side-flow/

**Comment by kurudrive** [comment]
@ChiakiKouno @goutetsuguma 公開しました！

画面サイズ最小の時に矢印がなくなるので下向き矢印があるといいなと思いました。
あと、やはり編集画面に貼り付けるとデザインが全然違うという感じになっちゃうので、編集画面のCSSはカスタムHTMLブロックに書いて、必要に応じてユーザーが削除する感じでどうでしょう？

**Comment by ChiakiKouno** [comment]
公開ありがとうございました！ツイートさせていただこうと思います！

@goutetsuguma タイトルを再調整に変更しましたが、急がないでOKとのことのでまたおいおいゆっくりお願いいたします☺️
