### ISSUE TITLE
【管理画面 React 化版リリース待ち】[ 共通余白 ] xs / xl 追加 : ボタン下積みにした時のmargin-bottomをもう少し空けたい気がしましたがいかがでしょうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1155]
現在は5pxですが、8pxくらい？0.5remくらい？でいかがでしょうか。
（今まで使用していた人に若干影響が出てしまいますが、、）
下マージンを0にしてレスポンシブスペーサーなどで調整する手もありますが、ちょっと詰まりすぎな気がしましたのでブロック固有の余白を調整したいなと思いました。

<img width="1440" alt="スクリーンショット 2022-04-11 11 46 03" src="https://user-images.githubusercontent.com/5525368/162656702-4454355b-6cdd-4142-983a-9b003d5ef21d.png">

**Comment by shimotmk** [comment]
#1355 で対応されたのでcloseします
