### ISSUE TITLE
[ ボタンブロック ］ボタンサイズが大、標準、小だけだが、サイズを変更できるようにしたいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1161]
▼こんな感じの大きさを変える機能がほしいです
![固定ページを編集 “test” ‹ Lightning × ExUnit 日本語デモ — WordPress (1)](https://user-images.githubusercontent.com/5525368/162903865-3364e6a4-f4c2-4c7d-b94e-3aaed4c99820.png)

できれば、アイコンの色を変更できる機能がつくとうれしいです。
理由は、こんな見た目にもできるようにしたいためです。
![test _ Lightning × ExUnit 日本語デモ](https://user-images.githubusercontent.com/5525368/162906850-5ca66ce6-785e-4006-a9c6-da3eed959984.png)

**Comment by sysbird** [comment]
リリース済みにつき閉じます
