### ISSUE TITLE
【機能追加要望】［グループブロック］線の色にカスタムカラーパレットみたいな色を調整できる機能が欲しい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1172]
線の色が決まった色しか入れられないのが使いづらいので、もしカスタムカラーパレットが追加できるようなら、欲しいなと思いました。
<img width="1267" alt="スクリーンショット 2022-04-19 10 48 52" src="https://user-images.githubusercontent.com/5525368/163904724-09e32c3a-e915-4d41-b523-0ee921d3ef2c.png">

**Comment by kurudrive** [comment]
@goutetsuguma 
https://github.com/vektor-inc/vk-blocks-pro/issues/1033 と関連しているので close
