### ISSUE TITLE
【保留】[ タブブロック ] 新規実装

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1190]
タブブロックは実装中。
以下のブランチで作業している。
https://github.com/vektor-inc/vk-blocks-pro/tree/add/tab-block-new

その続きの以下の作業

- [x]  .vk_tab_bodys_body に padding 指定できるようにしたい（共通）
- [x] タブの色がタブ毎に変更できるように
- [x] Equal 1 Column 〜 Equal 4 Column 廃止 （ Fit Width で事足りる & CSSが多くなるため ）
- [x] 画面サイズは SP / タブレット / PC ３つに減らしたいです（ユーザーにとって設定項目が多い & CSSが多くなるため ）

**Comment by mtdkei** [comment]
タブブロックがリリースされたのでCloseします。ありがとうございました。
