### ISSUE TITLE
【お知らせ待ち】[ ボタンブロック ] キラーンのエフェクトが指定できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1207]
まずは一つスタイル追加してみて（・ｗ・

**Comment by goutetsuguma** [comment]
**メモ**　

- UIはこちらで作成中
- キラーンのエフェクトだけだと寂しいので、borderのエフェクト増やそうかな（css未）

https://www.figma.com/file/4bdwFjwkn6vOphzECs2X2P/vk-botton?node-id=0%3A1

**Comment by goutetsuguma** [comment]
@kurudrive @sysbird 

石川さん、トリさんおつかれさまです。
キラッと光るボタンと立体ボタンのエフェクトを追加したいと思い、Figmaに仕様をつくってみましたがいかがでしょうか。
仕様が問題なければ、トリさんに実装をお願いしたいと思っております。

▼相談したいこと
- VKボタンブロックとVK横並びボタンブロックにエフェクトを追加したいと思うのですが、難しいでしょうか

https://www.figma.com/file/4bdwFjwkn6vOphzECs2X2P/vk-botton?node-id=0%3A1

▼ボタンエフェクトのCSSのみ追加したブランチ
https://github.com/vektor-inc/vk-blocks-pro/tree/add/button-shine

**ベタ塗り光るボタンのHTML**
`<div class="wp-block-vk-blocks-button vk_button vk_button-color-custom vk_button-align-left"><a class="vk_button_link btn has-background has-vk-color-primary-background-color is-style-shine btn-md" role="button" aria-pressed="true" rel="noopener"><div class="vk_button_link_caption"><span class="vk_button_link_txt">ベタ塗り光るボタン</span></div></a></div>`

**ベタ塗り立体ボタンのHTML**
`<div class="wp-block-vk-blocks-button vk_button vk_button-color-custom vk_button-align-left"><a class="vk_button_link btn has-background has-vk-color-primary-background-color　is-style-solid btn-md" role="button" aria-pressed="true" rel="noopener"><div class="vk_button_link_caption"><span class="vk_button_link_txt">ベタ塗り立体ボタン</span></div></a></div>`

**Comment by sysbird** [comment]
キラーンを確認しながら、実装方法を考え中

**Comment by sysbird** [comment]
@goutetsuguma 
> * VKボタンブロックとVK横並びボタンブロックにエフェクトを追加したいと思うのですが、難しいでしょうか

CSSと Figma の仕様案ありがとうございます
ベタ塗りの場合だけ、ボタンエフェクトを選択できるかんじですね
ボタンエフェクトが選択されたら、aタグに `.is-style-shine` のように付与するようにします

CSSのみ追加したブランチで進めようと思います〜

**Comment by goutetsuguma** [comment]
@kurudrive 
@sysbird 

トリさんご確認ありがとうございます！

> ベタ塗りの場合だけ、ボタンエフェクトを選択できるかんじですね

はい、そうですmm

ーーー
【石川さんに軽く相談したいこと】
今回つくったボタンエフェクトは、ベタ塗りの場合にだけ表示されるエフェクトですが、
今後、背景無しの時にだけでるエフェクトも随時追加していく感じになるのかなと思っていたけど、cssブロックがでたらパターンに追加していくほうが管理が楽なのでしょうか、、？
などなど思ったり。またその辺もお話しできたらいいなと思います。

**Comment by sysbird** [comment]
@goutetsuguma 
エフェクトの名前で相談です
Solid はすでに「直線」と翻訳が付いてるので、なにか他の名前がよいのかな？

- Dimensional
- Shadow
- Solid Shadow などなど

**Comment by goutetsuguma** [comment]
ありがとうございます！翻訳のこと考えていなかった！！

候補ありがとうございます！
Dimensional にしましょうか？！

**Comment by sysbird** [comment]
Dimensional にしておきますか、翻訳は 「立体」で
ちなみに Solid Shadow と 2語になると 別の翻訳付けられますよ

**Comment by kurudrive** [comment]
@kaorock72 お知らせよろしくお願いいたしますー (￣人￣)

**Comment by kurudrive** [comment]
![スクリーンショット 2022-10-17 18 03 23](https://user-images.githubusercontent.com/3272660/196136559-30bede99-d949-4f97-8759-cc0a56280a4f.png)

**Comment by kaorock72** [comment]
@kurudrive お知らせ公開と各シェア完了しましたので、クローズいたします
https://www.vektor-inc.co.jp/product-update/vk-blocks-1-44-0-add-button-effect/

**Comment by kurudrive** [comment]
@kaorock72 ありがとうございました！
