### ISSUE TITLE
theme.json があるテーマでの カバーやグループブロック内の要素の 全幅 / 幅広対応調査

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1234]
## 問題点

現状 theme.json のあるテーマ（ https://github.com/vektor-inc/lightning/tree/feature/theme-json ）だと、インナーブロックで幅広や全幅が使えない

https://github.com/WordPress/gutenberg/issues/37036

これだと、

https://patterns.vektor-inc.co.jp/vk-patterns/online-semminar-page-free/

みたいに、カバーブロックの中に 幅広 要素を配置してはみ出す みたいなレイアウトができない。

## 対応案

本来はコアの「theme.json があったらインナーブロックの幅指定を無効化する」という機能を無効化するのが理想ですが、ちょっと難しいのではないかと思い、
共通余白のように 独自のUIを追加して、クラスに alignfull や alignwide を追加するようにするのが妥当ではないかと思いますがどうでしょう？

ただ、

* できればコアで使えるようになった時にそのまま移行できるように保存attribute名はコアに揃えたい
* だがしかしコアと同じattribute名だと、コアの幅指定機能と同じく無効化が効いてしまったりしないだろうか？

とか思ったりする今日この頃です。

出来そうかどうか検証よろしくお願いいたします  (￣人￣)

**Comment by shimotmk** [comment]
完了のようなのでcloseします
