### ISSUE TITLE
［スライダーブロック］全幅にした時、スライダーアイテムを追加するappenderの位置が左に寄っている

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1235]
![投稿を編集-“トップページスライダー”-‹-VK-パターンライブラリ-—-WordPress](https://user-images.githubusercontent.com/5525368/169181125-ac209fa5-e94d-4374-bf59-9ded1dcbe4cc.png)

https://patterns.vektor-inc.co.jp/vk-patterns/top-slider/

**Comment by mtdkei** [comment]
本件確認してみました。現在は全幅にした時、スライダーアイテムを追加するappenderの位置が左に寄っている 現象は無くなったようなので一旦Closeにいたします。
