### ISSUE TITLE
[ グループブロック ] プレビューで背景色が出ていないものがある

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#1238]
6.0 RC-3 で確認

プレビュースタイルで、
info, Success, Warning, Danger で背景色が出ておりませんでした。

![スクリーンショット 2022-05-19 午後4 07 33](https://user-images.githubusercontent.com/43702482/169245071-84bf0be9-a7ac-4843-a89c-9a702d8679fa.png)

**Comment by kurudrive** [comment]
大丈夫になってる close
