### ISSUE TITLE
【お知らせ待ち】[ 吹き出しブロック ] 吹き出しの幅を100%にするみたいな選択肢があると嬉しいかもしれないです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1288]
カラムブロックの中に吹き出しブロックを入れたい時がありまして、幅を100%にするチェックボックスがあると嬉しいなと思いissueを立てさせていただきました。

もし需要がなさそうであればCloseしてもらっても大丈夫です。

![非公開-オンラインコース-VK-パターンライブラリ](https://user-images.githubusercontent.com/5525368/174019825-73d11797-d7e8-4a64-9d81-9ba7e7b9dd96.png)

**Comment by kurudrive** [comment]
@kaorock72 リリースしましたので、次回お知らせよろしくお願いいたします。 (￣人￣)

**Comment by kaorock72** [comment]
お知らせ公開と各シェア完了しましたのでクローズいたします

**Comment by kaorock72** [comment]
お知らせ公開と各シェア完了しましたのでクローズいたします
https://www.vektor-inc.co.jp/product-update/vk-blocks-1-41-0-balloon-width-100/
