### ISSUE TITLE
[ アイコンブロック ] rem,em,vw指定の時に小数点が入るようになると使いやすいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1305]
現在は、サイズと余白をrem,em,vw指定にして、小数点をいれても「.」が消えてしまうようでしたので、issueをたてました。
もしむずかしそうであればCloseしてくださいmm

**Comment by sysbird** [comment]
はい、やります
パターン作ってて欲しいな〜と思ってたので

**Comment by sysbird** [comment]
リリース済につきクローズします
