### ISSUE TITLE
[ 横並びアイコン ] ブロックテーマのテーマエディタで横並びにならないので要修正

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1313]
症状

1. 日本語環境でVK Block Patterns 最新版をインストール・有効化
2. 新規投稿を追加
3. 左のサイドバーでパターン「プロフィール」を検索
4. アイコン部分が横に並ばずに縦に並んでしまう

![投稿を編集-“FSE対応テーマを開発しています”-‹-Lightning-×-ExUnit-日本語デモ-—-WordPress](https://user-images.githubusercontent.com/3272660/177940956-cc297dce-510c-4a88-9cce-76609ba53c96.png)

**Comment by shimotmk** [comment]
おそらくブロックテーマ以外でもiframeで横並びになっていない
![lightning](https://user-images.githubusercontent.com/42362903/178432694-ee76fddf-fb51-42d3-855f-1a1ab2cf0963.png)

テーマ：Lightning
