### ISSUE TITLE
ブロックテーマ&分割読み込みを有効にするとコアのブロックに追加したスタイルが公開画面側で効かないっぽいので直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1319]
発生手順

1. X-T9 を有効化
2. 設定 > VK Blocks で分割読み込みを有効にする
3. 記事編集画面で見出しブロックのスタイルを変更
4. 編集画面上では効く
5. 公開画面で効かない

2024.6.19  : まだ発生する

**Comment by shimotmk** [comment]
@kurudrive 
現時点ではブロックテーマでスタイルが効かないのはコアのバグのようです。

コアのticket,pull request
https://github.com/WordPress/gutenberg/pull/41020
https://core.trac.wordpress.org/ticket/55184

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1744 で処理するのでこちらは close
