### ISSUE TITLE
6.0でmargin-extensionのe2eでエラー

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1334]
@shimotmk @kurudrive 
テスト動かないようです
すみません、テスト環境がWordPress 5.9 でしたので、6.0.1にアップグレードしたらエラーが発生しますね

_Originally posted by @sysbird in https://github.com/vektor-inc/vk-blocks-pro/issues/1312#issuecomment-1192172228_

**Comment by kurudrive** [comment]
あー、なるほど...そういう事でしたか...。
また調査よろしくお願いいたします... (・ｗ・；

**Comment by shimotmk** [comment]
closed this as completed in #1340
