### ISSUE TITLE
[ 共通余白設定 ] 分割読み込みにすると反映されない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1343]
VK Blocks 設定で分割読み込みにすると、 [ 共通余白設定 ] が反映されないようです

- 編集画面では正常
- フロントで反映されないよう
- レスポンシブスペーサー、ブロックの上下余白

**Comment by sysbird** [comment]
@kurudrive 
さきほど終礼で言ってた現象です
ローカル環境で気のせいかと思ってたんですけど、環境作り直しても発生するので、
テストサイトで確認しました
下記でも発生します
↓↓↓
https://vk-block-test.vs4.nagoya/

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1595

の後で対応
