### ISSUE TITLE
非表示設定の非表示 ( 画面サイズ : xl )が効いていないようでした

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1351]
`vk_hidden-xl_v2`とクラス名が付与される
scssファイルは`vk_hidden-xl-v2`になっている

https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/extensions/common/hidden-extension/style.scss#:~:text=%26%2Dxl%2Dv2,%7D

▼報告のあったフォーラム
https://vws.vektor-inc.co.jp/forums/topic/%e9%9d%9e%e8%a1%a8%e7%a4%ba%e8%a8%ad%e5%ae%9a%e3%81%ae%e4%b8%8d%e5%85%b7%e5%90%88#post-67344

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/pull/1349
