### ISSUE TITLE
[ 枠線ブロック ] X-T9 で見出し部分が崩れるので直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1353]
見た感じタイトル部分が inline-block なのでだめっぽい？
display:block; にして幅を fit-content にすれば良いと思われます。

![VK-Blocks-ブロックサンプル-デザイン要素サンプル-Lightning-×-ExUnit-日本語デモ](https://user-images.githubusercontent.com/3272660/182977803-cc010403-c8a8-42a6-a7e5-842df9b24122.png)

**Comment by mtdkei** [comment]
確認してみたところ、現在は X-T9でも見出し部分が崩れるということは無くなっていたのでCloseします
