### ISSUE TITLE
[ パンくずブロック ] トップページでは表示されないようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1354]
トップページにはパンくずリストは基本的に不要
フッターとかに配置した場合、トップページに表示されてしまう。

トップページの場合非表示にするチェックボックスが....
いや、ん？チェックボックスとか関係なくトップページの場合は問答無用で非表示でいいんじゃね？
そうしよう。

VK Blocks 側でいけると思うけどもしかしたら↓側の修正かも。
https://github.com/vektor-inc/vk-breadcrumb

**Comment by doshimaf** [comment]
merge済なのでCloseします
