### ISSUE TITLE
蛍光マーカー alphaを使用したカラーパレットを使った時に色がつかない

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1356]
・theme.jsonなどではカラーパレットでalphaが指定されることがある
https://github.com/vektor-inc/x-t9/blob/master/theme.json

・蛍光マーカーはカラーパレットに自動でalpha=0.7がつく
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/extensions/common/highlighter/index.js#L27

alpha 0.1などが付いているときに自動で0.7にするかカラーパレットのままにするか仕様を検討する必要がある
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/utils/hex-to-rgba.js

今後カラーパレットでalphaを指定できるようになるっぽいので
https://github.com/WordPress/gutenberg/pull/37731
alphaがある時はrgbaのままで良いですか

それともalphaは強制的に0.7変換したほうが良いですか
デザイン得意な方ご意見いただければと思います🙏

**Comment by kurudrive** [comment]
アルファのある色の場合は 0.7 ではなくカラーパレットに指定のアルファを反映する方向でよろしくお願いいたします。

**Comment by shimotmk** [comment]
リリースされたのでcloseします
