### ISSUE TITLE
Outerブロック上のOuterブロックの枠線色が反映されない

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1361]
https://vws.vektor-inc.co.jp/forums/topic/outer%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e4%b8%8a%e3%81%aeouter%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%81%ae%e6%9e%a0%e7%b7%9a%e8%89%b2%e3%81%8c%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84

こちら原因がわかったので調整します。

**Comment by kurudrive** [comment]
@shimotmk ありがとうございました。リリースしました！
