### ISSUE TITLE
設定画面でエラーが発生して表示されないので直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1365]
## 今までの調査

* 特定のユーザー環境でのみ発生
* 発生環境のDB情報をインポート
* build を非圧縮で実行し、コンソールのエラーメッセージを確認
* どうやら src/admin/margin.js の AdminMargin がわるいっぽい
* margin.js 内のコードをいろいろコメントアウトして、正常に表示されなくなる場所を調査
* NumberControl をコメントアウトすれば表示されるので NumberControl の中身が悪いっぽい
* エラーが発生する db と発生しない db を切り替えて vkBlocksOption の中身を確認
* エラーが発生する db だと vk_block_options に値は入っているが margin_size のメンバが存在しない
* → __vk_block_options[margin_size]__ が存在しない状態での処理に不具合がある

## 検証方法

vk_block_options の配列が存在するが margin_size がない状態にする

例えば vk-blocks.php に

```
$option_error = array(
	'balloon_border_width'      => '1',
	'display_vk_block_template' => 'display',
	'margin_unit'               => 'rem',
	'new_faq_accordion'         => 'close',
);
update_option( 'vk_blocks_options', $option_error );
```

など書いて、vk_block_options を書き換えると、おそらく 設定 > VK Blocks の画面でエラーが発生して中身が表示されなくなる

逆に `delete_option( 'vk_blocks_options' );` すると、デフォルト値が入ってくるのでエラーにならない

**Comment by kurudrive** [comment]
あ、
https://github.com/vektor-inc/vk-blocks-pro/pull/1363
と関連するのか。

**Comment by drill-lancer** [comment]
解決済みのようなので Close
