### ISSUE TITLE
[ ダイナミックテキスト表示ブロック ] 新規作成

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1366]
カスタムフィールドの内容などを返すダイナミックブロックが欲しい
基本文字列だけ返す

表示要素（セレクト）
* 選択してください
* 表示中のページの投稿タイプ名（ [ここからひっぱる](https://github.com/vektor-inc/vk-helpers/blob/320155b9df7f9f57a889e144dd8b379184ac15ec/src/VkHelpers.php#L62) ）
* 表示中のページの先祖階層の固定ページ名
* カスタムフィールド （後日追加実装でも可）
*（恐らく今後カスタムフィールド以外（ユーザーメタなど）のダイナミックテキストを表示したくなると予想）

### カスタムフィールドが選択されている場合（後日実装でも可）
* 対象のカスタムフィールド名

wp_kses_post() などでエスケープして文字列を返す

**Comment by goutetsuguma** [comment]
@kurudrive 
@doshimaf 

ブロックのアイコンを作業ブランチにプッシュしました。
どうでしょうか？
いろいろ迷って、、、文字が表示されるようなイメージのシンプルな感じにしました

![icon](https://user-images.githubusercontent.com/5525368/211476985-28960d9b-8588-4343-a057-c35bed28410d.svg)

▼figmaファイル
https://www.figma.com/file/Y5AqJ0EmIbxbVJo8JMC0Kg/VK-Blocks-Icons?node-id=0%3A1&t=nPq0zQmILv0A7gpC-1

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございます。
せっかくなので A は D の方がいいかなとか思いますがどうでしょう？

**Comment by goutetsuguma** [comment]
@kurudrive 
なるほど！Dの方がDynamic感でますね！早速直してプッシュしておきます！ありがとうございます！

**Comment by goutetsuguma** [comment]
icon修正して作業ブランチにプッシュしました。
ご確認よろしくお願いいたします。

![icon](https://user-images.githubusercontent.com/5525368/211480558-c0fe88c5-b6bd-40fe-bfc4-77308ee48893.svg)

**Comment by doshimaf** [comment]
@goutetsuguma 
ありがとうございます！

**Comment by kurudrive** [comment]
@doshimaf 

wrap するタグの指定が必要でした。
グループブロックなどが div か section か article か選択するやつがあるので、同様のが欲しいです。

選択肢

* なし
* h1
* h2
* h3
* h4
* h5
* h6
* div
* span

**Comment by doshimaf** [comment]
@kurudrive 

ありがとうございます。
wrapするタグの選択肢ですが、「なし」も必要でしょうか？

**Comment by kurudrive** [comment]
@doshimaf そうね、例えばテーブルの中でカスタムフィールドを読み込む場合にありえるかなと。

なし だと技術的にちょっとむずかしいんだっけ？
わからなかったら 下村さんかRICKさんに聞いてみてー。

**Comment by doshimaf** [comment]
@kurudrive 
wrapするタグの実装はある程度できたのですが、なし の場合だけエラーが出るので不要であればと思った次第です。
もう少し調整してみます。

**Comment by kurudrive** [comment]
仕様上無理かもしれないので、ぼちぼち調べてみて 無理っぽかったらサクっと諦めてシム村さんかRICKさんに聞いてみて。
無理だったら div をデフォルトで。

**Comment by doshimaf** [comment]
https://github.com/vektor-inc/vk-blocks-pro/pull/1527
wrapするタグが なし 以外だと正常に動作する状態です。
なしを選択すると`The above error occurred in one of your React components:`とエラーになります。
当然ですが、レンダリングされない場合はなしにしてもレンダリングされない旨のアラートが正常に表示されます。

@shimotmk @drill-lancer 
wrapするタグがなしだと仕様上正常に動作しないものでしょうか？
なしでもできそうなものであれば、教えていただけると助かります。

**Comment by drill-lancer** [comment]
@doshimaf 
ServerSideRender で使う edit.js の blockProps は編集画面上でブロックを選択しやすくする意味しかありません。
表画面に wrap するタグを反映させるには PHP に引っ張ってきてそこであれこれ処理するよりないと思います。

**Comment by doshimaf** [comment]
@drill-lancer 
フロントに反映されるよう、調整しました。
なし でもエラーが出なくなり、フロントでは意図通り表示されるようになりましたが、編集画面のソースが、div>div>ダイナミックテキストとなり、グループブロックのようになりません。

**Comment by drill-lancer** [comment]
@doshimaf 
私が想定している感じにはなっています。

> 編集画面のソースが、div>div>ダイナミックテキストとなり、グループブロックのようになりません。
編集画面で div が一つ多くなるのは ServerSideRender を使う以上こうなるのは仕方がありません。
あとは CSS で編集画面で使いやすく調整するくらいですかね。

**Comment by doshimaf** [comment]
@drill-lancer 
ありがとうございます！

@kurudrive 
仕様としては、現在のもので問題なさそうでしょうか？
なければ調整してプルリクをオープニンしようと思います。

**Comment by shimotmk** [comment]
返信遅れてすみません
そもそもwrapするタグなしでテキストを出力することはHTMLの構造としてあまり良くないかもしれないです
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q11251043551

ダイナミックテキストを”テキスト”として動かすならばブロックではなくツールバーなどからテキストを挿入する形になるかなと思います

**Comment by doshimaf** [comment]
wrapタグは、「なし」はなしで、「div」をデフォルトに。

**Comment by kurudrive** [comment]
@doshimaf あ、これは wrap のタグを無しにできるかって話で、特定条件の時に出力自体をなしにするという話ではなかったね。
（特定条件の時に出力自体をなしにするのは他のブロックでもやってるしね...）

**Comment by kurudrive** [comment]
@doshimaf 以下の処理追加よろしくお願いいたします。

プルダウンで先祖階層のページを選択した場合
→ プルダウンの下に「このブロックは親階層を持つ固定ページ以外のページでは表示されません。」のアラートを表示 alert alert-warning

vk_blocks_dynamic_text_render_callback の最初に、特定の条件（↑）の場合には何も返さずに return する処理を追加

**Comment by doshimaf** [comment]
承知しました。

**Comment by doshimaf** [comment]
何も返さずにreturnする場合、下記のようになるという仕様でしょうか？

<img width="838" alt="スクリーンショット 2023-05-09 14 25 08" src="https://user-images.githubusercontent.com/73574599/237001801-4ddec682-e4ec-4caa-9ca8-5a26db03b97e.png">

**Comment by doshimaf** [comment]
>プルダウンで先祖階層のページを選択した場合
>→ プルダウンの下に「このブロックは親階層を持つ固定ページ以外のページでは表示されません。」のアラートを表示 alert >alert-warning

>vk_blocks_dynamic_text_render_callback の最初に、特定の条件（↑）の場合には何も返さずに return する処理を追加

それぞれプルリクにコミットしています。

**Comment by kurudrive** [comment]
@doshimaf ありがとうございます。
サイトエディタ上では動的に取得すると意図しない文字列になるので、
サイトエディタ上ではコアの他の動的ブロック同様に「投稿タイプ名」「先祖階層のページ名」などにしてしまいましょう。
コアの投稿タイトルブロックが参考になるかと。
https://github.com/WordPress/gutenberg/blob/d24ac78b12d5e90afe8d095e81dfce623e235518/packages/block-library/src/post-title/edit.js#L52-L54
ちなみにこれ最優先でよろしくお願いいたします (￣人￣)

**Comment by doshimaf** [comment]
リリースされたのでclose
