### ISSUE TITLE
[アニメーション]動くのはページを表示したときだけにしたい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1369]
アニメーションはページを表示したとき1回でいいな、と思うときがあります
いまのところスクロールするたびに繰り返し動くので、繰り返す/繰り返さない 選べると嬉しいです

**Comment by sysbird** [comment]
@kurudrive 
こちら、私は気になります
 「繰り返す/繰り返さない」のようなオプションを追加したいです。
対象になるのは、フェードイン/スライドアップ/スライド左/スライド左 と思います。

着手してもよいでしょうか？

**Comment by goutetsuguma** [comment]
わたしも1回がいい派です！オプションあるとありがたいです！
（フォーラムでもそのような意見があったと思います）

**Comment by sysbird** [comment]
確認済、着手します〜

**Comment by sysbird** [comment]
マージされたので Close
