### ISSUE TITLE
管理画面保存ボタンを画面下に追従するのはどうでしょうか。

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1374]
画面上に保存ボタンが無い状態がある
その時に「変更を保存」ボタンを押し忘れそうとなりました
https://github.com/vektor-inc/vk-blocks-pro/issues/1057#issuecomment-1212944652

![vk-admin](https://user-images.githubusercontent.com/42362903/184807092-23bca90f-922a-49e3-9e16-597b7a3a3cd6.png)

注意書きを追加するのは簡単ですが今後もそういった状況はあるかもしれないので、管理画面保存ボタンを画面下に追従するのはどうでしょうか。
イメージ
https://coliss.com/articles/build-websites/operation/css/css-position-sticky-how-it-really-works.html#:~:text=%E5%90%8C%E3%81%98%E6%8C%AF%E3%82%8B%E8%88%9E%E3%81%84%E3%81%A7%E3%81%99%E3%80%82-,position%3A%20sticky%3B%E3%81%AE%E4%BE%BF%E5%88%A9%E3%81%AA%E4%BD%BF%E3%81%84%E6%96%B9,-%E3%81%BB%E3%81%A8%E3%82%93%E3%81%A9%E3%81%AE%E5%A0%B4%E5%90%88

https://user-images.githubusercontent.com/42362903/184807111-7034ad93-0d2d-4c46-977f-fc38bb46bf1b.mp4

developer toolsで試作してみましたが、もしかするとvektor-wp-librariesを調整する必要があるかもしれません。
https://github.com/vektor-inc/vektor-wp-libraries/tree/master/vk-admin

デザイン得意な方ご意見いただければと思います🙏

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます！

保存ボタンは全ての設定値を保存するのでプログラム的な調整は無いです。
なので @goutetsuguma さんか @sysbirdさんお願いできますか。

保存ボタンは

コンポーネントをインポートして
```js
import { SaveButton } from '@vkblocks/admin/save-button';
```

ボタンを置きたい場所に読み込んだコンポーネントを書けば出来ます。
```js
<SaveButton
	vkBlocksOption={vkBlocksOption}
	vkBlocksBalloonMeta={vkBlocksBalloonMeta}
/>
```

わからなければ聞いていただければと思います

**Comment by sysbird** [comment]
マージされたので閉じます
