### ISSUE TITLE
カスタムストアを作る

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1379]
今後、グローバルな設定を各ブロックから保存するというケースが増えると思います。
その時にoption値をReactから呼び出す・保存するというパターンになってくるので、以下のような感じで読み書きできるようにしたいです。

```
// 読み
const options = useSelect( (select) => {
     select('vk-blocks/options').getOptions();
}, []);

// 書き
const { setOptions } = useDispatch('vk-blocks/options');
setOptions(options);
```

というイメージです。これを実現するにはカスタムストアが必要です。

参考：
[Registering a Store](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registering-a-store)

@shimotmk さんが、POSTのREST APIを作ってくださったので、GET/POST対応して、カスタムストアが間に入って橋渡しする感じです。JSからのオプション値の読み書きはこれに集約したらいいかなと思います。

#1109 #1056  を対応する中で実は作りかけておりますが、一応確認したほうが良いなと思いまして。
@kurudrive  @shimotmk @drill-lancer  ご意見・ご質問あれば頂ければと。

**Comment by shimotmk** [comment]
@mthaichi 
カスタムCSS識別表示 ストア経由で保存しています
#1501
@mthaichi さんの方でトライしていた感じで気づくところなどあったらご指摘お願いします🙏

**Comment by mthaichi** [comment]
> @mthaichi カスタムCSS識別表示 ストア経由で保存しています #1501 @mthaichi さんの方でトライしていた感じで気づくところなどあったらご指摘お願いします🙏

@shimotmk ありがとうございます！ なかなか手が回らず、気を使って頂いてすみません。
助かります。拝見します。

**Comment by mthaichi** [comment]
@shimotmk ありがとうございます。さすがといいますか、特に大きな問題ないのではないでしょうか。

自分の書いたソースも恥ずかしいのですが、一応プッシュしておきました。
https://github.com/vektor-inc/vk-blocks-pro/tree/try/vk-blocks-store/src
ここでは試しに、下村さんが作ってくれた設定画面を localize_script 経由で取得していたのをカスタムストアで表示するという実験をしています。参考にもならないかもしれませんが、シェアしておきますね。

吹き出し関連は困りますよね。vk_blocks_optionsに統一させてもいいと思います。

**Comment by shimotmk** [comment]
@mthaichi 
ありがとうございます！
拝見させていただきます！

**Comment by shimotmk** [comment]
@mthaichi
> 吹き出し関連は困りますよね。vk_blocks_optionsに統一させてもいいと思います。

これはvk_blocks_optionsに統一させようと思っています。
ただ、オプション値はvk_blocks_optionsや吹き出し以外にもあるので増えた時にも対応できるように考えた方が良さそうです。

--- 
storeはビルドファイルを変えているのですね。
管理画面(`options-general.php?page=vk_blocks_options`)で使用を想定していると思うのですが、ブロックエディターでの利用をしたいと思うのでブロックエディタのファイルに入れたのですが、その辺りは何か考えがありましたか？？
テスト的に作っていたのであれば大丈夫です！

---

このあとのストアについてどのように進めましょうか？
@mthaichi の方で進めてもらっても構わないですし、他の作業があるから私に頼みたいなどあれば続けて作業しようかと思いますが、、

**Comment by mthaichi** [comment]
@shimotmk  お疲れさまです。ご確認ありがとうございます！

> その辺りは何か考えがありましたか？？

深い考えはありません。

>このあとのストアについてどのように進めましょうか？

よかったら @shimotmk さんの方で実装を進めていただけると嬉しいです。
私はどうしても時間がかかってしまうので。
実装する上でなにかあれば、いつでもお声がけください！

**Comment by shimotmk** [comment]
#1710 で作ったのでcloseします
