### ISSUE TITLE
vk_block_options の中の display_vk_block_template は廃止された機能なので削除したい。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1383]
WordPressコアにブロックパターンが実装される前に VK Blocks Pro に独自実装したブロックパターン機能を非表示にするためのものと思われる。
確認した限りやはり使われてないっぽいので

https://github.com/vektor-inc/vk-blocks-pro/pull/1373

のマージ後に削除したい

**Comment by shimotmk** [comment]
#1586 で対応済みなのでclose
