### ISSUE TITLE
レスポンシブスペーサーは一番下では使えないっぽい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1384]
レスポンシブスペーサーを一番下の要素で使うと無効になるのは仕様でしょうか？
margin-top で設定されているからでしょうか(編集画面では表示されている)
コアのスペーサは height なので一番下に置いても有効です

グループの背景色を付けて下の余白付けたいのですが、レスポンシブスペーサーでできない、グループの余白でやればよいかもしれないですね。
レスポンシブスペーサーはPC、タブレット、モバイルと設定できるので便利と思ったんですけど

**Comment by kurudrive** [comment]
@sysbird 

> レスポンシブスペーサーを一番下の要素で使うと無効になるのは仕様でしょうか？

意図的にそのような指定にはしていないと思います。
該当のURLなど症状がすぐに確認出来る情報があると助かります。

**Comment by kurudrive** [comment]
あ、CSSの仕様の都合でマージンでは効かないのではないかと思います。
レスポンシブスペーサーの設定を height に切り替えて利用してください。

**Comment by kurudrive** [comment]
@sysbird issue は立てても assignees など指定しないと気づかれずにissueだけ溜まっていってしまうので、対象と思われる人を適当に何人かわりふってくださいー。

**Comment by sysbird** [comment]
> レスポンシブスペーサーの設定を height に切り替えて利用してください。

選べるのですね！
気が付かなくてたいへん失礼いたしました
height で解決するのを確認しました
→ Twitter でつぶやくのに入れておこう〜

閉じます！
