### ISSUE TITLE
【確認待ち】管理画面 本文よりもサイドバーが長い時最下部までスクロール出来ない

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1392]
本文よりもサイドバーが長い時最下部までスクロール出来なくなります。
管理画面をGutenbergにする前から発生していました
おおよそ１２００px以上で発生すると思います

テーマ:Lightning
プラグイン:VK Blocks Proのみ

https://user-images.githubusercontent.com/42362903/186356488-2cef3532-db7e-4e2f-b113-2ab9d2f897e8.mp4

おそらくサイドバーを追従させたいと思うのですがvk-adminのvk_admin.jsで作るよりもcssのstickyで実装したほうがシンプルに出来るのではと思います
https://github.com/vektor-inc/vektor-wp-libraries/blob/master/vk-admin/package/js/vk_admin.js

実装する時は、これが終わってから
#1374

**Comment by kurudrive** [comment]
@shimotmk あー、これ相当古い独自実装だからそろそろ潮時ですね。ありがとうございます。
js 処理廃止の方向で調整します！

**Comment by shimotmk** [comment]
#1408 で対応されたのでcloseします
