### ISSUE TITLE
動的条件分岐ブロック技術検証

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1394]
## やりたい事

* 動的条件分岐の中にインナーブロックでブロックを配置して、ページによって出し分けたい。
* 条件分岐の条件をサイドバーで指定する。

例えばチェックボックスで

表示するページ
* フロントページ（is_front_page()）
* 固定ページ（is_page()）
* 個別投稿ページ（is_single()）

みたいな選択があり、例えば固定ページにチェックされたら、
固定ページの中でさらにどのページにするかのUIが出てくるとか...

とりあえずまずは選択機能はなくて良いので、インナーブロックの表示を条件分岐処理する事が可能なのかテストして欲しい

**Comment by kurudrive** [comment]
@shimotmk この件できれば今の時点でわりと急ぎで使いたいのですが実際試してみて無理そうでした（・ｗ・？

**Comment by shimotmk** [comment]
@kurudrive 
たしか、条件分岐タグ(`フロントページ（is_front_page()）、固定ページ（is_page()）、個別投稿ページ（is_single()）`)は出来そうだったと思います。
それ以上のことをする場合にどうしようか迷ってた気がします

**Comment by kurudrive** [comment]
@shimotmk 了解でございますー。ありがとうございます。ちょっと僕の方でも実験してみますー。

**Comment by kurudrive** [comment]
実験先を下記に移行したのでclose
https://github.com/vektor-inc/vk-dynamic-if-block
