### ISSUE TITLE
画像のスタイルに円がほしい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1397]
画像を正円に表示するには、いまのところ画像サイズをサムネイルにすて角丸を選択するしかない
フルサイズのまま正円で表示したい
(もともとの画像を正方形にすれば解決しますが…できたら便利です)

**Comment by kurudrive** [comment]
過去にもあったのですが、まぁでもそのままできた方が楽ではありますよね...
https://github.com/vektor-inc/vk-blocks-pro/issues/513

**Comment by sysbird** [comment]
「CSSの小技」に対応方法があり、
これからはカスタムCSSでできるので、クローズしますね
https://www.vektor-inc.co.jp/post/2022-css-kowaza/
