### ISSUE TITLE
[グリッドカラムカード] 編集画面用のCSSがフロントに出力されている

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1399]
編集画面用のCSSがフロントに出力されているので修正する
・editor.scssをeditor-cssに移動する
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/blocks/_pro/gridcolcard/editor.scss

**Comment by sysbird** [comment]
マージしたので閉じます
