### ISSUE TITLE
【相談待ち】スライダーブロック : ぐにょーっと横に動き続けられない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1416]
https://seki-koumuten.co.jp/

**Comment by drill-lancer** [comment]
https://web-dev.tech/front-end/javascript/swiper-infinite-loop-slide-show/

```
/* スライダーのwrapper */
.infinite-slider .swiper-wrapper {
  transition-timing-function: linear;
}
```

これを追加すれあとは画像のような感じでいけそうです。
![slider](https://user-images.githubusercontent.com/38716787/192671326-695fcbf3-719e-4f1c-85f4-bc2cd13a5487.jpg)

**Comment by goutetsuguma** [comment]
スライダーブロックにcssいれてみました
https://demo.dev3.biz/architect/interview/aichi-amashi-isama/

**Comment by drill-lancer** [comment]
パターンとして実装されたようなので Close
