### ISSUE TITLE
FAQブロックのfont-family について iOSのsafariでゴシック表示できる指定

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1420]
https://vws.vektor-inc.co.jp/forums/topic/%e6%96%b0faq%e3%81%aefont-family%e6%8c%87%e5%ae%9a%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6

**Comment by mtdkei** [comment]
fixがマージされましたのでCloseします
