### ISSUE TITLE
WordPress 6.1 PopoverのDOMが変わったようなのでスタイル調整

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1431]
WordPress 6.1でPopoverのDOMが変わるようなのでスタイル調整する
アイコンブロックなどで使用しているFontAwesomeのPopover
![iconPopover](https://user-images.githubusercontent.com/42362903/191702678-9fd4c606-8d5d-46f8-8baf-ed294e1b0df9.png)

6.1-beta1で確認

**Comment by mthaichi** [comment]
@shimotmk  これPopoverというよりも RadioControlの構造が変わったっぽいですね。
VStackコンポーネントでラップされるようになったので、div が一個加わって、flexが効かなくなった系です。
私の方で直しちゃって大丈夫ですかね。

**Comment by shimotmk** [comment]
> @shimotmk これPopoverというよりも RadioControlの構造が変わったっぽいですね。 VStackコンポーネントでラップされるようになったので、div が一個加わって、flexが効かなくなった系です。 私の方で直しちゃって大丈夫ですかね。

@mthaichi 
ありがとうございます🙏お願いします！

**Comment by shimotmk** [comment]
#1454 で対応されたのでcloseします
