### ISSUE TITLE
【相談待ち】Cocoonのテーマでヘッダー幅が変わってしまう（Boostrap）

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1439]
フォーラムで以下の要望がありました。
Boostrapのコンテナの幅が聞いて、ヘッダー幅が縮まるようでした。
対応するのかどうか、対応可能かどうかも含めていったん相談まちに置いておきます。

https://vws.vektor-inc.co.jp/forums/topic/vk-blocks%e3%82%92%e6%9c%89%e5%8a%b9%e5%8c%96%e3%81%99%e3%82%8b%e3%81%a8cocoon%e3%81%ae%e3%83%98%e3%83%83%e3%83%80%e3%83%bc%e5%b9%85%e3%81%8c%e5%a4%89%e3%82%8f%e3%81%a3%e3%81%a6%e3%83%ac%e3%82%a4

**Comment by kurudrive** [comment]
たぶんもう脱BootstrapしてるからOK
