### ISSUE TITLE
【お知らせ待ち】[ 投稿リストブロック ] タクソノミーでの絞り込み仕様変更

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1447]
https://vws.vektor-inc.co.jp/forums/topic/vk-post-list-tax-query

**最寄駅で絞り込み**
長岡駅

**家賃で絞り込み**
60,000円台

添付画像を合わせてご参照ください。

このとき、「長岡駅 かつ 60,000円台」で絞り込んでほしいところですが、
「長岡駅 または 60,000円台」の動作になり、
他の駅の物件や60,000円台以外の物件も表示されてしまいます。

かつ(AND) で絞り込むようにしていただけるとありがたいです。

**Comment by kurudrive** [comment]
![スクリーンショット 2022-10-17 17 58 05](https://user-images.githubusercontent.com/3272660/196135300-aa9bb7cb-491c-4f9e-80f9-2f3444a97594.png)

**Comment by kaorock72** [comment]
こちら公開完了していますので、クローズいたします！
https://www.vektor-inc.co.jp/product-update/vk-blocks-pro1-44-0-post-list/
