### ISSUE TITLE
[グリッドカラムブロック]の余白関連の数字でem、rem、vwにした時に小数点が設定できない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1453]
仕様なのか、修正できるのか（修正するのか）どうか　の相談になります。

前からある「グリッドカラム」ブロックの方です（グリッドカラムカードの方ではないです）

**Comment by doshimaf** [comment]
編集画面のinput要素のstep属性に1が指定されているからかもしれません。

<img width="878" alt="スクリーンショット 2022-10-18 11 55 57" src="https://user-images.githubusercontent.com/73574599/196325147-ffcb4a96-7725-4990-88ba-cdf6e2bc92e0.png">

見出しブロックの余白のstep属性は0.1が指定されており、小数点第一位まで指定することができました。
<img width="798" alt="スクリーンショット 2022-10-18 12 06 41" src="https://user-images.githubusercontent.com/73574599/196326319-3019cdf8-e477-437e-b96f-9e661354f26d.png">

**Comment by kurudrive** [comment]
@doshimaf @goutetsuguma 
rem指定なら 0.1 単位で普通に使うので 0.1 でよろしくお願いいたします。

**Comment by doshimaf** [comment]
リリースされたのでcloseします。
