### ISSUE TITLE
スライダーブロック 無料化..

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1477]
個人的にはプロ版にしたいが書籍のデモサイトを作るにあたって使いやすいスライダープラグインが存在しない。
Lightning が選ばれる決め手もスライダーが標準装備だった事も大きい。

**Comment by goutetsuguma** [comment]
```
・書籍での説明がように少ない手順でスライダーを設置したいけど、他のスライダーブロックは高機能で手順が多い
・VKスライダーの機能を軽量化したものを無料にするとかもあるけど、作業工数・管理が増える
```

わたしも無料版でよいかなとおもいました。
・スノーモンキーさんのスライダーも無料でつかえる。
・スライダー以外にもグリッドカードとかPro版には魅力的なブロックがある

**Comment by ChiakiKouno** [comment]
これからコアになる有料版の価値がパターンライブラリに移っていくことを考えると、スライダーは確かに無料版でも良さそうに思いました。

**Comment by kurudrive** [comment]
@doshimaf これよろしくお願いいたします (￣人￣)
