### ISSUE TITLE
カスタム ブロックスタイル設定機能

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1495]
カスタム ブロックスタイル機能を作ったほうが良いのではないか
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-styles/

このissuesで書きましたが一部のブロックで様々なカスタムCSSを持つパターンを作ると思います。
https://github.com/vektor-inc/vk-blocks-pro/issues/1494

配布されたユーザーとしてはそのパターンはサイト内で複数箇所使用する場合があると思います。そう言う場合はプリセットとして持っておきたい時があると思います。
なのでVK Blocksの方ではカスタムブロックスタイル機能が必要かなと思っていますがどうでしょうか？

**Comment by shimotmk** [comment]
これ作る感じで大丈夫ですか？
「良さそう」とかだけでもコメントいただければと思います

**Comment by goutetsuguma** [comment]
呼び出せるの便利で良さそう！使いたいです！

**Comment by kurudrive** [comment]
@shimotmk 非常に便利だと思います。優先度高めでお願いしたいです。

**Comment by shimotmk** [comment]
プロトタイプはできています。
ただ #1488 #1498 これらがマージされてからになります

**Comment by shimotmk** [comment]
@goutetsuguma
お疲れ様です。
カスタムブロックスタイルの設定画面のデザインをお願いしたいです🙏

ブランチ
#1507

CSSやクラス名は自分が適当につけたので付け直していただいても構わないですし、FigmaとかでUI作って再現できそうか確認いただいても構わないです。
そのほかユーザーとして欲しい機能などあれば遠慮なく言ってください

よろしくお願いします🙇‍♂️

**Comment by shimotmk** [comment]
オプション周りの実装でブランチを行き来していると存在しないオプションがDBに残ったりするためPHPのエラーが出る可能性がありますその際は
vk-blocks.phpなどに以下のコードを貼ってVK Blocksを有効化and無効化してDBを削除してください
```PHP

if ( function_exists( 'register_deactivation_hook' ) ) {
	register_deactivation_hook( __FILE__, 'vk_blocks_uninstall_function' );
}
function vk_blocks_uninstall_function() {
	delete_option( 'vk_blocks_options' );
	delete_option( 'vk_blocks_balloon_meta' );
}
```

**Comment by kurudrive** [comment]
@shimotmk 

一応僕の add/custom_block_style の環境ではでませんでした。
vk_blocks_options 消しても出ませんでした。

ただ、foreach ( (array) $args as $key => $value ) { 
の $args が bool(false) で落ちてくる事はあるみたいなので、
 (array) $args で配列にはしてるけど、 $args が配列じゃない空だったらストレートに $default 返すとかそういう話かな。

意図した事と違ったらスルーでかまいません（＝ｗ＝；

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます！
vk_blocks_array_mergeはオプション値とデフォルトのオプション値をマージする関数で、DBから貰ってきた(get_option())で取得した値が空の時はfalseを返すみたいですね
https://github.com/WordPress/wordpress-develop/blob/905bc9651f1a34b75c4f9ca18de66afdb135cc9f/src/wp-includes/option.php#L72-L78

なので @kurudrive さんの通り 空の際はループを回さずにデフォルト値が返ってきた方が良いので早期リターンにしたいと思います

**Comment by goutetsuguma** [comment]
@shimotmk さんおつかれさまです。以下の箇所は、調整可能でしょうか？難しいようであればなくてOKです！

### 【質問01】
codeタグがあった方がコピーする場所がわかりやすいので、追加できたら良いなと思いました。なくてもOKですmm 

<img width="944" alt="01" src="https://user-images.githubusercontent.com/5525368/207484780-07401042-a823-4354-8d55-83e7dca53cb0.png">

---

### 【質問02】
横並びに調整したくて、`<div>`で囲われていたらCSS調整しやすそうでしたので聞いてみました。難しそうであれば、なくてもOKですmm 

<img width="1046" alt="スクリーンショット 2022-12-14 10 33 36" src="https://user-images.githubusercontent.com/5525368/207484858-95b0a9cb-d2f6-4d97-af00-9af3643b3d14.png">

**Comment by shimotmk** [comment]
@goutetsuguma 
調整ありがとうございます！
【質問01】
codeタグで囲っておきました。下の文章もcodeにしました
![block-style](https://user-images.githubusercontent.com/42362903/207491458-2322bfdd-7d68-4c42-93ab-878e2e427bca.png)

【質問02】
divで囲っておきました！

**Comment by goutetsuguma** [comment]
@shimotmk 
CC @kurudrive @doshimaf 

おつかれさまです！いろいろ使ってみました、めっちゃ使いやすいです！！

【機能追加の案です】
管理画面用のCSSも書けると便利だなと思いましたが、なくても全然使いやすいです！
下のissueもたっていたので、案として出しました。みなさんにお聞きしてもいいかもですね
https://github.com/vektor-inc/vk-blocks-pro/issues/1508

----

以下、質問です。

【01】インナーのカラムが「テキスト」エリアに入っていましたが「デザイン」に入るのが正しいのでしょうか？親のカラムは「デザイン」に入っていたので、聞いてみました。
<img width="624" alt="スクリーンショット 2022-12-14 14 59 49" src="https://user-images.githubusercontent.com/5525368/207518853-226519ec-704b-44bd-b5f0-d1aa68c1b02f.png">

よろしくお願いします

**Comment by shimotmk** [comment]
@goutetsuguma 
ありがとうございます！

管理画面用のCSSは迷いますね。私としては管理画面用に書いたつもりのCSSがコアのアップデートなどによりかえって分かりにくくなる可能性もありえるなと思ったり迷っています。

> 【01】インナーのカラムが「テキスト」エリアに入っていましたが「デザイン」に入るのが正しいのでしょうか？

これそうですよね。コアの方には報告済みなのでいつか変わるかもです。
このブロック一覧のカテゴリーなどは手動で設定しているわけではなくコアの設定通りなのでVK Blocks側では設定できない(しない方が良い)箇所かなと思います。

---

CSSの調整は一旦以上ですか？？？

少し相談したいのですが、いくつかブロックスタイルを追加すると結構場所をとってしまう感じがあってどうにか出来ないかと迷っています。(これは別に @goutetsuguma 以外の人のアイディアも待っています。 )

<details>
<summary>管理画面画像(クリックで表示)</summary>

![admin](https://user-images.githubusercontent.com/42362903/207527106-cb3d2a5c-4eab-4bf3-9d53-77b5d080471f.png)
</details>

**Comment by goutetsuguma** [comment]
@shimotmk  @kurudrive @doshimaf @mthaichi @sysbird 
折りたためるの良いですね！あと、ブロックスタイルのそれぞれの順番が入れ替えれるとうれしいかもと思いました。
たくさん作っていると順番を変えたくなる気がしました。
みなさんはいかがでしょうか？
![editor-vk-blocks](https://user-images.githubusercontent.com/5525368/207532076-21868dd0-b055-49b4-9fb9-2c720d3bfa6d.png)

**Comment by shimotmk** [comment]
@goutetsuguma 
ありがとうございます！多分クラシックウィジェットみたいな感じですよね。
少し調整してみます！

**Comment by kurudrive** [comment]
@shimotmk @goutetsuguma 
動作確認しました！
なるほど、たしかに数が多いとめっちゃ場所とりますね。
折りたたみ＆順番切り替えで良いと思います👍

@goutetsuguma @sysbird @shimotmk 

* 新規追加でブロックを選ぶラジオボタンの所ですが、アイコンがガタガタになるので、コア＆書式設定を踏襲して下線+アイコン右のほうが良いかなと思うのですがどうでしょう？
* 折りたたみになるドラッグできる部分についても、畳んで並んだときに、文字数によってアイコンの位置がガタガタにならないように下村さんが実装後に調整よろしくお願いいたします。

**Comment by goutetsuguma** [comment]
@kurudrive @shimotmk 
たしかにガタガタでした、、下線 + アイコン右に調整いたしましたmm
下村さんが実装後に、ドラッグできる部分のデザイン調整など着手しますmm

**Comment by shimotmk** [comment]
お疲れ様です。カスタムブロックスタイル設定機能を調整しました。

本番リリース前に使ってみた感想や欲しい機能などあったらご意見いただきたいです🙏
お手隙の際で構わないのでよろしくお願いします🙇‍♂️

ブランチ #1507
現時点でのzipプラグイン
[vk-blocks-pro.zip](https://github.com/vektor-inc/vk-blocks-pro/files/10349233/vk-blocks-pro.zip)

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます！全体的に非常にすばらしい仕上がりだと思います！

機能面で下記だけ気になりました。
テキストエリアの上でドラッグを離すと文字が入ってしまうので、これ制限って出来たりしますか？

![スクリーンショット 2023-01-05 14 48 48](https://user-images.githubusercontent.com/3272660/210711393-39bddc80-cf0b-4209-a828-e502a7301339.png)

@goutetsuguma @shimotmk 

あとはデザイン的な細かい所ですが下記気になった点です。

![スクリーンショット 2023-01-05 14 44 34](https://user-images.githubusercontent.com/3272660/210711763-69a4c656-995a-4246-8ed0-6741d3966ab5.png)

![スクリーンショット 2023-01-05 14 30 58](https://user-images.githubusercontent.com/3272660/210711795-53aa11e5-5dbe-4915-b3b8-7594a10c7590.png)

↓ 畳んだ状態だとバランスが良いのでもったいないのですが、展開した状態だとバランスが悪いので、改善したいなと思いました。

![スクリーンショット 2023-01-05 14 25 19](https://user-images.githubusercontent.com/3272660/210711841-e265d142-3de1-4370-8d1c-36cb157e239a.png)

**Comment by shimotmk** [comment]
@kurudrive 
> テキストエリアの上でドラッグを離すと文字が入ってしまうので、これ制限って出来たりしますか？

これは制限できないと思います。
気になったということなので、ドラッグ&ドロップは無い方が良いかと思います

**Comment by kurudrive** [comment]
@shimotmk 

> ドラッグ&ドロップは無い方が良いかと思います

そうですね...あった方が便利だと思う反面
意図せずうっかり入ってしまう事があると思うので、実際はもっとCSSが多い事を考えると、
残念ですがドラッグ＆ドロップはなし...

あ、展開してない時だけ...、あ...ドラッグされる側が展開してたりすると一緒か...

はい、無しでいきましょう。

**Comment by shimotmk** [comment]
@kurudrive 
ドラッグ&ドロップは削除しておきました。

デザイン的な細かい所は多分自分が行うとあれだと思うので @goutetsuguma お願いしても良いでしょうか？

**Comment by kurudrive** [comment]
@shimotmk はい、デザインは @goutetsuguma さんが主担当領域ですので大丈夫です。
@goutetsuguma さんよろしくお願いいたします。

**Comment by goutetsuguma** [comment]
@kurudrive @shimotmk 
css調整いたしましたのでお手隙の時にご確認お願いいたしますmm

**Comment by kurudrive** [comment]
@goutetsuguma 確認しましたー！
ありがとうございますー。ばっちりです！
