### ISSUE TITLE
ライセンス期限切れの時のアラート、新製品リンクへ

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#1496]
G3 Pro Pack 販売終了& Vektor Passport 販売開始になりましたので、下記の箇所の文言とリンクの調整をお願いいたします。
G3 Pro Pack の商品ページにはすでに誘導の文言とリンクが設定してありますので急がなくて大丈夫という認識です。

## 現状
テキスト：Lightning G3 Pro Pack
リンク先：https://vws.vektor-inc.co.jp/product/lightning-g3-pro-pack/?rel=vk-blocks-pro-alert

## 変更後（案、石川さんに確認）
テキスト：Vektor Passport (旧Lightning G3 Pro Pack)
リンク先：https://vws.vektor-inc.co.jp/product/vektor-passport-1y?rel=vk-blocks-pro-alert

![VK Blocks](https://user-images.githubusercontent.com/43702482/203244812-ef1ef030-3efa-44f5-ae57-e4aa13de750e.png)

**Comment by mtdkei** [comment]
対応されているみたいなのでCloseします
