### ISSUE TITLE
WP6.0以前に作成したリストブロック(アイコン付き)が 6.1ではアイコンがなくなってしまう

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1497]
パターンのコピペ確認をしてて気づきました
下記のパターン(2022/1月作成)を、WP6.1 の投稿画面にコピペすると、アイコンがない状態になってしまいます
https://patterns.vektor-inc.co.jp/vk-patterns/dental-clinic_request/

上記パターンはパターンライブラリのフロントではアイコンが表示されてますが、編集画面ではスタイルが標準となりアイコンがない状態です

パターンに限らないようです
6.0 で作成したリストブロック(スタイルが標準以外のアイコン付き)が、6.1 ではスタイルが標準になります。
6.1 でスタイルを選び直すことはできます。

コメント欄にスクリーンキャプチャとコードを貼ります

**Comment by sysbird** [comment]
WP6.0 で作成したリストアイコン
スタイル → 矢印

![list-block](https://user-images.githubusercontent.com/4631838/203262017-e3061921-ac75-4c26-9b77-1e34379705fb.jpg)

コード
```
<!-- wp:list {"className":"is-style-vk-arrow-mark"} -->
<ul class="is-style-vk-arrow-mark"><li>りんご</li><li>みかん</li><li>ばなな</li></ul>
<!-- /wp:list -->
```

WP6.1 で編集しようとすると、`{"className":"is-style-vk-arrow-mark"}`  が消えてしまう

**Comment by shimotmk** [comment]
やはりGutenbergのバグだったようで、ちょうどryoさんがプルリク出してくれていました
https://twitter.com/ddryo_loos/status/1595303770115969024
https://users.swell-theme.com/forum/swell-bugs/%E3%83%AA%E3%82%B9%E3%83%88%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%8C%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%95%E3%82%8C%E3%81%9F%EF%BC%9F/

**Comment by mtdkei** [comment]
解決したような感じなので閉じます。
