### ISSUE TITLE
吹き出し画像設定のオプションを改善する

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1506]
吹き出し画像設定のオプションを改善する
https://www.vektor-inc.co.jp/product-update/vk-blocks-0-37-0-balloon/

・なぜか別オプションになっているvk_blocks_balloon_metaのデータをvk_blocks_optionsにマイグレーション
・任意の数登録できるようにする
・上記の理由によりUIの改善
・ブロックエディターでAPI取得している方法を修正

これが出来ればカスタムストア周りもスッキリするので修正しようと思います。
#1379
いや、やめたほうが良いなどあれば止めてください

**Comment by kurudrive** [comment]
いつも自主的にissue立てて処理してくれてありがとうございます！
あくまで肌感レベルなのですが、

* カスタムストア回りをスマートにするために修正したい
 → 了解です。進めちゃってください！

* 吹き出しブロックの表面側の

> ・任意の数登録できるようにする
> ・上記の理由によりUIの改善

→ 僕の中ではユーザーが頻繁に触る部分ではないので作業優先度は低くていいかなと思ってます。
他に優先する作業があってこの作業を分離できるなら後日実装でもいいのかなと思いました。
分離できない or 分離は面倒だから一緒にやりたい or 特に他に優先タスクがない というような感じでしたらそのまま一緒にすすめてください。

よろしくお願いいたします！

**Comment by shimotmk** [comment]
closed this as completed in #1559
