### ISSUE TITLE
[ カスタムCSS機能 ] 管理画面用CSS入力欄があった方が良いのではと思いますがいかがでしょう？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1508]
カスタムCSSが多用されるようになると、

* プレミアムパターンを編集画面にはりつけたら表示が全然違うというケースが増えてくる
* 管理画面用のCSSを今の場所に書くとフロントにも表示されてしまう
* カスタムHTMLブロックにカスタムCSSブロックを書いても編集画面で反映されない＆美しくない

という事で、各ブロックに現状のCSS入力欄とは別にもうひとつCSS入力欄があって、そこに入力した内容は管理画面でのみ出力されるみたいにできたらいいかなと思ったのですがみなさん如何でしょう？

**Comment by kurudrive** [comment]
@goutetsuguma @sysbird @shimotmk @mthaichi @doshimaf @kaorock72 @ChiakiKouno 

急ぎではないです。案です。

**Comment by goutetsuguma** [comment]
クライアントワークの人は、管理画面も同じように見えてほしいかもですね、、
今後、管理画面も同様の見た目に直したいという方が増えてくる気がしますので、あったらうれしいです。

**Comment by doshimaf** [comment]
たしかに、管理画面もフロントと同じように見えるのが理想だと思うので、あると便利だと思います。
ただ、CSS入力欄が2箇所になると「管理画面のCSSを編集していたつもりがフロント側に出力される方を編集していた」みたいなことも出てきてしまうのではないかと思いました。
また、ブロック自体の構造が変わるようなアップデートの影響も大きくなるのではないかとも思いました。
なので、あると便利だと思いつつ、その機能があっても管理画面上で表示が異なるのは許容するような気がします。
