### ISSUE TITLE
VK Blocks に古くからあるカスタムスタイルを非表示にできるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1519]
グループブロックのカスタムスタイルはすでに標準機能で出来るようになってしまったので、無効化できるようにしたいと思いますがどうでしょう？

**Comment by shimotmk** [comment]
たぶんグループブロックは @mthaichi さんが #1056 で作業中な気がします

**Comment by kurudrive** [comment]
#1056 と同じなのでclose
