### ISSUE TITLE
［ちょっとした相談］レスポンシブスペーサーブロックを配置した時に余白タイプがheightになっていると嬉しいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1531]
今は余白タイプが始めはmargin-topになっているけど、marginが相殺される場合や、グループブロックの中に（背景色あり・paddingは0）レスポンシブスペーサーをmargin-topで入れた場合に余白が外についてしまったので、最初から余白タイプがheightだと、変える手間がないのでうれしいかもしれない。

もし難しい場合、必要なさそうな場合はCloseしてください

**Comment by kurudrive** [comment]
@goutetsuguma 解説しましょう。相殺されて広い方になるように意図的に margin-top にしています（・ｗ・；

**Comment by goutetsuguma** [comment]
> 殺されて広い方になるように意図的に margin-top 

なるほど！承知しました！返事ありがとうございます、Closeしますmm
