### ISSUE TITLE
[X-T9 編集画面] リストブロックに上下どちらでも「ブロックの余白」を適用するとスタイルがつかなくなる

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#1532]
試した環境
WP 6.1.1
X-T9 1.3.4
VK Blocks Pro 1.48.0.1

リストブロックの親に上下どちらでも「ブロックの余白」を付けると、編集画面でスタイルが何も当たっていないような状態になりました。フロント画面は問題なく表示されていました。
また、リスト項目の方は編集画面でも問題ありませんでした。
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43702482/210059414-3ae5b6b1-3441-4fc7-8c14-f5b4fb56f429.gif)

**Comment by mtdkei** [comment]
本件確認してみました。現在はリストブロックに上下どちらでも「ブロックの余白」を適用するとスタイルがつかなくなる 現象は無くなったようなので一旦Closeにいたします。
