### ISSUE TITLE
【お知らせ記事待ち】設定のインポート・エクスポートができるようにしたい 

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1539]
カスタム書式やカスタムブロックスタイル・ブロックマネージャーなどの便利な設定が増えてきたのですが、細々設定したものを他のサイトでも使いたいという場合、手動で設定しなければなりませんよね？  

吹き出しブロック設定は画像があるのでちょっとむずかしいですかねー（画像をBase64でエンコードするとか？）

カスタム書式やカスタムブロックスタイル・ブロックマネージャーの設定だけでもインポート・エクスポートできたらいいなと思いますし、「カスタムブロックスタイルだけエクスポートする」みたいな選択ができたらなお良いと思いますが、いかがでしょうか。

**Comment by kurudrive** [comment]
@mthaichi いいですね！
吹き出しは除外で良いのではないでしょうか？
サイトによって登場人物はかわると思いますし。

**Comment by kurudrive** [comment]
これは json でエクスポート、インポートが妥当ですかねぇ。

* エクスポートボタン
* ファイル選択ボタン（インポート用）
* インポートボタン

を追加するみたいなのを想定しました。
そのほか高度な機能ってなくていいですよね？

ただ、そもそも、その前段階としてまだ option 値の処理のリファクタリングの途中ですよね？

そうなると 6.2 対応の後ぐらいでだから優先度はまだ低い感じかな？

@mthaichi @shimotmk @drill-lancer @doshimaf 
何かご意見・提案などありましたら募集中ですー。

**Comment by mthaichi** [comment]
> これは json でエクスポート、インポートが妥当ですかねぇ。
> 
> * エクスポートボタン
> * ファイル選択ボタン（インポート用）
> * インポートボタン
> 
> を追加するみたいなのを想定しました。 そのほか高度な機能ってなくていいですよね？
> 
> ただ、そもそも、その前段階としてまだ option 値の処理のリファクタリングの途中ですよね？
> 
> そうなると option 値の扱いのリファクタリングと 6.2 対応の後になると思うから優先度はまだ低い感じかなと思いました。
> 
> @mthaichi @shimotmk @drill-lancer @doshimaf 何かご意見・提案などありましたら募集中ですー。

自分は、ACFのインポート・エクスポート機能の感じをイメージしていました。
エクスポートでどの項目をエクスポートするか選べるといいなと。「カスタム書式」「カスタムブロックスタイル」「ブロックマネージャー」のチェックボックスがあり、「エクスポート」押下でダウンロード。
インポートはファイルを選んで「インポート」を押すだけ。

↓ACFのインポート・エクスポート画面
![image](https://user-images.githubusercontent.com/1535140/214512419-68a583c0-78e1-40d2-b171-9443309750ca.png)

**Comment by shimotmk** [comment]
@mthaichi 
これトライしてみても良いですか？

**Comment by mthaichi** [comment]
> @mthaichi これトライしてみても良いですか？

@shimotmk もちろんです。ありがとうございます。m(__)m

**Comment by shimotmk** [comment]
この機能を作ってみました。 
#1667

エクスポートする項目とインポートする項目を選べるようにしました。
吹き出しブロック、カスタム書式設定、カスタムブロックスタイル設定はインポート方法も追加しました。

仕様などご意見ある方いただければと思います。

**Comment by shimotmk** [comment]
@mthaichi 
ありがとうございます。

> エクスポート時は、現在の画面の「入力値」がJSONに反映されているようですが、「保存値」をエクスポートしたほうがいいと思います。

これは自分も結構迷ったのですが、保存値の方が良さそうですよね。
保存値と入力値が異なっていたらエクスポートは出来ないようなどにした方が良さそうですね。

> また、インポート＆エクスポートは「変更を保存」ボタンより下にあるので、設定フォームとはまったく別の枠組みという捉え方をします。設定フォームの内容によって、JSON化される内容が設定フォームの入力値に左右されないほうがよいかと思いましたが、いかがでしょう

これもエクスポート時のJSON化の話ですか？
設定フォームの内容 ＝ 入力値 という意味ですか？

**Comment by mthaichi** [comment]
> これもエクスポート時のJSON化の話ですか？
> 設定フォームの内容 ＝ 入力値 という意味ですか？

そうです。インポート＆エクスポートのエリアは、VK Blocksの各種設定フォーム（＝入力値）の外側にある形なので、設定フォームの内容でJSONの内容が左右されるのはよろしくないのかなと感じました。

**Comment by mthaichi** [comment]
> これは自分も結構迷ったのですが、保存値の方が良さそうですよね。
> 保存値と入力値が異なっていたらエクスポートは出来ないようなどにした方が良さそうですね。

それでもいいと思いますし、「変更した設定が保存されていないようです。変更前の設定内容をエクスポートします」とお断りした上で、エクスポートしちゃっても良いかなと思います。

**Comment by shimotmk** [comment]
@mthaichi 
ありがとうございます。
保存値と入力値が異なっていたらエクスポートは出来ないようは難しかったので、「変更した設定が保存されていないようです。変更前の設定内容をエクスポートします」とお断りを追加しておきました！#1667

**Comment by shimotmk** [comment]
特に何もなさそうなのでそのままプルリクにします〜

**Comment by kaorock72** [comment]
@kurudrive お知らせ公開いたしました！
https://www.vektor-inc.co.jp/product-update/vk-blocks-1-58-0-import-export/
