### ISSUE TITLE
FSE対応テーマで分割読み込みを有効にするとコアのブロックを拡張しているスタイルがフロントで効かない

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1546]
FSE対応テーマ(X-T9/TT3)で分割読み込みを有効にすると、コアブロックの拡張スタイル（見出しや画像のスタイル）がフロントで効いていないです。

既知の問題でしたら、すみません。

**Comment by shimotmk** [comment]
以前ここで #1319 出てました😅
コアのバグっぽいです

**Comment by mthaichi** [comment]
> @mthaichi 以前ここで #1319 出てました😅 コアのバグっぽいです

@shimotmk ありがとうございます。Issue検索したんですが、見つけられず、とりあえず書いておきました。クローズしておきますね。
