### ISSUE TITLE
【VK Blocks側で直せるのか相談】「インライン文字サイズ」で文字サイズを再度調整しようとするとウィンドウが左上に隠れてしまう件

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1548]
私の方でも再現できたのですが、VK Blocks側の問題なのかがわかりませんでした、、、
一度治せるのかどうかの相談になります。

▼Chiakiさんのコメント（この手順で再現できました）
https://discord.com/channels/1010092469863587892/1010099807777468456/1065482978018459649

https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/extensions/common/inline-font-size/index.js

▼報告のあったフォーラム
https://vws.vektor-inc.co.jp/forums/topic/%e3%80%8c%e3%82%a4%e3%83%b3%e3%83%a9%e3%82%a4%e3%83%b3%e6%96%87%e5%ad%97%e3%82%b5%e3%82%a4%e3%82%ba%e3%80%8d%e3%82%92%e6%8c%87%e5%ae%9a%e3%81%99%e3%82%8b%e3%81%a8%e8%a8%ad%e5%ae%9a%e7%94%bb%e9%9d%a2

**Comment by goutetsuguma** [comment]
しもむらさんありがとうございます！developでなおっていました！！

**Comment by goutetsuguma** [comment]
developでなおっていたのでCloseします　ご確認ありがとうございました🙇‍♂️

**Comment by kurudrive** [comment]
@shimotmk 確認ありがとうございます！
@goutetsuguma VK Blocks は今日〜明日に一旦リリース予定です。
