### ISSUE TITLE
[Katawara フロント画面] ステップの見出しが中央寄せになって点線の下線が短くなってしまう

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/vk-blocks-pro#1550]
試した環境

Katawara1.18.6
VK Blocks Pro1.49.0

Katawaraデモサイト
https://demo.dev3.biz/katawara/sample-design/vk-blocks-pro-sample/

※vektor-incのサイトも同じ環境です

- 編集画面での表示は問題ないです。
- VK Blocks Pro1.48.1.0にダウングレードすれば表示に問題ないことを確認しました。

Lightning15.5.0
VK Blocks Pro1.49.0の組み合わせでは問題ありませんでした。

---

### VK Blocks Pro1.49.0
<img width="600" alt="vk-blocks-pro-1-49-0-step-01" src="https://user-images.githubusercontent.com/59037734/214192110-ea603ac9-81e5-4abf-8b4b-0878f3c3ee7b.png">
  
<img width="600" alt="vk-blocks-pro-1-49-0-step-02" src="https://user-images.githubusercontent.com/59037734/214192188-b8a09609-4f36-4c90-802f-37266740cef1.png">

`.vk_step .vk_step_item_content {
    /* display: grid; */
}
`
を外すと見出しの表示は直るようですが、タイムラインの線に隙間ができてしまうようです。

<img width="600" alt="vk-blocks-pro-1-49-0-step-03" src="https://user-images.githubusercontent.com/59037734/214194147-a8872b78-eff9-4335-bc39-2587ec537133.png">

### VK Blocks Pro1.48.1
<img width="600" alt="vk-blocks-pro-1-48-1-step-01" src="https://user-images.githubusercontent.com/59037734/214192216-8479f5d2-f760-44b7-91a0-71ca1337d346.png">

**Comment by goutetsuguma** [comment]
おそらく「Lightningデザイン設定」&「Katawaraデザイン設定」のh4の見出しデザインによって、中央に寄ってしまうようです。

resetのcssで
```
margin-left: auto;
margin-right: auto;
```

と書いてあるので中央に寄ってしまうようでした。
ここをunsetにするとOKな気がしましたが、2年前のコメントアウトで

> margin:unset; にすると編集画面で左ベタ付きになるので注意

と書いてあるので、編集画面で問題なければunsetにした方が良いかもしれません。

**Comment by goutetsuguma** [comment]
リリース済みなのでCloseしますmm
