### ISSUE TITLE
【メモです】カスタムブロックスタイル設定で特に見出しなどは selector::before(after)で編集画面に反映されないかもしれない（フロントはOK）読み込み順の問題っぽいので注釈など追加する？

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1555]
勉強会でのご意見で、おそらく見出しなどはデザイン設定のcssが強すぎてimportantが必要だったりするのかな？（まだ詳しく確認していないので確認するところから）

> カスタムブロックスタイル設定で selector::before(after) の指定ができるともっとうれしいです。

**Comment by kurudrive** [comment]
@shimotmk 

カスタムブロックスタイルが普通にセレクタ一つだけだと編集画面で高確率で他のCSSにまけて反映されないので、
編集画面の時は .editor-style-wrapper .selector {  } みたいに出力するようにできればした方が良いのではないかなと思うけどどうでしょう？

↓実際の症状例
https://www.youtube.com/watch?v=qRgMt16_-bA

技術的にハードル高い？

**Comment by shimotmk** [comment]
> ↓実際の症状例
https://www.youtube.com/watch?v=qRgMt16_-bA

多分Lightning G3 Pro Unitの見出しデザインの影響だと思います
https://github.com/vektor-inc/lightning-g3-pro-unit/blob/master/inc/headding-design/package/class-vk-headding-design.php

> 編集画面の時は .editor-style-wrapper .selector { } みたいに出力する

これは多分`selector`の文字列を `.editor-style-wrapper .is-style-クラス名` に変更すれば出来そうですが、それをすることによって何か不具合が出ないかわかりません
(例えばエディタではスタイルがあたるがフロントで効かないなど)

CSSの詳細度などはユーザーが適宜考える領域にした方が自然だろうと思ったので詳細度などをいじることはしませんでした

**Comment by shimotmk** [comment]
すみません🙏
こちらWP 6.2 サイトエディタで使えるコアのグローバルスタイルで.editor-style-wrapperをラップする方法があったので実装しようと思います

**Comment by shimotmk** [comment]
#1578 #1584 で対応したのでcloseします
