### ISSUE TITLE
［グリッドカラムカードアイテム］編集ロックの表示が崩れている

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-blocks-pro#1565]
グリッドカラムカードのグリッドカラムカードアイテムで、編集ロックのトグルボタンとテキストが被った表示となっていました。
ToggleControlコンポーネントにあたっているスタイルが影響しているような感じで、コアの問題でしょうか？
英語・日本語とも同じように崩れており、テキスト部分が長くなると崩れるようです。

<img width="317" alt="スクリーンショット 2023-02-02 9 57 43" src="https://user-images.githubusercontent.com/73574599/216204790-0bbd9be8-2f07-4466-8e66-7e3375e73eee.png">

**Comment by shimotmk** [comment]
コアのバグにありました！
https://github.com/WordPress/gutenberg/issues/45381
https://github.com/WordPress/gutenberg/pull/45962
たぶん6.2でなおると思います

**Comment by doshimaf** [comment]
@shimotmk 
ありがとうございます！

**Comment by kurudrive** [comment]
6.2 で修正されてる事を確認したので close
