### ISSUE TITLE
【確認待ち】[スライド設定] → [表示時間] を 0 に設定できない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1568]
[スライド設定] → [表示時間] を 0 に設定できないようでした。（1には設定できますので、そこまで表示上に問題はありません。）
修正できるかどうかの相談になります。

▼ご報告
https://vws.vektor-inc.co.jp/forums/topic/vk-blocks-%e3%82%92-1-50-0-1-%e3%81%ab%e3%82%a2%e3%83%83%e3%83%97%e3%83%87%e3%83%bc%e3%83%88%e3%81%99%e3%82%8b%e3%81%a8%e3%80%81%e3%82%b9%e3%83%a9%e3%82%a4%e3%83%80%e3%83%bc%e3%81%ae%e8%a1%a8%e7%a4%ba

**Comment by sysbird** [comment]
マージされたので閉じまする
