### ISSUE TITLE
吹き出しブロックの画像が切れることがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1571]
吹き出し(別件)の確認中で気が付きました
たぶん画像が正方形でない場合は、はみ出た箇所が表示されないようです

1. 吹き出しの設定画面では正円表示なので、切れることはわかる
2.  投稿の編集画面では切れない
3. フロントでは切れる

表示を統一して、つじつまがあっていればよいと思います

編集画面
![Balloon-1](https://user-images.githubusercontent.com/4631838/216901889-56ad6583-68f2-44f4-b655-936ff7066e81.jpg)

フロント
![Balloon-2](https://user-images.githubusercontent.com/4631838/216901881-fe4b5727-3bcf-4e37-85db-94b4fddef082.jpg)

**Comment by mtdkei** [comment]
MargeされたのでCloseします
