### ISSUE TITLE
【確認待ち】［Outer］ブロックを全幅にした時に、「alignfull」のクラス名が付与されるとうれしいです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1572]
Lightningでカスタマイズ→Lightning 機能設定→theme.json を有効にした場合、
全幅サイズのグループブロックの中に全幅サイズのOuterブロックを入れると、Outerブロックにはalignfull のクラス名がつかないので、全幅にならずに幅が小さくなってしまいます。　

▼以下のCSSがつくため

```
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)){
max-width:var(--wp--style--global--content-size);
margin-left:auto !important;
margin-right:auto !important;
}

```

スライダーブロックは全幅にするとalignfullがつくようでしたので問題なさそうでした。パターンをつくっていて、全幅グループブロックの中に全幅Outerをいれることもあるため、Outerにもalignfullがつくとうれしいです

現状は、手動で追加 CSS クラスのところにalignfullをいれています。

Assigneesには、いったん開発メンバーの方々を入れさせていただきました。
ご検討よろしくお願いいたしますmm

**Comment by kurudrive** [comment]
@shimotmk @mthaichi @drill-lancer @sysbird @doshimaf @goutetsuguma 

これはコアにあわせて alignfull を入れる方向で良いよね？
そうすれば Outer ブロック用の全幅指定のCSSも減らせるし。

やる方向で優先度 中 にしておくけど、
反対意見や「いやいや、ちょっとミーティングで相談しましょう」という場合はお気軽にコメントくださいー。

**Comment by drill-lancer** [comment]
マージされたので Close
