### ISSUE TITLE
【確認待ち】［レスポンシブスペーサー］単位 vh ・svhが無いような気がするので追加で欲しい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1573]
vhの単位が無いようでした。コア側ののスペーサーでは選べるようでしたので、レスポンシブスペーサーにもvh単位が欲しいなと思いました。

Assigneesには、いったん開発のメンバーを入れさせていただきました。
ご検討よろしくお願いいたします。

【余談です】
svhの単位も気になっております、、
https://zenn.dev/moneyforward/articles/svh-dvh-lvh-for-all-browser

**Comment by sysbird** [comment]
たしかに、ほしいです！

**Comment by kurudrive** [comment]
あー、vh よりも svh が重要ですね。両方入れましょう！

**Comment by drill-lancer** [comment]
https://jajaaan.co.jp/web-production/frontend/css-vw-vh-vmin-vmax/
https://coliss.com/articles/build-websites/operation/css/large-small-dynamic-viewports.html

vmax とか vmin とか単位も色々ありますね。

**Comment by drill-lancer** [comment]
@goutetsuguma @sysbird @kurudrive 
lvh と dvh は不要ですか？
あと共通余白も必要ではないですか？

**Comment by kurudrive** [comment]
lvh と dvh も入れておいてください。
共通余白も設定必要っすー。

**Comment by sysbird** [comment]
マージしたので閉じまする
