### ISSUE TITLE
【お知らせ待ち】［機能追加要望］［スライダーブロック］前後の画像をチラッと見せる機能があると嬉しいというご意見

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1581]
▼VWS Slackよりご意見
https://vektor-vws.slack.com/archives/CJD95D5LZ/p1676891961357149

意見調整待ちになります。

メモです
・以前リックさんが一度に表示する枚数を小数点可能にした場合に、前後の画像を見せることができたけど、仕様がむずかしい？

---
Assigneesには開発のメンバーの方を入れさせていただきました

**Comment by kurudrive** [comment]
@kaorock72 こちらお知らせ記事...必要か？

**Comment by kaorock72** [comment]
@kurudrive お知らせ記事書きましょう！書きますーー

**Comment by kaorock72** [comment]
https://www.vektor-inc.co.jp/product-update/vk-blocks1-53-0-slides-per-view/
お知らせ記事公開とシェア完了しましたので、クローズいたします
