### ISSUE TITLE
グリッドカラムカードアイテムヘッダーに画像のキャプションが入ってしまうと消せなくなる

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1582]
グリッドカラムカードのグリッドカラムカードアイテムヘッダーに画像を設置した場合、画像のキャプション(figcaption)が自動的に入力される場合がある。
このキャプションは画像ファイルのメタ情報から持ってきてるので、WordPress の仕様と思います。
→このような画像はあまりないかもしれないですが、たぶん素材にはありがち？(私も入れることがあるので)

このような画像のとき、画像ブロックにキャプションがくっついて表示されます。
通常は編集画面で気がついて削除しますが、グリッドカラムカードアイテムヘッダーではキャプションを削除する手段がないようです。
別の画像に差し替えても、キャプションは初回のが残ります

**Comment by sysbird** [comment]
グリッドカラムカードアイテムヘッダーに画像のキャプションが入ってしまったとき(消せない)
![yoga](https://user-images.githubusercontent.com/4631838/220290797-5c04756e-3332-453c-b7a0-a30484c0463c.png)

キャプションを持っている画像のアップロード時
![image-title](https://user-images.githubusercontent.com/4631838/220290789-239e6954-1690-47c6-a025-74ad7bd77da9.png)

**Comment by kurudrive** [comment]
あー、うーむ、消せないと困りますよねぇ...

**Comment by kurudrive** [comment]
とりあえず今回はスルー。
また同じ症状で困る場面が出てきたら再度オープン
