### ISSUE TITLE
[ スライダーブロック ] 高さ指定の単位で % / vh / svh を追加して欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1585]

**Comment by drill-lancer** [comment]
@kurudrive 
すでに develop ブランチでは追加されていると思います。
https://github.com/vektor-inc/vk-blocks-pro/pull/1579

**Comment by kurudrive** [comment]
@drill-lancer あ、レスポンシブスペーサーだけじゃなかったのね。ありがとう！

**Comment by drill-lancer** [comment]
@kurudrive 

https://github.com/vektor-inc/vk-blocks-pro/pull/1579 の作用・副作用で
- レスポンシブスペーサーのカスタムで使える長さ（高さ）
- 共通余白
- カード（非推奨）の画像の高さ
- スライダーの（画像の）高さ

が実装済みで上記と関係がない

- Outer の「コンテナ内側のスペース設定」
- グリッドカラムの「カラム下部余白設定」
- グリッドカラムアイテムの「アイテム内の余白設定」
- （横並び）アイコンのサイズと余白

はまだ使えません。

**Comment by sysbird** [comment]
なお、スライダーブロック で動作確認済みですー
