### ISSUE TITLE
【機能追加要望】VKボタンブロック、横並びボタンブロックの内側のパディングと角丸が設定できるとうれしい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1587]
コア側のボタンブロックのように内側のパディングと角丸が設定できるとうれしいけど、複雑になるようでしたらVKパターンライブラリーでパターンで登録対応でもよいかなと思っていますがどうでしょうか。

---
Assigneesには、開発の皆さまをいったん入れさせていただきました。

**Comment by sysbird** [comment]
設定できたらうれしい！

**Comment by kurudrive** [comment]
まぁ必要ですよね（・ｗ・

**Comment by kurudrive** [comment]
- [ ] padding設定
- [ ] 角丸設定

**Comment by shimotmk** [comment]
この機能ですが、[ブロックサポート](https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-supports/)で実装するか独自のattributesを追加するか迷っています。

一旦仮で両方を有効化した状態のプルリクはこちらです。
https://github.com/vektor-inc/vk-blocks-pro/pull/1626/

コアと同じ機能のみで良いのであればブロックサポートの方が実装上は簡単ですがどっちが良いのでしょうかね。。

**Comment by mthaichi** [comment]
> この機能ですが、[ブロックサポート](https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-supports/)で実装するか独自のattributesを追加するか迷っています。
> 
> 一旦仮で両方を有効化した状態のプルリクはこちらです。 #1626
> 
> コアと同じ機能のみで良いのであればブロックサポートの方が実装上は簡単ですがどっちが良いのでしょうかね。。

@shimotmk ブロックサポートで実現できるのであれば、そちらを使った方が良いと私は単純におもってしまいしたが、@shimotmkさん的にどういうところで迷ってますか？ 

あと、6.2からインスペクタータブが導入されているので、独自実装するにしてもスタイル関係のものはスタイル側のタブにいれていったほうがいいのかなと思いましたが、どうなんでしょう。
