### ISSUE TITLE
develop ブランチ版の場合、記事編集画面だと空の <style></style> が出力される

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1593]
発生環境 6.2 Beta3 / X-T9 （←たぶん関係なく発生するのではないかと）

適当にブロック配置して、インスペクタで要素見ると、上に空の style タグが出力されます。

![スクリーンショット 2023-03-02 14 37 38](https://user-images.githubusercontent.com/3272660/222341156-f961f7be-4ecc-44c6-8e7e-7c2be5b7caf9.png)

![スクリーンショット 2023-03-02 14 46 50](https://user-images.githubusercontent.com/3272660/222342135-725c7ec5-b205-4e9f-8158-fccc3cd42239.png)

カスタムCSS機能の影響かな？
下村さんの環境でも発生するか確認よろしくお願いいたします。

これがあると CSS で nth-child 指定や h2 + p みたいな指定してある場合に挙動がおかしくなってしまうので出来れば直したいです。

お手数ですが一度確認よろしくお願いいたします (￣人￣)

**Comment by sysbird** [comment]
マージしたので閉じまする
