### ISSUE TITLE
【確認待ち】レスポンシブスペーサーでCSSを直接指定できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1595]
#### 現状の問題点

* minmax() 指定などができないのでテーマ側がそういった指定をしてると揃えられない
* CSS変数で指定できない

#### 改善要望

CSSを直接入力できるようにして、入力があったらその内容を最優先で出力するようにしたい。

![スクリーンショット 2023-03-06 12 09 24](https://user-images.githubusercontent.com/3272660/223012230-bebd3049-1407-4370-bda2-36121bac0b15.png)

```
CSS Customize
If you entered custom CSS, the values you entered are applied.
ex) var(--wp--custom--spacing--x-small);
```

現状例えば --vk-margin-lg とかに出力されているので、同様に 今回追加した カスタムCSS が入力されている場合は
--vk-margin-lg にその内容をあてるみたいな感じです。

**Comment by drill-lancer** [comment]
`--vk-margin-xl: 10px; ` の 10px の部分をテキストエリアに出力

**Comment by kurudrive** [comment]
おわったらこっち
https://github.com/vektor-inc/vk-blocks-pro/issues/1343

※ 別プルリクでよろ

**Comment by drill-lancer** [comment]
マージされたけどクローズされていないのでクローズ
