### ISSUE TITLE
コアのUIの 余白設定 / ボーダー設定が VK Blocks でも使えるようにコンポーネントごと内包できないか？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1596]

**Comment by drill-lancer** [comment]
余白は

https://github.com/WordPress/gutenberg/blob/wp/6.2/packages/block-editor/src/hooks/padding.js

SpacingSizesControl　は

```
import {
	__experimentalSpacingSizesControl as SpacingSizesControl,
} from '@wordpress/block-editor';
```
からの

https://github.com/WordPress/gutenberg/tree/wp/6.2/packages/block-editor/src/components/spacing-sizes-control

で実装可能だが棒線部分の扱いが謎すぎて Filter Search では断念

ボーダーは

https://github.com/WordPress/gutenberg/blob/wp/6.2/packages/block-editor/src/hooks/border.js

**Comment by drill-lancer** [comment]
https://github.com/WordPress/gutenberg/blob/wp/6.2/packages/block-editor/src/index.js
https://github.com/WordPress/gutenberg/blob/wp/6.2/packages/block-editor/src/hooks/index.js
https://github.com/WordPress/gutenberg/blob/wp/6.2/packages/block-editor/src/components/index.js

これらのファイルで エクスポートが指定してあるものは `@wordpress/block-editor` から読み取れそうです。

**Comment by shimotmk** [comment]
とりあえず余白設定は以下の様な形でコンポーネントごと持ってきて独自のattributesに保存は出来そうです。
https://github.com/vektor-inc/vk-blocks-pro/pull/1626/commits/3bfe3b9a90f681dfba550cdff266da684e3ae7c4
