### ISSUE TITLE
【機能追加要望】［Outer］区切りの設定で上部と下部の区切りの色の透過設定ができると嬉しいかもしれない。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1600]
背景設定の色設定では半透明に設定できるので、同じように上部と下部の区切りの色の透過設定ができると便利だなと思おうことがあります。
パターンを作っていて、主にキーカラーを半透明にしたいことがありました。

ご検討よろしくお願いいたしますmm
不要そうであればCloseしてください

![非公開-LP_求人_建築-VK-パターンライブラリ](https://user-images.githubusercontent.com/5525368/223661666-7b946811-cd86-487e-be9e-96eeb1e1fe94.png)

**Comment by shimotmk** [comment]
#1620 と同じでリリースされていたのでclose
