### ISSUE TITLE
[ グリッドカラムカード ]未翻訳あり

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1604]
カラムヘッダーメディアエリア のラベル Card header image aspect ratio を翻訳可能にしよう

**Comment by kurudrive** [comment]
翻訳ファイルだけなら develop ブランチでやってもらえればおｋ

**Comment by mtdkei** [comment]
Card header image aspect ratio は __() の国際化関数が使われておりませんので、まずはgrilcolcardのedit.jsで翻訳可能な状況にしていただいてから翻訳頂けたらと思います。

**Comment by mtdkei** [comment]
マージされていましたのでCloseします。ありがとうございました。
