### ISSUE TITLE
readme にオフィシャルリンクを追加するとよいかもしれない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1605]
下記へのリンク
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-blocks/

もしかしたら日本語ページしかないからリンクがないかもしれませんが、あったほうがよい気がします。

**Comment by kurudrive** [comment]
readme を見る人はエンジニアなので、まぁ一般向けの説明ページにはむしろ行ってほしくないかなと...ごにょごにょごにょ
