### ISSUE TITLE
font awesome のよく使うアイコンを自分で登録できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1607]
https://vws.vektor-inc.co.jp/forums/topic/add-icon-select

**Comment by shimotmk** [comment]
@vektor-inc/vektor-inc 
この機能を作ってみました。
ブランチ #1710

設定はvk_blocks_optionsに保存しています。


https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/04af4522-ce88-44d6-b25f-8c31f053cabb



順番や削除のボタンが小さすぎる感じはありますが、どうでしょうかね。
ご意見ある方いただければと思います。

**Comment by sysbird** [comment]
使ってみました、とても便利ですね！
操作も問題ないし、削除もできるのはさすがです

**Comment by ChiakiKouno** [comment]
下村さん、ありがとうございます！めっちゃいいですね！

１）追加後のアイコンリストを見た時に、どれが自分で登録したものかが一目でわかると良いなと思ったので「マイリスト」「プリセット」というように分かれていると良さそうに思いましたがいかがでしょうか

２） 「編集モード」を「削除・並び替えモード」とするのはどうでしょうか

３）編集モードがおっしゃる通り少し小さいと思いましたので、大きくできないか検討してみました：
 - A: 削除のX印とドラッグ&ドロップ
 - B: 削除のX印と左右の矢印
 - C: 今の下村さんの実装してくれてる状態で進める

素人目線なので「そんなん無理やで」みたいな提案になっていたらすみません🙏 
可能でしたら個人的希望は A>B>C となります

<img width="1376" alt="Screenshot 2023-06-27 at 6 06 53 PM" src="https://github.com/vektor-inc/vk-blocks-pro/assets/43702482/84e03f5b-01a5-401d-9ffe-5bad39a5bc20">

Figmaこちらです：
https://www.figma.com/file/wnfnRlhap7earuSN7ccTmH/Issue%E7%94%A8?type=design&node-id=501-2&mode=design

**Comment by shimotmk** [comment]
ありがとうございます！



> １）追加後のアイコンリストを見た時に、どれが自分で登録したものかが一目でわかると良いなと思ったので「マイリスト」「プリセット」というように分かれていると良さそうに思いましたがいかがでしょうか

そうですね！
一度それも考えたのですが、マイリストが5個以外の時3個とか6個の時に見た目が悪いかなと思ってやめたのですが、改めて見るとこちらの方が良さそうです！
自分で登録したものとそうでないものが一目でわかるのは良いと思いました

> ２） 「編集モード」を「削除・並び替えモード」とするのはどうでしょうか

良いと思います！

> ３）順番や削除のボタンがおっしゃる通り少し小さいと思いましたので、大きくできないか検討してみました：

> A: 削除のX印とドラッグ&ドロップ

以前カスタムブロックスタイルでドラッグ&ドロップを試したのですが、結構難しいかなと...
コアのコンポーネントがまだ今ひとつで中途半端なものになりそうです

> B: 削除のX印と左右の矢印
> C: 今の下村さんの実装してくれてる状態で進める

> 削除のX印

右上の方がわかりやすそうですね！

> 左右の矢印

矢印はコアと合わせて今の方がいいかなと...

> 選択表示中のアイコンを「マイリスト」として登録・編集が可能です。

 １）にすれば、マイリストに追加で大体予想がつく&気に入らなければすぐに戻せるのでこの文章はなくても良いかと思いました。
また、ポップオーバーで出てくる部分はブラウザ外に出ることが多いので出来るだけ内容は短くしたいと言う理由もあります。

と言うことで少し調整します〜

**Comment by shimotmk** [comment]
調整しました 

> 選択表示中のアイコンを「マイリスト」として登録・編集が可能です。

はマイリストが無い時は表示させました！


https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/8fcafe30-6610-4123-b50a-a0318773d5ce

**Comment by ChiakiKouno** [comment]
良い塩梅のところ見つけてくださり＆早速のご調整誠にありがとうございます！

そっかそっか、左右の矢印はコアに合わせなのですね！なるほど！無問題と思いました！

めっちゃいいですー！🙌 素早い〜すばらしー


> 選択表示中のアイコンを「マイリスト」として登録・編集が可能です。
> はマイリストが無い時は表示させました！

そそ、私もその方がスッキリするなと思ってました、ありがとうございます！

あ、そしてちょっとここで迷ってることがあり相談してみたかったのですが、

> 設定はvk_blocks_optionsに保存しています。

とあったので、きっとこの設定はユーザーごとではなくて、サイト全体で一括で適用されるということですよね。
自分で設定した人は非表示になっても分かると思うのですが、誰かが設定した後、別の人が見た時にも「選択表示中のアイコンを「マイリスト」として登録・編集が可能です。」が見えていた方が直感的に分かりやすかったりするかなと思うのですが…どうでしょうか。
（個人的には非表示にできるものはできるだけそうしたいところではあるのですが…）
私が受託制作で納品してる企業さんは大体2人以上で更新されており、頻度が高ければ毎年スタッフさんが入れ替わるケースもあったりします。

ううむ…もしかすると誤解が生まれにくいように「マイリスト」のネーミングを変えた方がいいかもしれないかな…「カスタムリスト」とかの方が『私が個人で登録したやつ感』が減りますかね…

**Comment by shimotmk** [comment]
> > 設定はvk_blocks_optionsに保存しています。
> 
> とあったので、きっとこの設定はユーザーごとではなくて、サイトの全ユーザーに一括で適用されるということですよね。 

そうですね。
やっぱりユーザーごとに保存の方が良さそうですかね？？

**Comment by kurudrive** [comment]
@shimotmk なかなかアグレッシブな実装ありがとうございます！

> やっぱりユーザーごとに保存の方が良さそうですかね？？

いや...さすがにユーザーごとは需要とメンテナンス性のバランスが割にあわないと思うなぁ。
「カスタムリスト」の表記で良いように思います。

@ChiakiKouno どうですかね？

**Comment by ChiakiKouno** [comment]
あ、石川さん、お呼び出ししようかと思っていました！
気になっていたことがクリアです、ありがとうございます！それで良いと思いますー！

**Comment by ChiakiKouno** [comment]
@shimotmk 

> ポップオーバーで出てくる部分はブラウザ外に出ることが多いので出来るだけ内容は短くしたい

ここは確かにそうですよね、なるべく省略できないか考えてみました。
ボタンの表記を「カスタムリストに追加する」から →「選択中アイコンをカスタムリストに追加」とすると、説明文が省けそうに思いましたが、どうでしょうか…。
ちょっと文字数多すぎで冗長かな…？フォントこんなに小さくできるかな？

<img width="551" alt="Screenshot 2023-06-29 at 2 20 24 PM" src="https://github.com/vektor-inc/vk-blocks-pro/assets/43702482/274c470b-ec55-4572-af06-d497f94fc7ff">

**Comment by shimotmk** [comment]
あれ？アイコンのタイトルにカスタムリストとプリセットは表示するような形になったので、カスタムリストが無い時だけ説明は表示させれば良いのでは無いですか？

ここの時のマイリストと同じ形です
https://github.com/vektor-inc/vk-blocks-pro/issues/1607#issuecomment-1611200707

**Comment by ChiakiKouno** [comment]
自分で設定した人は説明が非表示になっても分かると思うのですが、カスタムリスト設定後、別のユーザーが見た時には分からなくなるかなと思いましたので、「選択中アイコンをカスタムリストに追加」としておくと、説明文がなくても分かりやすくなるのではと思ったのですが、どうでしょうか。

私が気にしすぎかもしれませんので、下村さんの方で↑でしっくりきているようでしたら、スキップしてもらって構いません◎

**Comment by shimotmk** [comment]
すみません！勘違いしてました🙇‍♂️

確かに、「選択中アイコンをカスタムリストに追加」にすると説明文なしでいけそうですね！
そうしようと思います

**Comment by ChiakiKouno** [comment]
いえいえ、私がまとまりのない長文を書いてしまってたので、ややこしかったですよねmm
ご調整誠にありがとうございますー！

**Comment by shimotmk** [comment]
その他、特に何もなさそうなのでプルリクにします〜

**Comment by shimotmk** [comment]
リリース済みのためcloseします
