### ISSUE TITLE
【リリース待ち】【機能追加要望】［アニメーション］グループみたいに「アニメーション解除」とかできると嬉しい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1608]
**欲しいと思った理由**
パターンを作っていて、アニメーションブロックをつけた後に、やっぱりアニメーションつけるのやめようと思うことがたまにあります。アニメーション解除ができないので、今はアニメーションブロックから中身を全部出してからアニメーションを削除しているので、手間なので解除ができたら便利そうです。（グループブロックのグループ解除みたいなイメージです）

アニメーションがついているパターンは、アニメーションがいらない人もいると思いますので、ユーザー側も解除できたら嬉しいのではないかなと思いました。

複雑になったり仕様上難しいようでしたらCloseしてくださいmm

**Comment by sysbird** [comment]
解除あると便利ですね！
Outer とかも

**Comment by shimotmk** [comment]
こんな感じでラップ,アンラップの変換機能は出来そうです

https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/c4782e42-b337-4ce7-b5b1-8f6f15a92b94

**Comment by goutetsuguma** [comment]
@shimotmk @kurudrive @sysbird 
めちゃ便利そうです！

**Comment by sysbird** [comment]
こちらマージされてたんですね、ありがとうございます
追えてなくてごめんなさい
リリース待ちにしておきます

**Comment by shimotmk** [comment]
リリースされていたのでclose
