### ISSUE TITLE
【確認待ち】［Outer］幅は全幅、余白 (左右)：コンテンツエリアに合わせる にしたときにコンテナ内部のスペース設定がPCサイズでcssが上書きされて効いていない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1612]
テーマはKatawaraで、幅は全幅、余白 (左右)：コンテンツエリアに合わせる にしたときにコンテナ内部のスペース設定がPCサイズ(min-width: 1200px)でテーマ側のcssに上書きされて効いていないようでした。

KatawaraのCSS（このpaddingに上書きされる）
```
@media (min-width: 1200px)
.vk_outer.vk_outer-width-full.vk_outer-paddingLR-none .vk_outer_container {
    width: 100%;
    max-width: 1140px;
    margin: auto;
    padding-right: 15px;
    padding-left: 15px;
}

```

VK BlockのCSS
```
@media (min-width: 992px)
.vkb-outer-a1f7b5bd-9bfc-4f39-9655-6c4f28204327 .vk_outer_container {
    padding-left: 300px;
    padding-right: 300px;
}
```

----

あと、「コンテナ内部のスペース設定」は左右の余白が設定できるのですが、上下もできると勘違いしそうな気がしました。
「コンテナ内部のスペース設定（左右）」とするのはどうでしょうか。

・Lightningでも同様になることを確認しました

**Comment by kurudrive** [comment]
親のOuterの指定が子のOuterにかかっちゃってるから

vkb-outer-a1f7b5bd-9bfc-4f39-9655-6c4f28204327 > .vk_outer_container {

みたいに > 指定追加する必要があるっぽいです。

**Comment by drill-lancer** [comment]
マージされたので Close
