### ISSUE TITLE
[ レスポンシブスペーサー ] 0の値にしたい場合

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1617]
レスポンシブスペーサーをPCでは値を入れて、スマホなどではmarginを無しにしたい場合は、非表示設定でスマホで非表示にすれば良いのですが、パターンなどでお客さんがコピーして触る時に、非表示機能にしていると気づきにくくて、スマホのサイズを設定しているのに値が効いていないと勘違いしてしまうのではないかなと思い、0の設定もできると良いなと思いました。

仕様的に難しいかもしれないので、その場合はCloseしてください。

**Comment by sysbird** [comment]
おぉ、そうですね
私はたまにスマホで非表示を使っちゃってますが、0のほうがわかりやすいと思います!

**Comment by kurudrive** [comment]
そうね、0にしたい場面はあると思うので、0が指定できるように調整してもらいましょう。
