### ISSUE TITLE
【機能追加要望】［グリッドカラムカード］色の透過設定できる機能がほしい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1620]
現状では透過設定ができないようでした。

透過設定が追加できるのかを調査、できそうであれば実装をおねがいいたします。

Assigneesにはいったん開発の皆様を入れさせていただきましたので、作業する際にご自分のアイコンに変更などしてください🙇‍♂️

----

コアのカラムブロックだとalpha-pointerというのがついているけど、VK Blocksの例えばOuterブロックだと背景の透過は「透過設定」で実装しているので、どちらに合わせるとかあるのでしょうか？
意見の調整が必要そうだったので、いったん意見調整待ちとしました🙇‍♂️

**Comment by doshimaf** [comment]
コアに合わせるのであれば、影響範囲は大きいですがAdvancedColorPaletteコンポーネントでColorPaletteコンポーネントのenableAlphaプロパティを使えるようにすることで実装できると思いました。

Outerブロックのにあわせるほうが影響範囲と実装コストは小さく済みそうです。

**Comment by shimotmk** [comment]
AdvancedColorPaletteにenableAlphaプロパティを使えるようpropsを追加したら良いのではないですか。
Outerブロックの透過設定はコアのCoverブロックと同じ仕様でクラス名でopacityを変えているので透過の意味合いが少し違います。

**Comment by kurudrive** [comment]
@doshimaf @shimotmk 
確認ありがとうございます。どちらかキリの良いタイミングで結構ですので対応よろしくお願いいたします。

**Comment by shimotmk** [comment]
対応します〜

**Comment by shimotmk** [comment]
リリースされていたのでclose
