### ISSUE TITLE
プルリク時のGithub workflowの動作について確認

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1622]
プルリク時、テスト以外にテストサーバーへのデプロイが含まれるようで、このデプロイはPHP/WPバージョンの組み合わせで計12回動作しているように見えます。（#1376 で私スルーしてますね・・・今さらすみません）
https://github.com/vektor-inc/vk-blocks-pro/blob/9833cb8a5fc01181fa570cee2ddd0241204332d8/.github/workflows/develop-test.yml#L73-L83

つまり、1回のプルリクで12回同じようなファイルをサーバーにアップロードしているような気がしますが、これは意図した挙動でしょうか。AさんとBさんが同時にプルリクを投げるとおかしなことになりませんか？ 

最低限、テストとデプロイでジョブを分けて、1回のプルリクで走るデプロイを1回だけにしたほうがよさそうな気がします。
もしくは、プルリク時はテストが走るだけにして、テストサーバーへのデプロイは別のトリガーにできないでしょうか。

Workflowあまり詳しくないので、変なこと言ってたらすみません。気になったので書いておきます。

**Comment by kurudrive** [comment]
はい、少なくできるのは少なくしたいです（・ｗ・；
