### ISSUE TITLE
プロ版のブロックに翻訳があたらないので修正したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1624]
VK Blocks の翻訳やはり、無料版を先にインストールしてる人がプロ版を入れると、無料版の翻訳ファイルが優先されて、プロ版のブロックの翻訳があたらなくなってしまう感じですね...

どうしたものか...

**Comment by drill-lancer** [comment]
@kurudrive 
無料版のテキストドメインを vk-blocks
有料版のテキストドメインを vk-blocks-pro とするのが良いような気がします。
（Filter Search はそんな感じです。）

**Comment by drill-lancer** [comment]
月曜日から着手する予定です。

**Comment by drill-lancer** [comment]
リリース済みなので Close
