### ISSUE TITLE
【機能追加要望】［アイコンブロック］アイコンと枠のスタイル時に、背景色（白とか）を入れれると嬉しいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1625]
たとえばこんなアイコンを作りたい場合
![LP_求人_-Lightning-×-ExUnit-日本語デモ](https://user-images.githubusercontent.com/5525368/229986057-63126255-5fe8-40d4-b21a-f1a5f0fb8290.png)

アイコンと枠のスタイル時の背景は透明になるけど、色が選択できると嬉しい。
入れるとしたらほとんど白背景が多そうなので、背景を白にするのチェックボタンでも良いかも、、？

そもそもパターンで実装すればいいだけかもしれません、、！一応issue化しておきます

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1936
