### ISSUE TITLE
ボタンブロックに問題があるらしいので要確認

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1636]
@shimotmk ↓の件一度状況確認よろしくお願いいたします (￣人￣)

https://vws.vektor-inc.co.jp/forums/topic/vk-blocks-button-1-54

**Comment by kurudrive** [comment]
@shimotmk この件って今対応中でしょうか？症状発生するかなど一旦状況確認よろしくお願いいたします。

**Comment by shimotmk** [comment]
> @shimotmk この件って今対応中でしょうか？症状発生するかなど一旦状況確認よろしくお願いいたします。

症状発生が確認できません。

**Comment by kurudrive** [comment]
@shimotmk 確認ありがとうございます。

**Comment by kurudrive** [comment]
プラグイン EditorsKit と干渉するっぽい
