### ISSUE TITLE
ライセンスキーの入力欄に「Lightning G3 Pro Pack」と書いてあるので「Vektor Passport」に変更

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1637]
![VK-Blocks-設定-‹-Vektor-WordPress-Solutions-—-WordPress](https://user-images.githubusercontent.com/5525368/231907119-e5eb8478-4e9e-4617-8d3e-3ab3a4f93d17.png)

**Comment by kurudrive** [comment]
これ今から僕が対応します。
