### ISSUE TITLE
リストブロックを配置すると warning が出るの僕だけ？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1640]
develop ブランチ / ※ WP_DEBUG true で確認

編集画面でリストを配置

```
<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>あああああ</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>おおおおお</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
```

以下が編集画面でも公開画面でも表示されてしまう

Warning: Undefined array key "className" in /var/www/html/wp-content/plugins/vk-blocks-pro/inc/vk-blocks/extensions/core/list.php on line 17

**Comment by shimotmk** [comment]
出るかもです。直します

**Comment by kurudrive** [comment]
@shimotmk 確認ありがとうございます。よろしくお願いいたします (￣人￣)

**Comment by shimotmk** [comment]
closed this as completed in #1641
