### ISSUE TITLE
[カスタムCSS] あとから空にしたとき属性がコードに残っている

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1645]
カスタムCSS をいったん設定したブロックで、あとからカスタムCSS を空にしたとき
下記のコードが属性に残るので、削除してもらえるとスッキリします

`"vkbCustomCss":""`

**Comment by kurudrive** [comment]
@shimotmk これって消せる？

**Comment by shimotmk** [comment]
空文字''のときはundefinedで保存すれば消せると思います
https://github.com/WordPress/gutenberg/blob/33665ae206452e29ad8a271b8c8eee43d33f0108/packages/block-editor/src/hooks/custom-class-name.js#L69-L74

**Comment by shimotmk** [comment]
リリースされていたのでclose
