### ISSUE TITLE
リスト表示やブロックをドラッグ＆ドロップする時のアイコンがいくつか白抜きになっていない

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#1646]
このissuesを確認していた時に気づきました。
https://github.com/vektor-inc/vk-filter-search-pro/issues/261

VK Blocks以外のブロックでも発生しますが、とりあえずVK Blocksにissuesをたてておきます。

https://user-images.githubusercontent.com/42362903/233560437-2477a167-5b95-49e4-a2ef-8e3cfae29434.mp4

上記のビデオの通り、リスト表示やブロックをドラッグ＆ドロップする時のアイコンがいくつか白抜きにならないことがあります。
VK Blocksは横並びアイコン、横並びボタンは大丈夫な気がします。

VK Filter Searchは
VK Custom Field Search 
検索結果の並び替え
のみ白抜きになりませんでした。

気づく人は少ないかもですが、ドラッグ＆ドロップする時などにどのブロックを動かしているかわかりやすくなると思うのでお手隙の際に @goutetsuguma 確認お願いできますか？

**Comment by goutetsuguma** [comment]
Marge済みなのでCloseします
