### ISSUE TITLE
カスタム書式設定のツールバーの中の項目がセンター揃えになっているので修正したいデス。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1653]
![スクリーンショット 2023-04-30 17 46 44](https://user-images.githubusercontent.com/3272660/235344327-4abf5bd9-9cc5-4f0f-92e3-12b73170c2bd.png)

たぶん has-text クラスがあれば良いと思います。

**Comment by shimotmk** [comment]
リリースされたのでclose
