### ISSUE TITLE
[ 子ページリスト ]「該当の固定ページはありません。」の表示がフロント画面にも出る

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1661]
該当の固定ページがない場合「該当の固定ページはありません。」のメッセージが表示されますが、フロント画面にも表示されます。
ExUnitの子ページ一覧ブロックでは「子ページがありません。」のメッセージはフロント画面には表示されません。（管理画面のみです）

もし可能であれば、ExUnitの子ページ一覧ブロックのようにフロント画面には表示されない方が良い気がしましたが、どうでしょうか。

【気づいた理由】
あまり「該当の固定ページはありません。」のまま公開することは無いと思うのですが、たとえばパターンでこのブロックを使用した場合に、コピペでフロント画面に出てしまうので、非表示の方が良いのかなと思った感じです。（実際にExUnitの子ページ一覧ブロックを使用しているパターンがあったため、VK Blocks の子ページリストの方が融通がきくので変更したところ、フロント画面に出てしまったため）

不要そうであればCLOSEしてください🙇‍♂️

**Comment by kurudrive** [comment]
フロントには表示しない処理でよろしくお願いいたします。

**Comment by doshimaf** [comment]
@kurudrive 
こちら、投稿リストブロックと同じ`class Vk_Blocks_PostList`で処理を行っており、投稿リスト側ではフロントに投稿が無い旨が表示されます。
子ページリストブロックの場合はフロントに表示せず、投稿リストブロックの場合はフロントに表示されるようにするということで良いでしょうか？
