### ISSUE TITLE
[ ダイナミックテキストブロック ] カスタムフィールド対応したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1685]
1. プルダウンでカスタムフィールドを選択  
→ フィールド名入力欄が表示される

フィールドの下には以下のアラートメッセージを表示

現状単純なテキスト表示のみの想定です。
画像などの表示には対応していません。

**Comment by doshimaf** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1366

**Comment by kurudrive** [comment]
@doshimaf ちなみに、普通に書くだけだと、クエリーループ内ではどの投稿idのフィールドなのかの判断ができず、ループ内のアイテムにならないっぽいので、ちゃんとループ中の投稿idを引き渡す必要があるっぽいです。
先日キタジマさんが Snow Monkey Blocks で実装してるので、上手く動作しなかったらそちらのリポジトリを参考にするとヒントがあると思います。
