### ISSUE TITLE
[ダイナミックテキストブロック] スタイルの設定をするとエラーが出る

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1691]
スタイル（たとえばフォントサイズ）を変更し、「表示要素」を有効なもの（ServerSideRenderが呼ばれる条件）にすると、エラーがでます。

![image](https://github.com/vektor-inc/vk-blocks-pro/assets/1535140/61410b1d-9aae-4715-b770-a9b951363da6)

ServerSideRender に渡す attributes に supportsを使った属性を含めるのはNGなのかなと思いました。ので、block.jsonのattributesにfontSizeなどの項目を加えるか、ServerSideRenderにsupportsの項目は渡さないようにすればいいのかなと思いました。
推測なので外してたらすみません。

※ ダイナミックテキストブロックは大嶋さんがいろいろ調整していただいているので、とりあえず大嶋さんだけにアサインしました。

**Comment by doshimaf** [comment]
@mthaichi 
ありがとうございます！
設定オプションではanchor、スタイルは全てでブロック読み込みエラーが表示されることを確認しました。

> ServerSideRender に渡す attributes に supportsを使った属性を含めるのはNG

色々と試したところ、おそらくこのとおりだと思います。
supportsにあるものに関しては、attributesに加えて使えるようにする必要があると思います。

@kurudrive 
現状、この方法でのスタイル設定となりそうな気がしますがいかがでしょうか？

**Comment by kurudrive** [comment]
@doshimaf @mthaichi おや？
僕の場合発生しなかったのですが、どういう手順で発生します？

**Comment by kurudrive** [comment]
> スタイル（たとえばフォントサイズ）を変更し、「表示要素」を有効なもの（ServerSideRenderが呼ばれる条件）にすると、エラーがでます。

あぁ...おや？うーん、僕フォントサイズとか変更して、保存して再読み込みしても問題はなかったんですよねぇ...
ただ、attributes 指定無しで使えちゃってええの？ とは思ってましたが...

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/c2768ca1-9334-45f9-9712-14452ac87bdb

**Comment by kurudrive** [comment]
@doshimaf @mthaichi あー、サイトエディタだと大丈夫で、普通の投稿で使うとダメっぽいですね...。

**Comment by kurudrive** [comment]
@doshimaf まぁ基本サイトエディタ用のブロックではあるけど、通常の投稿編集ページでもエラーにならないように一度調整を試みてくださいー 。
やらかしたのは僕ですみませんがよろしくお願いいたします。(￣人￣)

**Comment by shimotmk** [comment]
これでいけるかもです。
`skipBlockSupportAttributes`
https://github.com/WordPress/gutenberg/pull/44491

**Comment by doshimaf** [comment]
リリースされたのでclose
