### ISSUE TITLE
developブランチでphpunitが通らない

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-blocks-pro#1698]
<img width="1342" alt="スクリーンショット 2023-06-01 10 56 19" src="https://github.com/vektor-inc/vk-blocks-pro/assets/73574599/ec9c865e-887c-4c70-9f63-d202f0d62b92">

**Comment by kurudrive** [comment]
@doshimaf あら、確認します。

**Comment by kurudrive** [comment]
あぁ...6月になったからか。

**Comment by doshimaf** [comment]
リリースされていたのでclose
