### ISSUE TITLE
無料版のプロ版判定が誤動作するのを修正したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1704]
@drill-lancer 

vk-bloks-pro を vk-blocks に置換してしまうので発生していると思われます。

https://github.com/vektor-inc/vk-blocks/pull/135

暫定版は配信してるので対応は月曜日以降で問題ありません。

- [ ] 無料・有料判定のPHPUnitも追加してください

**Comment by drill-lancer** [comment]
マージされたので Close
