### ISSUE TITLE
【相談】グリッドカラムカードブロックを使いカード全体にリンクした時に、テキスト下にunderlineがはいる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1705]
特にアンダーラインが入っても問題ないのですが、Lightningテーマではテーマ側でアンダーラインが入らないようなcssが書いてあるので、合わせた方が良いのかな？と思いissueをたてました。

https://patterns.vektor-inc.co.jp/vk-patterns/grid-column-card_example/

アンダーラインがはいっても問題なさそうであればCloseしてください。

**Comment by kurudrive** [comment]
- [ ] Lightning 側の指定を削除

**Comment by mtdkei** [comment]
fixがマージされていたようなのでCloseします
