### ISSUE TITLE
［見出しのカスタムスタイル］サイトエディターで一部のスタイルが崩れる

### ISSUE THREAD

**Issue by osmdik** [vektor-inc/vk-blocks-pro#1709]
<img width="1204" alt="スクリーンショット 2023-06-05 12 14 07" src="https://github.com/vektor-inc/vk-blocks-pro/assets/73574599/88bb231e-4701-4a1d-8062-4ba763180262">

X-T9でサイトエディターに見出しを配置した場合、「左右線」「括弧　黒」のカスタムスタイルでブロックがホバーまたは選択された場合にスタイルが崩れます。

下記であてられているスタイルが原因のようです。
```
.is-outline-mode .block-editor-block-list__block:not(.remove-outline).is-selected:after
```

**Comment by goutetsuguma** [comment]
［自分用メモ］
これ、直そうかなと思いましたが、CSSでafter部分を打ち消すと、hoverまたは選択した場合に出るブルーの線は出なくなってしまいますよね、、、（添付画像）
デザイン崩れる方が気になるので、打ち消しても良いのかな、、

<img width="1419" alt="スクリーンショット 2023-06-06 10 37 21" src="https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/f71ed0ee-455a-43c9-8cfc-63355e450714">

**Comment by kurudrive** [comment]
しゃーない close
