### ISSUE TITLE
［横並びアイコンブロック］グループ化すれば良いのですが、非表示設定がないのは仕様でしょうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1716]
パターンを作っていて気づいたのですが、横並びアイコンブロックには非表示設定が表示されませんでした。
グループ化したり、横並びブロックにアイコンブロックを配置すれば良いので、それで運用するのが正解でしたらissueをCloseしてくださいmm

**Comment by sysbird** [comment]
はい、仕様ではなく、
私がアイコンブロックを作ったときの実装し忘れと思いますー
ごめんなさい

**Comment by goutetsuguma** [comment]
コメントありがとうございますmm
ぜんぜん急ぎではないですので、お手隙の際にご確認・調整よろしくお願いします🙇

（Assigneesにトリさんを入れさせていただきました）

**Comment by sysbird** [comment]
マージ済みにつき閉じまーす
