### ISSUE TITLE
インポート・エクスポート機能が画面を再読み込みしないと正しくデータがエクスポートされないっぽい空気を感じます

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1718]
@shimotmk 基本的にめちゃすばらしいです！さすがです！

ただ、動作確認していたら不具合っぽい部分があったので確認よろしくお願いいたします。

1. カスタムブロックスタイルを編集・保存
2. エクスポート
3. インポート

→ 正しく反映されない。

1. カスタムブロックスタイルを編集・保存
2. 画面を再読み込み
3. エクスポート
4. インポート

→ 正しく反映される。

https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/c54bcdc3-cc8d-431e-8590-64ba2975654f

**Comment by shimotmk** [comment]
これは、確認いただいた他の方にも悪いので書いておきますが、仕様変更にあたります。

ここでのやり取りをよく読んでくさい
https://github.com/vektor-inc/vk-blocks-pro/issues/1539#issuecomment-1552695327

**Comment by kurudrive** [comment]
@shimotmk @mthaichi 

おや？でも設定を「保存ボタンを押した後」での動作なので、
保存値の参照がうまく動作していないとかではなくて？

**Comment by kurudrive** [comment]
なんとなく元のやりとりは

「保存されてない入力値がJSONに出力されるのは違うんじゃない？」
→ 「保存値にしましょう」

だと思うので、保存ボタンを押したのに反映されてないデータがエクスポートされてるのはおそらく意図した動作ではないのかなと...

でも繰り返しますが機能はすばらしいです。ありがとうございます。ありがとうございます。

**Comment by mthaichi** [comment]
@shimotmk @kurudrive 
先程の終礼の報告を聞くに、もう修正に取り掛かっておられるかもしれませんが・・・。

保存直後に画面遷移なしでエクスポートするとたしかに保存値が反映されませんね。
設定保存時に  vkBlocksObject が反映されないって感じでしょうかね。

ご調整ありがとうございます。

**Comment by shimotmk** [comment]
リリースされたのでcloseします
