### ISSUE TITLE
ライセンスキーが通常見えないようにしたいらしい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1719]
案１）

* ライセンスキーの入力フォームが非表示になるプラグインを作る

案２）

* 未入力または、期限が切れている時にフォームを表示
* 切れていない時はフォームを表示しない
* フォームが見れるプラグインを有効化したらライセンスキーが有効期間中でもフォームが表示される

★ 案３）

所定のコードを子テーマのfunctions.phpとかにぺって貼ったらライセンスキーが非表示になるようにフックだけ用意する

**Comment by drill-lancer** [comment]
リリース＆お知らせ記事ができたので Close
