### ISSUE TITLE
［ダイナミックテキスト］「先祖階層のページでは非表示にする」にしていても固定ページ以外では表示されてしまう。

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-blocks-pro#1721]
https://github.com/vektor-inc/vk-blocks-pro/blob/faf1e4882aadab8f81bc315df1e147da92997c1c/src/blocks/_pro/dynamic-text/index.php#L25

先祖階層のページを選択時、固定ページ以外（投稿など）で先祖階層が無い場合、「先祖階層のページでは非表示にする」にチェックが入っていてもその投稿タイトルが表示される。

仕様っぽいですが、調整をしていて違和感を感じたのでissueにしています。
この仕様で問題なければcloseして下さい。

**Comment by kurudrive** [comment]
@doshimaf 僕も問題のように感じます（・ｗ・；
