### ISSUE TITLE
[ ダイナミックテキスト / カスタムフィールド ] サイトエディタでフィールド名が表示されるようにしたいです

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1723]
現状（ https://github.com/vektor-inc/vk-blocks-pro/pull/1697 ）表示が 「Custom Field」 になるので、複数配置した時に何の値かわかりやすくしたいなと。

**Comment by doshimaf** [comment]
メモ
`editContent = <TagName>{__('Custom Field for', 'vk-blocks-pro')} {customFieldName}</TagName>`
