### ISSUE TITLE
横並びボタンブロックは グループの横並びでカバーできるから非推奨化でいいんじゃない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1729]
どう？

**Comment by kurudrive** [comment]
非推奨扱いに変更

**Comment by goutetsuguma** [comment]
パターンをつくってて思ったのですが、横並びボタンは、添付画像のようにPCとタブレットとモバイルでボタンの幅が変えられるので、需要があると思いました。

グループの横並びを使用しても、このあたりの細かいところは調整が難しいです。
カラムブロックをおいて、カラムアイテムに横幅100%のボタンをおけばいけますが、タブレットでは50%の幅で2つ並んで欲しいなど、細かい調整となると難しいです。

ですので非推奨じゃなくてもよいのかなと思いましたがどうでしょうか。

![スクリーンショット 2024-06-05 15 24 08](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/8cf4fe6c-d872-4777-b48a-3343431e8ab1)

**Comment by sysbird** [comment]
> PCとタブレットとモバイルでボタンの幅が変えられる

たまに使いますね
けっこう良いと思いますよ〜

**Comment by kurudrive** [comment]
ではイキで close （・ｗ・
