### ISSUE TITLE
[ブロックマネージャー設定] チェックボックスをON/OFFすると、他の変更項目が元に初期化されて戻ってしまう

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#1735]
ブロックマネージャー設定でチェックボックスをON/OFFすると、他に変更した項目が元に戻ってしまいます。

具体的には「FAQ Blocks 設定」のアコーディオン無効を有効に切り替えた後に、ブロックマネージャーのチェックボックスをトグルさせると、アコーディオン無効に戻ります。

https://github.com/vektor-inc/vk-blocks-pro/blob/7b90a0ea8d17ff0d71c9c3fa85d41aebdce2359e/src/admin/block-manager/category.js#L33-L72

上記の部分の toggleVisible と toggleAllVisible 関数で useCallbackが使われていますが、依存を [showBlockTypes, hideBlockTypes]に指定して、showBlockTypesとhideBlockTypesもuseCallbackを使って、[vkBlocksOption, setVkBlocksOption]を依存指定すればいいのかなと思いました。

修正してプルリクしてもいいのですが、自分が盛大に勘違いしている可能性もあり、いったんissueにあげておきます。

**Comment by shimotmk** [comment]
リリースされたのでcloseします
