### ISSUE TITLE
[FAQ] アコーディオン開くの初期設定がブロックごとにほしいときがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1738]
[FAQ] アコーディオン開くの初期設定はVK Blocks 設定にありますが、ブロックごとにほしい気がしました
というのは、パターンライブラリでパターンごとに設定できないからです

たぶん理由があってこうなってて、通常はサイトごとでよいのかもしれないですね

**Comment by goutetsuguma** [comment]
パターンだとブロックごとに欲しいなと思う時がありますね。

過去のフォーラムですが、ブロックごとに欲しいという意見はありました。

https://vws.vektor-inc.co.jp/forums/topic/qa%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%82%92%e5%80%8b%e5%88%a5%e3%81%ab%e3%82%82%e3%82%aa%e3%83%bc%e3%83%97%e3%83%b3-%e3%82%af%e3%83%ad%e3%83%bc%e3%82%ba%e3%82%92%e6%8c%87%e5%ae%9a%e5%8f%af

**Comment by doshimaf** [comment]
リリースされたのでclose
