### ISSUE TITLE
[ ダイナミックテキスト カスタムフィールド ] サイトエディタでなく投稿本文に配置した場合にエディタ上で何も表示されなくなるので、サイトエディタ同様にフィールド名を表示したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1741]

**Comment by doshimaf** [comment]
@kurudrive 
現状はフィールド名指定して更新をかけると設定したフィールド名の値が出力される仕様ですが、サイトエディタと同様フィールド名のみの表示で良いでしょうか？

**Comment by kurudrive** [comment]
@doshimaf あー、そういう事か、それだと良くないね。そしてPHPだからリアルタイム反映もできないのか...
ぐぬぬ...一旦closeします ＞＜
