### ISSUE TITLE
[CSS / JSの分割読み込み] 見出しのスタイルが当たらない場合がある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1744]
CSS / JSの分割読み込みが ON のとき見出しのスタイルが当たらない
下記のテーマで発生するようです
* x-t9
* Twenty Twenty-Three

■ 関連
https://github.com/vektor-inc/vk-blocks-pro/issues/1319
https://github.com/vektor-inc/vk-blocks-pro/issues/1773

**Comment by kurudrive** [comment]
ローカルと ↓ で見る限り問題なさそうな空気を感じます（・ｗ・

https://www.vektor-inc.co.jp/post/vektorinc-2023-camp-tokyo/

**Comment by sysbird** [comment]
そうですね、私のローカル環境だけでした
VK Block の設定をあれこれ変更してたら再現しなくなりました
また見かけたら報告します

いったん閉じますねー

**Comment by ChiakiKouno** [comment]
本日、イベント情報を更新したところ、同じ現象が見られましたので、リオープンさせていただきます🙏

https://www.vektor-inc.co.jp/info/monthly-product-update-info-202307/

**Comment by sysbird** [comment]
ローカル環境でまた発生しています
このとき下記のCSS が読み込まれてないようです
/wp-content/plugins/vk-blocks-pro/build/extensions/core/heading/style.css

ブロックテーマで発生
クラッシックテーマでは発生しない

**Comment by mtdkei** [comment]
https://github.com/vektor-inc/vk-blocks-pro/pull/2130
のブランチで解決されているようでしたのでCloseします。
