### ISSUE TITLE
ブログカードブロックが欲しいデス

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1751]
* URLを入力
* OGデータからタイトルやアイキャッチから情報を取得して表示

■ 表示要素
...固定でいいかな？下記のように選択出来るようにする必要ある？どう思う？
* タイトル : まぁこれは必須よね
* アイキャッチ : これも普通必須よね
* 抜粋 : これも表示するよね？不要なケースある？
* URL : 表示・非表示選択機能必要？
* 投稿者 : 表示・非表示選択機能必要？
* サイトアイコン : 表示・非表示選択機能必要？

■ レイアウト
* 画像左
* 画像右
* 大画像 & 画像下文字

■ スタイル設定項目
* 枠線
* padding
* margin
* 枠線
* 文字色

**Comment by shimotmk** [comment]
Duplicate #749

**Comment by kurudrive** [comment]
oh...しまった。過去に立ててますね...。失礼しました。

**Comment by shimotmk** [comment]
これ少し考えていたのですが、１つのダイナミックブロックではなく表示要素をそれぞれブロックに分けて既存のブロックの組み合わせで再現できないですかね。
(**ブログカードブロックが不要と言う意味ではなく表示要素をブロックごとに分けると言う意味です**)

カラムブロックでそれっぽものは出来たのですが、右側に画像がある場合スマホの時に画像を上にする`flex-wrap: wrap-reverse;`にする方法が思いつかず。。。

![colun](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/df9f53d6-b568-4a88-be81-c29d17da3433)

作ってみたコード
```HTML
<!-- wp:columns {"style":{"spacing":{"blockGap":{"top":"0","left":"0"}},"border":{"color":"#0000001f","width":"1px","radius":"5px"}}} -->
<div class="wp-block-columns has-border-color" style="border-color:#0000001f;border-width:1px;border-radius:5px"><!-- wp:column {"width":"66.6%","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-column" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);flex-basis:66.6%"><!-- wp:heading {"level":5,"style":{"typography":{"textTransform":"none"}}} -->
<h5 class="wp-block-heading" style="text-transform:none"><a href="https://www.vektor-inc.co.jp/">株式会社ベクトル | WordPressテーマ・プラグイン開発のクリエイティブカンパニー</a></h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル抜粋サンプル粋抜</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:image {"sizeSlug":"large","style":{"layout":{"selfStretch":"fixed","flexSize":"15px"}}} -->
<figure class="wp-block-image size-large"><img src="https://www.vektor-inc.co.jp/wp-content/uploads/2020/03/cropped-icon2020-32x32.png" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p><a href="https://www.vektor-inc.co.jp/">株式会社ベクトル</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","width":"33.3%","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-column is-vertically-aligned-top" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30);flex-basis:33.3%"><!-- wp:image {"align":"center","sizeSlug":"large","linkDestination":"custom","style":{"border":{"color":"#0000001f","width":"1px","radius":"5px"}}} -->
<figure class="wp-block-image aligncenter size-large has-custom-border"><a href="https://www.vektor-inc.co.jp/wp-content/uploads/2020/04/vecktor-inc_ogp2020.png"><img src="https://www.vektor-inc.co.jp/wp-content/uploads/2020/04/vecktor-inc_ogp2020.png" alt="" class="has-border-color" style="border-color:#0000001f;border-width:1px;border-radius:5px"/></a></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

パターン作ってる方で何か良いアイディアあったら教えていただけたら嬉しいです🙇‍♂️

**Comment by kurudrive** [comment]
@shimotmk 検討ありがとうございます。

> １つのダイナミックブロックではなく表示要素をそれぞれブロックに分けて既存のブロックの組み合わせで再現できないですかね。

それはたとえば ブログカード というアウターブロックがある上でそのインナー要素としてブログカードブロックやブログカードタイトルブロックを用意するみたいな方式という意味？

**Comment by shimotmk** [comment]
> それはたとえば ブログカード というアウターブロックがある上でそのインナー要素としてブログカードブロックやブログカードタイトルブロックを用意するみたいな方式という意味？

そうですね。

**Comment by kurudrive** [comment]
@shimotmk 

なーるほどー。そういう構成も確かにありなのか...
その発想はなかったです。さすがです。

うーん、でもどうかなー。ブロックの性質上そんなに細かいチューニングは求められないとも思うんですよね。
それよりも手軽さの方が求められるというか。

ブロックが分かれると
→ デザイン調整しようとしたらそれぞれのブロックに切り替えて、そこからさらにスタイルタブに切り替えて...と何気に手数が増える（パターン調整してるとそのあたりの作業が結構手数多いなと感じる）
→ 初心者にもやはり「ブロックが入れ子になってて更にスタイルの各項目を調整」というのはハードルが高い
→ 頻繁に使うものなので、手軽に配置できる方が良い。
分割構成の場合、自分でお気に入りのレイアウトを作る > 自分でパターン登録する > パターンから呼び出す という操作が特にハードル高い
→ ブロック一つで限られた設定項目の方が楽

と、言うような気がしますが...

でも 記事タイトルやサイトタイトルの文字サイズや余白がブロックで調整出来た方がいい気もするし...

でもそこはカスタムブロックスタイルとかで配布すればいいんじゃね？サイト全体で統一させやすいし...うん。

個人的には一つのブロックの方がいいんじゃないかなと思います。

他のみなさんもご意見どうでしょう？
おそらく広報チームのみなさん頻繁に埋め込みで使うと思うのでぜひご意見いただければ。

**Comment by shimotmk** [comment]
何にもモノが無い状態で意見を求めても憶測で判断することになり不毛な議論になるので一旦両方のパターンで作ってみます。

その後フィードバックをいただけたらと思うのでその際はよろしくお願いします

**Comment by shimotmk** [comment]
Duplicate #749
