### ISSUE TITLE
[ ダイナミックテキストブロック カスタムフィールド ] URL対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1753]
■ 入力UI
* フィールドタイプに URL を追加
* URLを選択されたら「リンクを設定する」のトグルを表示
* 「リンクを設定する」が true になったら「別ウィンドウで開く」のトグルを表示

■ 出力
* リンクを設定するが true の場合は a タグでラップして出力
* 別ウィンドウで開くが true の場合は ` target="_blank" rel="noreferrer noopener"` 追加

**Comment by doshimaf** [comment]
@kurudrive 
URL対応してみたので、仕様がイメージしている通りかどうか確認をお願いいたします。
https://github.com/vektor-inc/vk-blocks-pro/pull/1756

**Comment by doshimaf** [comment]
リリースされたのでclose
