### ISSUE TITLE
［ダイナミックテキスト］カスタムフィールドのURLでリンク設定がtrueの場合の不具合

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-blocks-pro#1760]
- カスタムフィールドを選択し、フィールドタイプにURLを選択
- リンク設定をtrueにしてフィールドタイプをURL以外に変更
- リンクを別ウィンドウで開くが表示されたままになる

**Comment by kurudrive** [comment]
@doshimaf マジカ...。発見ありがとう。まだリリースしてないのでよろしくお願いいたします (￣人￣)

**Comment by doshimaf** [comment]
リリース済のためclose
