### ISSUE TITLE
［ダイナミックテキスト］カスタムフィールドの繰り返し対応

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-blocks-pro#1766]
Smart Custom Fieldsで繰り返し可能なカスタムフィールドを追加して試したところ、おそらく繰り返しの中の最初のフィールド値のみが出力され、繰り返したフィールド値は出力されません。

このブロックはカスタムフィールドの繰り返しに対応させたほうが良いでしょうか？

**Comment by kurudrive** [comment]
あ、違うわ。条件分岐の方じゃなくてダイナミックテキストか。
いやー・・・でも繰り返しってクラシックエディタ時代にレイアウトを積むために使ってたけど、それはブロックエディタでできるからいらないんじゃないかな？

**Comment by doshimaf** [comment]
確かにブロックエディタだと何かしら積むときに繰り返しフィールドを使うことはまず無いですね。。
あったとしてもかなりイレギュラーなケースになりそうなので、対応しない方向で良いでしょうか？

**Comment by kurudrive** [comment]
とりあえず必要な場面に出くわしたり、ユーザーからの実用的なニーズと判断できるリクエストがあってから検討でいいのではないかなと思います。

**Comment by doshimaf** [comment]
承知しました！
