### ISSUE TITLE
［グリッドカラムカード］グリッドカラムボディにスライダーを入れるとフロント画面に表示されない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1768]
ボタンを揃えたくて、グリッドカラムカードのボディにスライダーを入れたのですが、フロント画面では表示されないようでしたので聞いてみました🙇‍♂️グリッドカラムカードはちょっと複雑そうなので、おそらくスライダー入れるのは非推奨ですかね、、？

https://demo.dev3.biz/lightning-g3-pro/test-column/

**Comment by kurudrive** [comment]
何故こうなるのかワカリマセン。気が向いたら調査してください（＝ｗ＝；

**Comment by kurudrive** [comment]
でも、スライダー入れてもボタンはスライダーの下になるから意図したレイアウトにはならないのでは？

それよりスライダー内で Grid でレイアウト指定した方がよいように思いますがどうでしょう？

**Comment by mtdkei** [comment]
本件確認してみました。現在はグリッドカラムボディにスライダーを入れるとフロント画面に表示されない現象は無くなったようなので一旦Closeにいたします。
