### ISSUE TITLE
Windows のXAMMPで設定画面でCSSとJSが読み込まれない（ローカル環境）

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1772]
■ WordPress のバージョン
6.2.2

■ テーマ・プラグインは全て最新版で確認してください。
確認しました。

■ 子テーマをご利用の場合は親テーマに変更して症状が改善するか確認してください。
確認しました。

■ テーマの種類
Lightning ( G3 ) + Lightning G3 Pro Unit

■ テーマのバージョン
15.9.5

■ Pro Unit のバージョン
9.90.2.0

■ スキンの種類
プレーン

■ 関連しそうなプラグインを一つづつ停止して症状が改善するか確認してください。
確認しました。

■ プラグインの種類・バージョン
ExUnit：9.90.2.
VK Blocks Pro：1.60.0.0
Lightning G3 Pro Unit：0.25.1

■ 期待する動作
ローカル環境でも正常なURLでCSSとJSファイルを読み込める様にご対応をお願いいたします。

■ 自分で試した事
キャッシュクリア
プラグインのバージョンアップ
ローカルサーバとWebサーバの同じ仕様のサイトとの比較など

■ 症状が発生するブラウザ
Google Chrome、FireFox

■ 実際の症状
ダッシュボードのExUnit、VK Block、Lightning G3 Pro Unitの設定画面で、CSSとJavascriptファイルのURLが以下の例ように変換されてしまい、添付の画像のように表示が崩れます。ローカル環境（XAMPP）であることが原因かと思いますが、画像登録など一部の機能が正常に動作しません。

例
ローカルサーバでの現状のURL
DirC:LOCALhtdocsexample.comDirwp-contentplugins….vk_admin.css

正常に読み込まれると、下記のURLになると思われます。
http://example.com/Dir/wp-content/plugins&#8230;.vk_admin.css
ローカルサーバの本来のパスは下記の通りです。
C:LOCAL\htdocs\example.com\Dir\wp-content\plugins….vk_admin.css

現在判明している正常に読み込めていないファイルは、以下の３つです。
/wp-content/plugins/vk-all-in-one-expansion-unit/vendor/vektor-inc/vk-admin/src/assets/css/vk_admin.css
/wp-content/plugins/vk-all-in-one-expansion-unit/vendor/vektor-inc/vk-admin/src/assets/js/vk_admin.js
/wp-content/plugins/vk-blocks-pro/build/vk_blocks_options.css

**Comment by kurudrive** [comment]
@drill-lancer vk-admin の方は対応済みです。vk_blocks_options.css の読み込みの部分、記載内容としてはおかしくないように思うのですが、Windowsだと問題発生するのでしょうか？
月曜日で結構ですので確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
 Windows 版 XAMPP 8.1.17 環境では vk-admin の問題が解消されればコンソールエラーは出なくなりました。

**Comment by kurudrive** [comment]
@drill-lancer 確認ありがとうございます。

おや？ /wp-content/plugins/vk-blocks-pro/build/vk_blocks_options.css
は vk-admin をアップデートすれば直っちゃうという事？
vk-admin 関係なくない（・w・？

**Comment by drill-lancer** [comment]
解消したようなのでクローズします。
