### ISSUE TITLE
CSS分割読み込みを有効にしているときキーカラーが表示されない場合がある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1773]
Lightning でキーカラーを設定したブロックが、他のテーマに切り替えると色が付かない(→見えなくなる)場合がある。

- VK Blocks の設定でCSS分割読み込みを有効にしているとき
- 再現を確認しているブロックはいまのところ、アイコン、グリッドカラムカードの背景色
- VKボタンは正常、よってページ内にVKボタンがあるときは、VKボタンのCSSにデフォルト色が定義されているため見えなくなることはない

関連
https://github.com/vektor-inc/vk-blocks-pro/issues/1744

**Comment by mtdkei** [comment]
対応されているようでしたのでCloseします

**Comment by sysbird** [comment]
そういえば最近の #2223 もこれの関連ですね
ありがとうございます！
