### ISSUE TITLE
非表示設定がされているかどうか目印があるとうれしいです

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1774]
カスタムCSS になにか書いてあるよ、
段落に No wrap が設定されてるよ、みたいなかんじで、
このブロックでは非表示設定が使われてる目印があると便利と思います

![hidden](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/6b6666b2-3a9c-4b20-8af3-a58cea852ddc)

**Comment by kurudrive** [comment]
あー、うーん、該当コンテンツ薄くならないです？

**Comment by sysbird** [comment]
@kurudrive 
あら、たしかに！
わたし注意力なさすぎした
ありがとうございます、そっこう閉じますね
