### ISSUE TITLE
【翻訳待ち】[ タクソノミーリストブロック ] 存在しないtaxonomyを呼び出すとエラーになる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1787]
該当のタクソノミーが存在しません 的なメッセージを表示するように改修

https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/f6298d94-234e-4029-80a5-cffcfee73bd2

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。

- [ ] 公開画面側に、サイトエディタを編集する権限でログインしていたら「指定されたタクソノミーが存在しません。表示するタクソノミーの設定を確認するか、このブロックを削除してください。」のアラートメッセージを表示
- [ ] 編集画面側に出すアラートの装飾を他のブロックが表示するアラートと揃えてください

**Comment by drill-lancer** [comment]
マージされたので Close
