### ISSUE TITLE
【質問です】［目次ブロック］グループやOuterブロックの中に目次ブロックを設置した状態で見出しを追加すると、目次が追加されなくなるようです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1791]
グループやOuterブロックの中に目次ブロックを設置した状態で見出しを追加すると、目次が追加されなくなります。

目次ブロックをグループやOuterの外に出せば問題ないですが、これは不具合でしょうか？
もし可能でしたらグループやOuterの中に入っている状態でも、正常に動作するとうれしいです。
（スタイルを枠線無しにして、グループで囲って色などをつける方も多くいると思うので）

いったんAssigneesには開発者の皆様を入れさせていただきました。
一度、ご確認お願いいたします。

----追記-----

今気づいたのですが、グループブロックや黒背景ブロック内にある見出しブロックは、目次ブロックには表示されなかった気がするのですが、現状ではグループやOuter内の見出しも表示されるようでした。

![パターンチェック-Lightning-×-ExUnit-日本語デモ](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/e0dc4f9c-4543-4f1c-bf5b-707369117bcf)

**Comment by mthaichi** [comment]
これ対応します。

**Comment by mthaichi** [comment]
修正したのでCloseします。
