### ISSUE TITLE
アイコンブロックのアクセスビリティ

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1795]
https://vws.vektor-inc.co.jp/forums/topic/%e3%80%90%e6%a9%9f%e8%83%bd%e8%bf%bd%e5%8a%a0%e8%a6%81%e6%9c%9b%e3%80%91font-awesome-%e3%81%ae%e3%82%bf%e3%82%b0%e3%81%ab-aria-hiddentrue-%e3%81%8c%e8%87%aa%e5%8b%95%e3%81%a7%e8%bf%bd%e5%8a%a0#post-78838

どういう仕様が良いかご意見募集中です！

**Comment by mthaichi** [comment]
そのページで言及されているJSのように書き換えてもいいですし、こういうフィルターフックを書いてもいい気がします。

```
function add_aria_hidden_to_fontawesome($content) {

    if (strpos($content, 'aria-hidden="true"') !== false) {
        return $content;
    }

    $pattern = '/(<i [^>]*class=["\'][^"\']*fa[^"\']*["\'][^>]*)(>)/i';
    $replacement = '$1 aria-hidden="true"$2';
    $content = preg_replace($pattern, $replacement, $content);
    
    return $content;
}
add_filter('the_content', 'add_aria_hidden_to_fontawesome');

```

このコードでは対応していないですが、<p>FAX番号 <i class="fax">000-000-0000</i></p> という書き方は存在するんでしょうか。それでも正規表現で対応可能とは思います。

VK Blocksではなく、ExUnit の設定ON/OFFで上記のフックが発動する機能があってもよいのかも。
コピーするコードを書き換えるよりもフィルターフックでON/OFFできるほうが柔軟性はあると思います。

**Comment by kurudrive** [comment]
確か 6.2 か 6.3 で属性追加するフィルターがあったのでそれ使えないかな...

**Comment by sysbird** [comment]
フィルターフックいいかもしれないですね、
ExUnit で ON/OFF できたら、アイコンブロックだけでなく各テーマでの対応もいらなくなるんじゃないでしょうか

js のやり方はブラウザの音声機能に反映されるのかどうか？検証しないと分からないですね

**Comment by kurudrive** [comment]
これか

https://hackmd.io/UbKqOSBpRNaPPSGcXPU9Gw

今回のケースで使えるかどうかちゃんと見てないけど...

**Comment by mthaichi** [comment]
@kurudrive @sysbird これ、とりさんが言うように、ExUnitにあったほうがしっくりくると思います。
有効にすると、the_content  のフックにひっかける。でどうでしょうか。

**Comment by kurudrive** [comment]
@mthaichi はい。良いと思います！ (￣人￣)

**Comment by kurudrive** [comment]
デフォルトは on で良いのではないですかね？

**Comment by sysbird** [comment]
マージされたので閉じますよ
