### ISSUE TITLE
Grid Column Cardの中のGrid Column Card body内に画像ブロックを中央揃えで入れても中央によらない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1798]
Lightningテーマの場合は中央によりました
<s>Lightningはテーマ側でCSSをあてているようでしたので、X-T9にissueたてましたが、ブロック側でしたらすみません。。</s>

【追記】
[ブロック側の問題のようでした](https://github.com/vektor-inc/x-t9/pull/202)ので、こちらに移動しました

VK Grid Column Card body inner内にimageブロックを設置してalignを中央・左・右に設定しても、VK Grid Column Card body innerのdivにis-layout-flowのクラス名が付与されないので、画像の配置が効かないようでした。
調査をしていただいてもよろしいでしょうか。

Assigneesにはいったん開発者のメンバーの方々を入れさせていただきましたので、調査される方は他の方と被らないようにご自身のアイコンに変更お願いいたします。

----

### 管理画面
![投稿を編集-“オンライン英会話スクール_カスタムCSS”-‹-VK-パターンライブラリ-—-WordPress](https://github.com/vektor-inc/x-t9/assets/5525368/9001730b-272c-4cb4-8de7-2502f5d132a1)

### フロント画面
![check-x-t9](https://github.com/vektor-inc/x-t9/assets/5525368/f472bdb3-3495-4083-b7af-58669b8850e0)

**Comment by mthaichi** [comment]
これみてみます。

**Comment by mthaichi** [comment]
マージされたのでクローズします。
