### ISSUE TITLE
Outerブロックの背景の透過処理に問題があるっぽい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1800]
https://discord.com/channels/1086176580675584011/1145869010949373952/1145871340444856384

https://vws.vektor-inc.co.jp/forums/topic/vk-blocks-pro-outer-1-61-1-bg-opacity

■ こちらのプルリクの影響と思われる

https://github.com/vektor-inc/vk-blocks-pro/pull/1776

**Comment by kurudrive** [comment]
ベクトレトップで背景が薄くなっている症状を確認

https://training.vektor-inc.co.jp/

**Comment by sysbird** [comment]
調査中

**Comment by drill-lancer** [comment]
マージされたので Close
