### ISSUE TITLE
single term block が欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1808]
現状 VK 投稿リスト では ターム名と、そのタームに指定した色の背景で表示する事ができる。
これのブロック版

一番必要な機能はターム編集画面で指定した色がラベルの背景色として反映される事。

投稿には複数のタクソノミー、タームが割り振られているが、基本的に一つを表示する目的
タームに割り振られた色を取得して反映する必要があるので、
https://github.com/vektor-inc/vk-term-color
を使う事を想定しており、vk-term-color には既にそれ用のメソッドは存在しているので、動的ブロックで作るのであればわりと簡単ではないかと思う。

ただ、ラベルのpaddingを指定できるようにとか、角丸を指定できるようにとか、そうなってくると、vk-term-color の表示側メソッドを改修したり、そもそも全部つくりなおす必要がでてくると思う。

* ブロックでタクソノミーが指定してある場合はそのタクソノミーのタームを一つ表示する
* ブロックでタクソノミーが指定されてない場合は存在するタームを一つ表示すればOK

欲を言えば、
* 親または先祖階層のタームがある場合は先祖階層のターム名を表示する

オプションがあると嬉しい。

**Comment by mthaichi** [comment]
@kurudrive [add/single-term-block](https://github.com/vektor-inc/vk-blocks-pro/tree/add/single-term-block) ブランチに雑な試作をあげました。

- single term というブロック名です。
- ServerSideRender で PHP側でvk-term-colorのget_single_term_with_color()を使ってます。
- paddingだけ設定できるようにしました。

私が以下感じたことです。

- WordPress的にServerSideRenderはあくまでフォールバック（クライアントサイドレンダリングができない場合や、特定の状況下での代替手段として使用される）なので、paddingや角丸などのスタイルを設定させる場合はクライアントサイドレンダリングかなと思います。
- ブロックのコンテナはdivタグのようなブロック要素であるべきと認識していますが、vk-term-colorのget_single_term_with_colorが吐き出すHTMLはspanタグなので、そのままだと扱いづらいです。
- というわけで、HTMLの組み立てはブロック側に任せるのがよいのかなと思いました。vk-term-colorに 色とテキストとリンク先を配列で返すようなメソッドを追加すると今後便利かなと思いました。
- コアの post-term ブロックは結構参考になるのかも。

**Comment by kurudrive** [comment]
@mthaichi ありがとうございます（・ｗ・

> vk-term-colorに 色とテキストとリンク先を配列で返すようなメソッドを追加すると今後便利かなと思いました。

ではその方向で (￣人￣)

**Comment by mthaichi** [comment]
#1874

@kurudrive  プロトタイプを一度見て頂いて、ご意見頂けますか。「Single Term」でブロック入れられます。
仕様的にはNew Badgeに寄せています。

**Comment by mthaichi** [comment]
@kurudrive テキスト色について相談です。

当初リリース時は、テキスト色を指定させずに、固定としたいです。
そこで、背景色にかなり明るい色が選ばれた場合、自動的にテキスト色が黒に設定されるようにしようと考えています。

今後のアップデート or 余裕があれば、テキスト色をユーザーが指定できるように考えています。
その場合、本ブロックではなく、VKTermColor側つまり従来のターム色指定画面で、テキスト色も選べるようになればいいのかなと。指定しない場合は「自動」扱いにすると良いと思います。

さらに将来的には本ブロック側で直接ターム色を変更できないかなと考えています。

上記についてご意見頂けますでしょうか。（他の方のご意見も歓迎です）

**Comment by kurudrive** [comment]
@mthaichi あー、たしかに文字色指定されると背景色がカテゴリーによって濃かったり薄かったりすると都合悪いですね。

**Comment by goutetsuguma** [comment]
@mthaichi 
CC @kurudrive 
SVGアイコンいれましたのでご確認お願いいたします🙏

**Comment by mthaichi** [comment]
> @mthaichi CC @kurudrive SVGアイコンいれましたのでご確認お願いいたします🙏

@goutetsuguma 確認しました。ありがとうございます！

**Comment by mthaichi** [comment]
@kurudrive 「Single Term」 が正式名でよいですかね。
日本語名どうしましょう・・・。
「単一分類」かそのまんま「シングルターム」にするかと考えていますが。

**Comment by goutetsuguma** [comment]
@mthaichi 
実装ありがとうございます！試してみました！
NEWブロックの様に、テキストが中央寄せだと良いと思いました。（横並びブロックに入れなかった場合に左寄せになってしまうので）

**Comment by kurudrive** [comment]
@mthaichi 日本語名迷いますなぁ...
それがあるからコアはタクソノミーがそのままついてるのかもしれないですなぁ...
「単一分類」「シングルターム」だと知っている人しかたどり着けないと思うので、
「単一カテゴリー&カスタム分類」 ... 長い...長すぎる...

めちゃめちゃ仕様がひっくり返って今月無理になりますけど、コアみたいに存在するタクソノミー毎のバリエーションブロックとして自動生成...の方がユーザー的に使いやすいですかねぇ...？

あと、１点、文字の改行を禁止指定で良いのかなと思いました。

**Comment by mthaichi** [comment]
memo:  相談の結果、名称は「Category Badge（カテゴリーバッジ）」にすることに。
nameは post-category-badge にします。

**Comment by mthaichi** [comment]
> @mthaichi 実装ありがとうございます！試してみました！ NEWブロックの様に、テキストが中央寄せだと良いと思いました。（横並びブロックに入れなかった場合に左寄せになってしまうので）

@goutetsuguma 重要なご指摘、ありがとうございます。そうですよね。
テキストアラインメント指定できるようにし、初期centerという形に修正させていただきました。

**Comment by mthaichi** [comment]
> あと、１点、文字の改行を禁止指定で良いのかなと思いました。

@kurudrive  ありがとうございます。
CSSで white-space: nowrap; を指定してみましたが、意味合いが違ってたらご指摘ください。

**Comment by ChiakiKouno** [comment]
少し触らせていただきました。いい感じです！迷わずに使えております！◎

@mthaichi @goutetsuguma 
１点確認です。
私の環境ですと、 VK Blocks の設定ページで、アイコンの赤い部分だけが表示されており、黒い部分が見えませんでした。ご確認いただければと思いますmm
![Screenshot 2023-12-15 at 1 22 47 PM](https://github.com/vektor-inc/vk-blocks-pro/assets/43702482/02e00bfb-4263-400c-accb-94ff81d2a925)

**Comment by mthaichi** [comment]
> @mthaichi @goutetsuguma １点確認です。 私の環境ですと、 VK Blocks の設定ページで、アイコンの赤い部分だけが表示

@ChiakiKouno ありがとうございます！  私の環境でも確認できました。

@goutetsuguma SVGの最初の `<svg xmlns="http://www.w3.org/2000/svg" width="25" height="24" fill="none">`  の `fill="none"` がついていたので、これを削除したら良い感じになりましたので、これでよいかな・・・と。でもくのうさんの方で修正いただいたほうがいいのかな。

ブランチを変えましたので、もし元データ修正されたいようでしたら、SVGデータ送っていただければと思います🙏

**Comment by goutetsuguma** [comment]
> SVGの最初の <svg xmlns="http://www.w3.org/2000/svg" width="25" height="24" fill="none"> の fill="none" がついていたので、これを削除したら良い感じになりましたので、これでよいかな・・・と。でもくのうさんの方で修正いただいたほうがいいのかな。

はい！それであってますー！

> ブランチを変えましたので、もし元データ修正されたいようでしたら、SVGデータ送っていただければと思います🙏

あ、ブランチを変えられたのですね！
先ほど https://github.com/vektor-inc/vk-blocks-pro/pull/1874　のブランチにアイコンをプッシュしてしまいました。。
