### ISSUE TITLE
【確認待ち】無料版のデプロイがコケる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1814]
確認よろしくお願いいたします (￣人￣)

https://github.com/vektor-inc/vk-blocks-pro/actions/runs/6320155962

**Comment by drill-lancer** [comment]
@kurudrive 
これ解決するには node.js を 16 以上にあげる必要がありそうです。

**Comment by drill-lancer** [comment]
解決したようなので Close
