### ISSUE TITLE
[ Outer ] 特定の設定で再利用ブロック化ができなくなるっぽい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1823]
https://vws.vektor-inc.co.jp/forums/topic/outer-reuse-convert-error

> 同じコンテンツを再作成しながら各ステップで保存を繰り返したところ、親カラムの「上下パディング」を0pxに設定すると不具合が再現（保存不可になりました）できました。
> 「マージン」または「ブロックの間隔」のいずれかの上下の値を0pxにしても再現しました。
> 添付ご確認ください。

<img width="1884" alt="530f364cfc459dc6c02965774bf2fe6f" src="https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/a410af69-8ba5-42a4-be1a-e9598740a88c">

**Comment by drill-lancer** [comment]
僕の環境では発生しなかったので抜けます。

**Comment by kurudrive** [comment]
> Outerをタップ
> Outer内の＋ボタンをタップ
> カラムをタップ
> 66/33カラムを選択
> 親カラムのカラム数を３に変更
> 真ん中と右のカラム幅を100pxに修正
> 左のカラム幅を空欄に修正
> （この時点でカラムの幅は左から「指定なし」「100px」「100px」です）
> 親カラムの「上下パディング」を0pxに設定する

https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/feb8d2b1-5709-4399-adf5-bb22202592bb

再利用に登録されない不具合再現せず

**Comment by kurudrive** [comment]
padding 0数値入力テスト版

https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/2d0bb879-ea7b-478e-b628-054136bfabd0

**Comment by kurudrive** [comment]
再現しないので一旦 close
