### ISSUE TITLE
[Outer] 区切りデバイスごとの設定で縦幅も考慮してもらえるとうれしい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1824]
【機能追加要望】［Outer］区切りの設定（傾斜、カーブ、波線、三角）機能が、PCとスマホで別で設定できると嬉しいかもしれない #1623 
 を対応していただきながら、要望ばかりで恐縮です
 
 区切り三角でデバイスごとの設定を行うと以下のようになります
 モバイルで三角は小さくなるものの縦幅がPCと同じなので、コンテンツの下余白が余分に空いてしまう見た目になります。
 モバイルのとき、小さい三角だけにするって難しいでしょうか？

![pc](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/df81ab64-ebc1-4552-8885-a3b2cbf7252b)

**Comment by osmdik** [comment]
@sysbird 
おそらく、三角を小さくするとそれに合わせてpaddingも小さくなる仕様だと思いますが、端末毎の設定を実装した際に、その箇所の処理に不備がありました。
取り急ぎその箇所の修正をしましたので、確認をお願いします

**Comment by sysbird** [comment]
マージされたので閉じます
対応ありがとうございました！
