### ISSUE TITLE
吹き出しブロックで英単語が単語の途中で改行されるのを改善したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1825]
https://vws.vektor-inc.co.jp/forums/topic/balloon-text-wrap

**Comment by osmdik** [comment]
https://github.com/vektor-inc/vk-blocks-pro/blob/56398fb3ac038ba4906fe2db5b3b5eb7d5b7a834/src/blocks/balloon/style.scss#L12C25-L12C25

https://developer.mozilla.org/ja/docs/Web/CSS/word-break

`word-break: break-word;` が適切かと思いますがいかがでしょうか？

**Comment by goutetsuguma** [comment]
@kurudrive @osmdik 


おおしまさん、調査ありがとうございます！

> [break-all](https://developer.mozilla.org/ja/docs/Web/CSS/word-break#break-all)
> CJK (中国語、台湾語、日本語、韓国語) 以外のテキストにおいて、単語中などでの文字の改行に関する禁則処理を解除し、どの文字の間でも改行するようにします。
> 
> [keep-all](https://developer.mozilla.org/ja/docs/Web/CSS/word-break#keep-all)
> CJK テキストの改行を許可しません。 CJK 以外のテキストについては normal と同じ挙動となります。

今までがbreak-all でしたので、keep-allにすると、以下の画像のように日本語も改行が許可されなくなるので、
ちょっと違和感がある人が出てきそうです。


![固定ページを編集-“フロントページ”-‹-サイトタイトル-—-WordPress (4)](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/4e632ef5-9615-48bd-8a97-1712d6e056a0)

この改行のword-break: break-all;　を入れたのは、おそらく日本語の時の表示を考えて入れたのかな、、？（どうなのかな）
と思われますので、ここでは`word-break: break-all;`の表記を削除してしまうのはどうでしょうか？

ちょっとword-break: break-all;を入れた理由が思い出せませんので、、相談です🙇

**Comment by osmdik** [comment]
@goutetsuguma 
確認ありがとうございます。
確か違和感がありますね。
デフォルトがnormalで適切だと思うので`word-break: break-all;`が追加された理由によってはスタイルを削除しても良いと思います。

**Comment by goutetsuguma** [comment]
返信ありがとうございます！
いったん削除する方向でいきましょうか。削除するだけなので、私の方で作業しようかなと思います🙇
調査などありがとうございます > <

**Comment by osmdik** [comment]
@goutetsuguma 
承知しました。
すでにPR作ってしまっているので、確認をお願いします。
https://github.com/vektor-inc/vk-blocks-pro/pull/1828

**Comment by goutetsuguma** [comment]
@osmdik 
あ！今見てたらプルリク出していただいていますね！ではおおしまさんにお願いしても良いでしょうか🙇
よろしくお願いします！

**Comment by osmdik** [comment]
リリース済のためClose
