### ISSUE TITLE
[ グリッドカラムカード ] 枠線の処理をコアの機能を使うように変更したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1829]
昔は枠線の機能がなかったので独自実装になっているが、コアの枠線処理が使えるようになってると思うのでそれを使えないか？

**Comment by osmdik** [comment]
コアの枠線処理というのは、block.jsonのsupportsのことでしょうか？
```json
"supports": {
		"__experimentalBorder": {
			"color": true,
			"radius": true,
			"style": true,
			"width": true,
			"__experimentalDefaultControls": {
				"color": true,
				"radius": true,
				"style": true,
				"width": true
			}
		}
	},
```

**Comment by kurudrive** [comment]
@osmdik そうそう。

ただ、このブロック親子間でデータの受け渡しもあるからちょっと面倒だとは思います（・ｗ・；

**Comment by osmdik** [comment]
@kurudrive 

> このブロック親子間でデータの受け渡しもあるからちょっと面倒

ちょっと試してみます。

**Comment by osmdik** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1820

**Comment by kurudrive** [comment]
@osmdik これどこで止まってたんだっけ？
確か僕が何か確認するよーって言って確認できてなかったように記憶してるけど、具体的に何だったかなと...。

cc: @mthaichi

**Comment by osmdik** [comment]
@kurudrive cc: @mthaichi 
コアの枠線処理は、ブロック単体に対するものでしたが、今のグリッドカラムカードは親子間と子同士でも同期できる仕様になっているため、supportsで設定した値がうまく同期されず躓いていたのだと思います。

**Comment by mthaichi** [comment]
@kurudrive @osmdik  
これに関しては、独自実装のままで良いと私は思います。
新規開発のブロックはブロックサポートを使うべきですが、昔のブロックを無理にブロックサポート対応させるのは慎重になったほうがいいのではないでしょうか。

ブロックサポートを使うのであれば、スタイルに関する処理は全部ブロックサポートに任せるべきで、一つのブロックの中で、背景色は独自実装、枠線はブロックサポート・・・というのはあまり良くないと感じますが、いかがでしょうか。

**Comment by kurudrive** [comment]
@mthaichi なるほど、確認ありがとうございます！
