### ISSUE TITLE
[吹き出し] 入力した文字数によって吹き出しの幅が変化するといいな

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1836]
Facebook のコメント欄がそうなってて、急にいいなと思いました
文字が少ないと吹き出しも小さいのです
改行が発生するときに初めて100%になるみたいです

**Comment by kurudrive** [comment]
@sysbird おや？こうじゃなくて？

![スクリーンショット 2023-10-20 0 38 02](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/d81fc844-2d49-4ec5-a720-f206be4f1fcb)

**Comment by sysbird** [comment]
あらやーね、そうでした
