### ISSUE TITLE
[ ダイナミックテキスト ] 親ページのタイトル も欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1837]
現状 先祖階層 があるが、親ページのタイトル を表示したい場合があるので追加して欲しいです

**Comment by osmdik** [comment]
@kurudrive 
先祖改装ページのオプション同様、親ページのないページで非表示にするオプションもあったほうが良いでしょうか？

**Comment by kurudrive** [comment]
@osmdik あんまり必要ないかなと思いつつ、まぁ必要な場面もありそうだし先祖階層でついてるなら合わせた感じにしておきましょう（・ｗ・

**Comment by osmdik** [comment]
リリース済のためclose
