### ISSUE TITLE
［グリッドカラム］【Discordより】グリッドカラム内にリストマーク有りのリストブロックを配置すると、編集画面でリストマークがズレてしまう

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1842]
[グリッドカラム内にリストマーク有りのリストブロックを配置するとズレてしまう](https://discord.com/channels/1086176580675584011/1166649897940951070/1166649897940951070)

![固定ページを編集-“余白の確認”-‹-サイトタイトル-—-WordPress](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/522f2876-40d2-4740-8b74-420017c34a52)

**Comment by osmdik** [comment]
https://github.com/vektor-inc/vk-blocks-pro/blob/c4962929015ef896da01fe3a6414c6d96f227661/editor-css/_editor_before_grid-column.scss#L15C18-L15C18

`display: unset;` を削除または`block`にすると解決すると思います。

以前の下記のプルリクで追加された意図にもよると思いますが、いかがでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/pull/408

**Comment by goutetsuguma** [comment]
@osmdik さん調査ありがとうございます！！！

> 以前の下記のプルリクで追加された意図にもよると思いますが、いかがでしょうか？

今確認していましたが、、なぜ `display:unset;` したのかが思い出せませんでした。

display: unset; は削除しても問題なさそうでしたので削除の方で良いとおもいます🙇

よろしくお願いします🙇

**Comment by sysbird** [comment]
対応マージされたので閉じます、ありがとうございます！
