### ISSUE TITLE
【確認待ち】[ スライダーアイテム ] container がある都合上余白が０にできないので、padding 指定が出来るようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1845]
![スクリーンショット 2023-11-01 0 02 31](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/fc759f4f-9aeb-4e87-9905-26f15996f9bb)

背景画像指定ではなく画像ブロックを配置した場合に bootstrap が contaiter に padding 15px をつけてしまい、スライド間の間隔が指定できないため。
コアのpadding指定機能使えないかな？

**Comment by drill-lancer** [comment]
やります。

**Comment by drill-lancer** [comment]
@kurudrive 
無理にコアが使っているコンポーネントを使うより
（そもそも多分外部の人間が使うことは想定されていない作りなので）
公式が簡単に使えるように手配したコンポーネントを使ったほうが
メンテナンス性が高いと思うのであえてコアには合わせません。

**Comment by kurudrive** [comment]
@drill-lancer 

```
	"supports": {
		"spacing": {
			"padding": true
		},
	}
```

は使えないの？

**Comment by drill-lancer** [comment]
@kurudrive 
それはブロックの一番外側のみ使えます。

それやるなら Slider Item ブロックの中に Slider Item Container ブロックを作る必要があります。

**Comment by kurudrive** [comment]
@drill-lancer あーそうか、外じゃないか。なるほど（・ｗ・
一応コアのカラムブロックとかの実装方法確認した上で良きに計らって実装してくださいー (￣人￣)

**Comment by drill-lancer** [comment]
@kurudrive 
Slider Item ブロックの中に Slider Item Container ブロックを作れば
Slider Item Container に対して下記は使用可能です。
```
	"supports": {
		"spacing": {
			"padding": true
		},
	}
```

Slider Item  の中に Slider Item Container を 新 FAQ の中のブロックのようにロックしてしまえば
ブロックの構造が変わりはしますが使用感はそう変わらないように思えます。

**Comment by kurudrive** [comment]
@drill-lancer そうねー、一回ちょっとやってみて貰えます（・ｗ・？

**Comment by drill-lancer** [comment]
@kurudrive 
とりあえずそれっぽく実装してみました。

**Comment by kurudrive** [comment]
@drill-lancer 実装ありがとうございました。

確認したところ、FAQブロックと違って Slide Item ブロック自体に余白指定機能が存在し（！）その中に Slide Item Container に余白となると、使用感として混乱するなと思いました。

と...言いますか...申し訳ありません。
ジャンピング土下座案件でした。

そもそも余白を無くす設定は普通にありました。

![スクリーンショット 2023-11-01 0 02 31](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/e0dc4397-912e-47be-b55f-91c64c0632a5)

本件問題としていた「画像ブロックを配置して、複数スライドにした場合に余白の制御ができない」ですが、「余白を無くす」指定ができたため、ここから先は更に余白をつけたい場合はユーザーがグループブロックを配置してそこでpadding指定をすれば事足りる状態でした。

つまるところ現行機能・仕様で問題ありませんでした。
