### ISSUE TITLE
[ボタン] ボタンの位置「幅広」が「ブロック」よりも大きくなってしまうことがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1858]
tt系テーマはコンテンツ幅が狭いので、 ボタンの位置「幅広」が「ブロック」よりも大きくなりコンテンツ幅よりはみ出てしまいます
対応は難しいでしょうか？
発生してる例 [法律事務所 費用について](https://patterns.vektor-inc.co.jp/vk-patterns/law_fee/) tt系テーマの場合

**Comment by kurudrive** [comment]
|￣ー￣）.oO（ とりさんの方で対応していただいてもええんですよー ）

**Comment by sysbird** [comment]
あれ…tt系ではこれ正しい動きな気がしてきました
