### ISSUE TITLE
WordPress 6.4 で書式設定のツールバーのアイコンが大きくなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1859]
https://vws.vektor-inc.co.jp/forums/topic/wordpress-6-4-%e3%81%ab%e3%81%97%e3%81%9f%e3%82%89%e3%82%ab%e3%82%b9%e3%82%bf%e3%83%a0%e6%9b%b8%e5%bc%8f%e8%a8%ad%e5%ae%9a%e3%81%ae%e3%83%84%e3%83%bc%e3%83%ab%e3%83%90%e3%83%bc%e3%81%ae%e3%82%a2

こちらは直したけどカスタム書式のは直していないと思うのでissueにします
https://github.com/vektor-inc/vk-blocks-pro/issues/1852

**Comment by kurudrive** [comment]
close as completed
