### ISSUE TITLE
[ 横並びアイコン ] 間隔を指定できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1862]
* アイコンの余白だと上下にも余白がついてしまう
* アイコンの余白だと一番左・右にも余白がついてしまう

**Comment by mthaichi** [comment]
@kurudrive 「アイコンの余白」というのはどこの設定を指してますか？
「アイコン」ブロックの設定に余白設定は見当たらないもので・・・。

**Comment by kurudrive** [comment]
@mthaichi 横並びアイコンブロックの方ですー。
が...まぁ横並びアイコンブロックじゃなくてもコアのグループブロックの横並びでブロックの間隔つければよくね？という説もあるので優先ではない感じです😑

**Comment by sysbird** [comment]
アイコンのサイズの下に、余白設定があります
いまのところ、この値が上下左右に付く仕様です
私もパターンでは、コアのグループブロックの横並びを使ってますね
![ico](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/f85c70f3-84e4-4d43-8016-022a1b088c98)

**Comment by kurudrive** [comment]
現状アイコンサイズ内の余白ではなくて アイコンブロック同士の余白（間隔）指定がないのですが、
先述の通りグループの横並び使ってるので優先度は低いです
