### ISSUE TITLE
【機能追加要望】［グリッドカラムカードブロック］背景色でグラデーションがきたら嬉しいですが難しいでしょうか（現在は単色のみ）。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1863]
グリッドカラムカードブロックの背景色でグラデーションがきたら嬉しいですが難しいでしょうか。
コアのカラムブロックを使えば良いのですが、角丸やリンクなど、なにかと便利なグリッドカラムカードブロックでグラデーションができると大変嬉しいのでissue化しました。
仕様的に無理な場合はCloseしてください🙏

Assigneesにはいったん、開発メンバーを入れさせていただきました。

**Comment by mthaichi** [comment]
調査中

**Comment by mthaichi** [comment]
@goutetsuguma  #1867 をビルドして試して頂けますか？  こんな感じでイメージ通りでしょうか。

**Comment by goutetsuguma** [comment]
ありがとうございます！！！イメージ通りです！

ちょっと気になるところは、「編集ロック」をかけた場合は問題ないのですが、全てのカラム共通で背景色をグラデーションにした場合に、フロント画面を見てから編集画面に戻ると、背景のグラデーションがリセットされてしまう様でした。

[Uploading 固定ページを編集-“LP”-‹-サイトタイトル-—-WordPress.webm…]()

**Comment by sysbird** [comment]
@mthaichi 
私も使ってみました
ありがとうございます、便利です！
おしゃれなグリッドカラムカードが作れるようになりますね

私の環境では再編集しようとすると、ブロック全体が白く(なにも見えなく)なってしまいます
たぶんこれから deprecated の処理とかするためでしょうかね

**Comment by mthaichi** [comment]
@goutetsuguma @sysbird ご確認ありがとうございます！
では、この方向で調整していきます。ご指摘の不具合も修正します。🙏
