### ISSUE TITLE
【機能追加要望】アコーディオンブロックの「スタイル」に「装飾なし」が欲しい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1864]
自由にグループで囲ったりして、枠線や背景色などの装飾をつけたい人が増えてくると思いますので、「装飾なし」のスタイルが欲しいです。パターンを作っていてcssで打ち消すことが多いのでissue化させていただきました。

-----

![スクリーンショット 2023-11-15 13 46 01](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/4b361922-5b65-44c9-9c17-ed212f416d6c)

**Comment by kurudrive** [comment]
装飾なし を追加してくれてええんやで（・ｗ・
