### ISSUE TITLE
[ グリッドカラムカード ] body の上下指定ができなくなっているのを直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1865]
![スクリーンショット 2023-11-15 14 39 39](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/4f17ca3d-1c02-4470-8cac-bca12a9a9201)

↑ タイトルや文章が上下中央揃えになってしまっていて、揃わない

っていうか... edit.js には上下指定のツールバーを追加するための記述ががあるので昔はできたのでは？
いつの間にか上下位置指定のツールバーが出なくなってこの問題が発生するようになった空気を感じます。

**Comment by kurudrive** [comment]
@drill-lancer さらっと見た限りuseInnerBlocksProps にした理由が特別コメントに書いてあるわけでもないので、変更しても良いのではないでしょうか？
ただし、実際に問題が発生しないかどうかはわからないので変更してみてから確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer ↓ の修正が進行中なのでご注意くださいー（・ｗ・
https://github.com/vektor-inc/vk-blocks-pro/pull/1867

**Comment by mthaichi** [comment]
@drill-lancer @kurudrive  これは修正済みですよね？

**Comment by kurudrive** [comment]
@mthaichi はい！ありがとうございます！
