### ISSUE TITLE
[ アコーディオンブロック ] PCとSPでデフォルトの開閉設定を分けられると嬉しい（Xより）

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#1866]
> WordPressテーマに実装されてるアコーディオンブロック、できればPCとSPでデフォルトの開閉設定を分けられるといいな。

https://twitter.com/17work_kengot/status/1724701798492250201

**Comment by mtdkei** [comment]
マージされましたのでCloseします
