### ISSUE TITLE
[アニメーション]全幅ギャラリーが全幅で表示されない(tt4)

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1868]
全幅ギャラリーをアニメーションのなかに入れると、全幅で表示されなくなります
ただし
- tt3
- tt4
の場合ですので、テーマが原因かもしれませんね

**Comment by kurudrive** [comment]
テーマの仕様だと思います。デフォルトテーマではコンテンツ幅指定の中の要素はコンテンツ幅を越えて全幅にはならないようになってると思います。
このタイプの不具合は CSS がどう影響してるかを確認したり、他のブロックでの動作を確認（通常幅のグループブロックに全幅ギャラリーを入れるなど）て VK Blocks Pro の CSS に起因する問題かどうかを判別してください。

**Comment by sysbird** [comment]
@kurudrive 
そうですね、ありがとうございます
パターンでなるべく tt4対応をしているので残念ですけど、回避策をかんがえつつ本件はクローズします

**Comment by kurudrive** [comment]
@sysbird tt4 はやっぱりパターン自体わけないと厳しいかなーという印象デス（＝ｗ＝；
