### ISSUE TITLE
[ グリッドカラムカード ] 編集モードのデフォルト値を変えた方が、わかりやすいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1871]
https://github.com/vektor-inc/vk-blocks-pro/pull/1867#issuecomment-1839817162

↑issueをたてさせていただきました🙇‍♀️

デフォルトで編集モードが「このカラムのみ」で、「編集ロック」はオフですので、グリッドカラムカードアイテムを編集して次のカラムにいこうとすると、編集画面でリセットされます。使い慣れてしまえば良いのですが、編集モードのデフォルト値を「すべてのカラム」にすると良いのかなと思いましたがいかがでしょうか？

それとも、もっと他にアイディアがありましたらよろしくお願いいたします🙇‍♀️

**Comment by sysbird** [comment]
編集モードのデフォルト値を「すべてのカラム」がよいと思います

**Comment by kurudrive** [comment]
そもそも 「このカラムのみ」= 「編集ロック」じゃない理由は何なんでしょうね...作ったの僕ですけど...

**Comment by sysbird** [comment]
マージされたので閉じます
