### ISSUE TITLE
［グリッドカラムカード］カラムブロックの様な垂直配置を選択できる機能がほしいです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1875]
インナーブロックのテキスト量によって、見た目が悪くなってしまうので（添付画像参照）、カラムブロックにある様な垂直配置を選択できる機能が欲しいなと思いました。
難しそうでしょうか。

一旦開発メンバーの方々をAssigneesにいれました🙇‍♀️

----
![LP-サイトタイトル](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/adbbe26d-1878-49fd-9540-72cbcf26eab1)
----
![スクリーンショット 2023-12-06 9 20 54](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/dc761d3b-3bc1-4b71-b16a-c7f29db27594)

**Comment by kurudrive** [comment]
|・ｗ・）つ「 https://github.com/vektor-inc/vk-blocks-pro/issues/1865 」

**Comment by mtdkei** [comment]
グリッドカラムカードアイテムボディで垂直配置が選択できるようになってたのでCloseします。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/f89de3e7-2162-4d11-807c-954e32645398)
