### ISSUE TITLE
[ ダイナミックテキストブロック ] ログイン中のユーザー名を表示できるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1879]
ついでに「前に表示する文字」と「後に表示する文字」も指定できるようにしたい

例）
こんにちは べくたろう さん

ができるように

**Comment by mthaichi** [comment]
これちょっとみてます。

**Comment by mthaichi** [comment]
@kurudrive ログインしていない時は非表示で良いですか？  ログインしていない時のテキストも指定させますか？
