### ISSUE TITLE
VK 見出しブロックを非推奨にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1880]
アイコン部分もコアの横並びブロックでできるようになって独自性がないので非推奨でいいかなと。

**Comment by mthaichi** [comment]
@kurudrive 相談ですが、すべての非推奨ブロック名のラベルに（非推奨）をつけたいです。
今はPRブロックだけについていますが、他の非推奨ブロックにも（非推奨）とラベルにつけたいです。

DBにvk_blocks_optionsが設定されているユーザーは、設定画面で非表示にしない限り、非推奨のブロックも表示され続けるようですので、判別するためにもラベルだけで区別できるようにしたいです。（新規インストール時のユーザーは非表示になります。設定を始めて保存した時に非推奨のブロックが非表示になります）

また、見出しブロックは、コアの見出しブロックと混同しやすいので判別しやすくするためにもラベルを変えたいです。

上記、問題がなければ、とりあえず、見出しブロックを対応して、その後別ブランチで他ブロックも対応します。

**Comment by kurudrive** [comment]
@mthaichi はいー。良いと思いますっす（・ｗ・ｂ
