### ISSUE TITLE
[ 枠線ボックス ] 編集画面でデザインが崩れてるので修正したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1890]

**Comment by goutetsuguma** [comment]
着手しようかなと思い、Lightning、X-T9テーマで枠線ボックスをおいて編集画面でみたのですが、そこまで崩れている様な感じではなかったのですが、どうでしょうか？私の環境のせいかな、、？石川さんの環境だとくずれていますか？
![固定ページを編集-‹-サイトタイトル-—-WordPress](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/e9753607-4460-4162-99c0-8ddefef1ef00)
