### ISSUE TITLE
[ 非表示機能 ] カスタムCSSのように横にVKマークが欲しい&設定が入っている場合にロゴがアクティブの状態（背景黒塗り）になってほしい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1894]
VK Blocksの機能なので、カスタムCSSと同じ様にVKマークが欲しいのと設定が入っているときにアクティブの状態（背景黒塗り）になって欲しいです。

【なぜ欲しいと思ったのか】
パターンのレビューしている時に、石川さんがちらっとこの意見をいっていましたが、非表示設定したブロックは半透明になるからわかるかな？ということで一旦そのままになりましたが、やっぱりブロックが入れ子になっているときに探すのに若干手間がかかるため、VKマークが欲しいなと思いissueをたてました🙇‍♀️

いったんAddigneesには開発者メンバーを入れさせていただきました
調査&作業する際はご自身のアイコンにするなどして、作業がかぶらないよううにお願いいたします🙇‍♀️

**Comment by sysbird** [comment]
私も最近思ってました〜
非表示設定したブロックは半透明になるからわかるかな？って言ってたですが、スペーサーはわからないんですね
スペーサー非表示にするのが邪道かもしれないんですけど
やっぱりアクティブの状態はわかったほうが嬉しいです
