### ISSUE TITLE
【機能追加要望】［Outer］最小の高さが入れられると使いやすいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1904]
Outerを使用する場合はレスポンシブスペーサーで高さを調整しますが、カバーブロックの様に最小の高さが入れられると便利そうだなと思いましたがどうでしょうか。

パターンを作っていて、Outerブロックのインナーに背景画像しか設定してない場合レスポンシブスペーサーを入れますが、高さの調整をレスポンシブスペーサーで調整しているということがユーザーには分かりずらいなと思ったためです

難しそうであればCloseしてください
（単位の種類、レスポンシブスペーサーと同じ単位にできるのでしょうか、、？）

Assigneesには開発者のメンバーの方々を入れさせていただきました。
ご意見などいただけると嬉しいです

**Comment by mtdkei** [comment]
プルリクがマージさましたのでCloseにします
