### ISSUE TITLE
画像ブロックで「フォトフレーム傾き」と「クリックで拡大」を組み合わせた時の挙動について

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1907]
画像ブロックで以下の組み合わせの際に起こる現象を確認しました。

## 現象発生時の画像ブロックの設定
- 設定で「クリックで拡大」
- スタイルで「フォトフレーム傾き右」もしくは「フォトフレーム傾き左」

##  issue現象
フロントエンドで上記の設定が施された画像をクリックすると、画像の一部が欠けてしまいます。
画像が欠けない状態で拡大されるようにしていただければと思います。
![image](https://github.com/vektor-inc/vk-blocks/assets/21466284/e06f0647-e918-4825-8f35-4b447df8bd33)

## 画像設定〜現象発生時のGif動画
![4eqhh-ctkhy](https://github.com/vektor-inc/vk-blocks/assets/21466284/04a3c781-f446-48ae-a715-d7470d1e32c6)

## 確認したこと
- Lightning、X-T9、TT4、TT3で上記の現象を確認しました。
- 「フォトフレーム傾き右」もしくは「フォトフレーム傾き左」以外のスタイルでissueの現象は発生しませんでした。

以上となります。他に確認する項目がありましたらご連絡ください。
お手数ですがご確認のほどよろしくお願い致します。

**Comment by goutetsuguma** [comment]
MargeされたのでCloseします
