### ISSUE TITLE
 【機能追加要望】［投稿リスト］［クエリループ］表示順で「よく読まれてる順」があったら嬉しいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1909]
投稿リストかクエリループで記事を表示するときに、表示順で「よく読まれてる順」に並び替えられたら嬉しいです。
マガジンサイトやポータルサイトのパターンブロックを考えてまして、こちらの機能があったらより色んな種類のパターンが作れると思うのでどうぞご検討ください！

**Comment by kurudrive** [comment]
* カテゴリー「よく読まれてる記事」など運用でカバー可能
* 独自実装はDBに専用テーブル作ってごにょごにょしないといけないので開発リソース的に難しいっす (￣人￣)
