### ISSUE TITLE
[ スライダーブロック ] プレビューモードで高さを検出するようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1916]
今までは縦積みモードだったので、できるだけコンパクトにするために高さ検出をしていなかったが、
プレビューモードでは上下余白があいてしまって変なので、編集画面でも指定の高さになるようにしたい。

https://patterns.vektor-inc.co.jp/vk-patterns/top-slider/

---

余談 :  ↑ のパターンで中の要素が上下中央にならないので、パターンの問題なのかブロックの問題なのか要確認

**Comment by goutetsuguma** [comment]
> 余談ですが ↑ のパターンで中の要素が上下中央にならないので、パターンの問題なのかブロックの問題なのか要確認

VK パターンライブラリのheight:100%;が原因の様でしたので、VK patternsのほうにissueをあげておきます

```
// iframe 内の最大高さがコンテンツの高さになってしまい、ヘッダーサブメニューなどを展開しても切れてしまう不具合を修正
html,
.container  {
	height:100%;
	overflow: visible;
}
```

https://github.com/vektor-inc/vk-patterns/blob/245b74a81bf54c4009ae2c90a3f2e4ec2ee3620e/assets/src/scss/iframe.scss#L18-L23
