### ISSUE TITLE
コアの一部のブロックにVK Blocksの「ブロックの余白」がつかないものばありますが、つくようになると嬉しいです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1919]
例えば以下のブロックです。他にもあるかもしれません
いったん開発者メンバーをAssigneesに入れさせていただきますが、難しそうであればCloseしてください🙇

- サイトのキャッチフレーズ
- サイトロゴ
- サイトのタイトル

追加
- ソーシャルアイコン

**Comment by mtdkei** [comment]
同意です！
また可能なら、同じくコアの「ソーシャルアイコン」ブロックも余白がつくようになると嬉しいです。

**Comment by kurudrive** [comment]
ある程度ついたので一旦close
