### ISSUE TITLE
コアブロック「タイトル」の見出しデザインを変更できるようにしたいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1920]
クエリループで新着投稿を作る時に「タイトル」の見出しデザインを、見出しブロックのようにいくつか用意されているデザインから選べればと思いました。
基本的にはタイトルのデザインが装飾されていない状態で使うことを想定していますが、どうぞご検討ください。

以下が現在の「タイトル」ブロックの状態で、h3ときは2色の下線が付いています。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/ecf928f2-2f56-4bf1-8e96-e791ada0a756)

**Comment by kurudrive** [comment]
あぁ、これテーマのスタイルがあたっちゃうのか...むしろテーマ側でタイトルブロックに対して装飾をつけないようにしないといけないな...

**Comment by kurudrive** [comment]
個人的には 投稿一覧のタイトルについては装飾されるケースは少ないかなーと。

あ、これクエリーループだけじゃなくてフルサイト編集の記事のタイトルにも使われるんだっけ？

それならあってもいいかなとは思いつつ、VK Blocks Pro に入れると使わない人にとっても重くなったり複雑になるので、
カスタムブロックスタイル用の json ファイルを配布したりした方が良いかなと。
その方が必要な人だけインストールできるので。

**Comment by mtdkei** [comment]
> あ、これクエリーループだけじゃなくてフルサイト編集の記事のタイトルにも使われるんだっけ？

フルサイト編集でも幾つかの場所で使われていそうでした。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/1f353a0a-0fbe-4a1e-a09e-de3575c82298)
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/9db502e0-bf1d-4994-8295-b5c69400f767)

**Comment by kurudrive** [comment]
* デザイン変更自体はテーマ側かカスタムスタイルでやった方がいいかな

- [ ] でもテーマからの指定などを打ち消すための 装飾なし だけはあった方がいいかな...

**Comment by mtdkei** [comment]
#1124 にて「タイトル」の見出しデザインで意図しない装飾がなくなったのでひとまずCloseします。ありがとうございました。
