### ISSUE TITLE
【機能追加要望】［スライダー］Lightningのように背景画像全体にリンクを設置できると良いかもしれないです

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1922]
パターン作成時に、背景全体にリンクできると良いなと思う時がありました
実装するのが難しい場合はCloseしてください🙇(カバーブロックにもリンク機能ないし、難しいのかもしれないですね)
いったんAssigneesには開発メンバーを入れさせていただきました

▼過去のフォーラム
https://vws.vektor-inc.co.jp/forums/topic/vk-blocks%e3%81%ae%e3%82%b9%e3%83%a9%e3%82%a4%e3%83%80%e3%83%bc%e3%81%a7%e3%80%81%e7%94%bb%e5%83%8f%e5%85%a8%e4%bd%93%e3%81%ab%e3%83%aa%e3%83%b3%e3%82%af%e3%82%92%e8%b2%bc%e3%82%8b%e3%81%93%e3%81%a8

**Comment by kurudrive** [comment]
関連
https://github.com/vektor-inc/vk-blocks-pro/issues/2052

**Comment by mtdkei** [comment]
マージされましたのでCloseします
