### ISSUE TITLE
【相談・要望】［見出し（非推奨）］ブロックツールバーの変換のところにコアの見出しが出てくると変換しやすい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1923]
VK 見出しが非推奨になってコアの見出しに変更する際に、ブロックツールバーにコアの見出しが出てこないので、出てくると変換作業が楽になると思いましたのでissueにします🙇
VK 見出しはアイコンやサブテキストの機能もあるので、難しそうでしょうか？難しい様でしたらCloseしてください。

-----
![スクリーンショット 2024-02-21 11 09 13](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/5e48d390-076d-4fa7-b986-2f3d11537c8a)

**Comment by drill-lancer** [comment]
マージされたので Close
