### ISSUE TITLE
カスタムCSSのテキストエリアの縦方向を広げられるようにしたいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1929]
カスタムCSSに書いたCSSを一眼でバッと見たい時があるので、テキストエリアの縦方向を広げられるようできたらと思いました。
例えば以下のように、右下角の３本線で下方向に広げられたらと思ってます。

![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/c8474106-528e-42f4-81cd-ad943e5b44cb)

他にカスタムCSSをよく使う方のご意見も伺えればと思いAssigneesに追加しました。

**Comment by goutetsuguma** [comment]
@kurudrive @mtdkei @sysbird 

CSSが長くなると見ずらいですよね汗

もうCloseされてしまったissueですが、本文蘭に置くカスタムCSSのタイプ「A」案もありました。

https://github.com/vektor-inc/vk-blocks-pro/issues/1419

この「A」案があると良いのかもしれないと思えてきましたがどうでしょうか？でもCloseしたということはいらなかったのかもしれないですね。。？

**Comment by mtdkei** [comment]
@goutetsuguma 
issue拝見しました。個人的には今のカスタムCSSを広げられたらとは思っているのですが、カスタムブロックA案もいいですね。
確かにCloseになっているのが気になります。

**Comment by kurudrive** [comment]
|￣￣￣￣────￣￣￣￣） Close したのは下村君に遠慮したからですよ

**Comment by sysbird** [comment]
少し調べました
CSS を書いたぶんだけ高さが表示されるモードがあるようです
これだとCSS を書くときや、すでに書いてあるときはわりと使いやすい感じがします
ただし空白の場合は高さが1行しか表示されないのでわかりずらいかも

現状は 200px 固定です

**Comment by sysbird** [comment]
![custom-css](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/4cf17c02-15cc-4f76-b867-ed0b004b1a6a)
ここに記述したぶんだけ下にひろがっていきます

**Comment by mtdkei** [comment]
マージされましたのでCloseいたします
