### ISSUE TITLE
【機能追加要望】[スライダー]スライダーアイテムに余白が設定できると使いやすいかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#1934]
スライダーアイテム内に余白が設定できると良いなと思うことがありました。（現在はグループブロックを中に入れて余白を設定しています。[例えばこのパターンのギャラリー部分](https://patterns.vektor-inc.co.jp/vk-patterns/nursery-school_event-and-gallery/)はグループに余白を設定しています）

スライダーアイテムの「レイアウト設定」の余白（左右）に「スライダーアイテムエリア内に余白を追加する」がありますが、この余白だと大きすぎることがあるのと、「コンテナエリアに合わせる」の場合は、テーマによっては余白がついたりつかなかったりするので、ブロック側で余白が設定できると便利そうだなと思いましたのでissueにしました。

いったんAssigneesには開発者メンバーを入れさせていただきました🙇‍♀️

**Comment by kurudrive** [comment]
■ 現状の余白システムを廃止してコアにあわせる
（既存コンテンツに対しては現状の余白設定に応じて近しい値で自動的に置換されるようにする）

**Comment by mtdkei** [comment]
グループブロックっぽい感じとなると、block.jsonのsupportsにspacingとか追加する感じだと思ったのですが、既存コンテンツの置き換えを考えると独自実装ということも考えられるのでしょうか。

**Comment by mtdkei** [comment]
@kurudrive 
承知しました。既存コンテンツの変更を伴う修正はしたことなく不安なので細かくプルリクを出してみます。

**Comment by mtdkei** [comment]
全て完了したのでCloseします。ご確認いただきありがとうございました。
