### ISSUE TITLE
【機能追加要望】[バンくずリストブロック]区切り線のデザインが選べるか入力できたらと思ってます

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1935]
パンくずリストブロックの区切り線ですが、何候補からかデザインを選択できたり、区切り線の入力欄があったらブロックテーマでのデザインの細かいところまで作り込めるかなあと思ってます。
カスタムCSSで対応できるので優先度は超低にしてます。

例えば

＞ とか
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/db2043cf-216c-4f05-9d7f-c9e21a211bf6)

▶︎ とか(FontAwesome使用)
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/9eaa218f-ed65-46dd-b2b9-dfd384aa511a)

**Comment by kurudrive** [comment]
- [ ] セパレーターを何にするかの入力欄を作る
- [ ] .vk_breadcrumb_list_item:after { content: } に対して 入力された値を反映させる

https://github.com/vektor-inc/vk-blocks-pro/blob/176e3ec2bb9ab97b01eb39256b7489f2cde84e94/src/blocks/_pro/breadcrumb/index.php#L56

を

	$breadcrumb         = $vk_breadcrumb->get_breadcrumb( $breadcrumb_options );
	$breadcrumb        .= '<style type="text/css">.vk_breadcrumb_list_item:after { content: "設定で入力した項目" } </style>';
	return $breadcrumb;

とかにすればできる。ただし、FontAwesome はタグだから話が別。

とすれば出来ます。

ただし...
フルサイト編集においては各テンプレート毎ですべて同じに設定しなくてはいけないという問題が発生する。
固定ページは変更したが固定ページ2カラムテンプレートは変更し忘れたとか。

そうなってくると、追加CSSに 
.vk_breadcrumb_list_item:after { content: " > " } 
とか書いた方が一括で全部反映されるし、まぁ管理画面のUIでやるなら...

あぁそうか...
ブロック側に設定項目を作るのではなくて、VK Blocks の設定画面に設定項目を追加して、option に情報を保存して、その情報を元に .vk_breadcrumb_list_item:after { content: " > " }  を ブロック側ではなくて wp_add_inline_style() で出力する方が良さそう。

管理画面の作成はFAQブロックがシンプルで参考にしやすいかもしれない
https://github.com/vektor-inc/vk-blocks-pro/blob/176e3ec2bb9ab97b01eb39256b7489f2cde84e94/src/admin/new-faq.js

**Comment by mtdkei** [comment]
@kurudrive 
ありがとうございます。試しにやってみます！

**Comment by kurudrive** [comment]
@mtdkei 
FAQ はプルダウンだったから ライセンスキーの方がテキスト入力なので近いっぽい
https://github.com/vektor-inc/vk-blocks-pro/blob/176e3ec2bb9ab97b01eb39256b7489f2cde84e94/src/admin/license.js

**Comment by kurudrive** [comment]
@mtdkei 
このファイルから読み込むので、これも変更が必要
https://github.com/vektor-inc/vk-blocks-pro/blob/176e3ec2bb9ab97b01eb39256b7489f2cde84e94/src/admin/index.js
