### ISSUE TITLE
[ アイコン ] ベタ塗り白で表示できるようにしたい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#1936]
いまのところベタ塗り白にしようとすると、アイコンフォントが白固定のため真っ白になってしまう
ベタ塗り白にしたい場合があるけど、それにはアイコンの色と背景色を別々に指定する必要があるのかな？

**Comment by sysbird** [comment]
アイコンブロックを作った覚えがあるので、着手します！

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1625

**Comment by mtdkei** [comment]
マージされたようなのでCloseします

**Comment by sysbird** [comment]
@kurudrive @kaorock72 
こちらお知らせに掲載しますか？

**Comment by kurudrive** [comment]
@sysbird @kaorock72 そうですね、よろしくお願いいたします。

**Comment by kaorock72** [comment]
@sysbird ご対応ありがとうございました！お知らせ掲載しました

**Comment by sysbird** [comment]
@kaorock72
掲載ありがとうございます！
閉じまする
