### ISSUE TITLE
[ ボタンブロック ] 背景を白にした時に文字色が効かないので直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1937]
https://patterns.vektor-inc.co.jp/wp-admin/post.php?post=15813&action=edit

![スクリーンショット 2024-03-26 11 26 48](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/7816170f-8624-4429-b6e1-378af7f44742)

**Comment by sysbird** [comment]
編集画面だけなんですよね

**Comment by kurudrive** [comment]
ですです

**Comment by sysbird** [comment]
見ます

**Comment by sysbird** [comment]
グループの文字色が優先されている

**Comment by sysbird** [comment]
マージされたので閉じます
