### ISSUE TITLE
[ 目次ブロック ] 6.5の環境で先頭の番号のみの表示になってしまう（見出しの内容が表示されない）

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/vk-blocks-pro#1956]
### 確認したこと

**Lightning公式サイト**
WordPress6.5
VK Blocks Pro1.70.0.0

既存ページ（編集画面・フロント画面ともに、見出しが先頭の番号のみ）
※目次を設置し直しても改善しなかった
https://lightning.vektor-inc.co.jp/support/

**Vektor-incサイト**
WordPress6.5-RC4
VK Blocks Pro1.70.0.0

新規作成した見出しテストページ（非公開）（編集画面・フロント画面ともに、見出しが先頭の番号のみ）
https://www.vektor-inc.co.jp/wp-admin/post.php?post=47063&action=edit

既存ページ（編集画面・フロント画面ともに、見出しが先頭の番号のみ）
※確認した時点でこの状態だった
https://www.vektor-inc.co.jp/post/wordpress-6-5-dev-note-note/

既存ページ（編集画面・フロント画面ともに、見出しが先頭の番号のみ）
※確認した時点では見出しの内容は表示されていたが、何も変更せず更新ボタンで更新すると、見出しが番号のみになった
https://www.vektor-inc.co.jp/post/copy-and-paste-blog-card-block/

**Lightning G3 Proデモサイト**
WordPress6.4.3
VK Blocks Pro1.70.0.0

既存ページ（編集画面・フロント画面ともに、問題なし）
※何も変更せず更新ボタンで更新してみても、表示に問題ない
https://demo.dev3.biz/lightning-g3-pro/sample-design/vk-blocks-pro-sample/

### 久納さんが確認してくれたこと
[パターンライブラリからコピペしたやつ](https://lightning.vektor-inc.co.jp/wp-admin/post.php?post=7936&action=edit) はフロント画面ではタイトルが表示されて管理画面では表示されませんでした。

**Comment by mtdkei** [comment]
マージされてましたのでCloseします
