### ISSUE TITLE
6.5 環境で js ファイルの読み込みで宣言済みエラーになる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1965]
https://demo.dev3.biz/lightning-g3-pro/

![スクリーンショット 2024-04-04 20 55 46](https://github.com/vektor-inc/vk-blocks-pro/assets/3272660/bf7051a3-7f54-48ab-8f15-fb47ede5fa11)

* テーマが Lightning だと発生
* TT4 や X-T9 では発生しない
* Nishiki で発生
  → クラシックテーマで発生
    - 分割良い込みだと発生しない
    
## 確認箇所・修正方法

下記参照
https://github.com/vektor-inc/vk-filter-search-pro/pull/381

**Comment by kurudrive** [comment]
僕の方で一応調査中ですが何か情報お持ちだったり同時進行で調査いただいても問題ありません (￣人￣)

**Comment by mtdkei** [comment]
マージされていましたのでCloseします
