### ISSUE TITLE
WP6.6の環境でVK Blocksが読み込まれなくなりました

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1975]
## 現状

WordPress 6.6の環境下でVK Blocks Pro、VK Blocksが読み込まれなくなりました。
(6.6がまだ安定していないとかそういう影響なのかもしれませんが。)

 固定ページ等でVK Blocksのパターンを追加しようしても表示されず、ブロックの一覧にも出てきません。
 なお、ExUnitとFilter Searchのブロックは表示されます。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/ef307a3b-0d88-43ec-af76-065744799f1b)

VK Blocksが使われているパターンをコピペすると以下の様に「"vk-blocks/ XXX" ブロックはサイトでサポートされていません。そのまま残すか、カスタム HTML ブロックへ変換、または完全に削除してください。」
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/f5120f38-df68-4a6a-9759-b4c7bb903e55)

また、ダッシュボード > 設定 > VK Blocks を開くと、VK Blocks 設定の中身も表示されない状態です。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/1fc393a2-3f96-43af-b34f-4a21a8017f61)

## 確認方法

1. WP Beta Tester等で WordPressの環境を6.6にします。(最前線&ナイトリー)
2. 固定ページ等でVK Blocksのブロックを追加しようとしてみてください。
3. 固定ページ等でVK Blocksが使われているパターンを追加しようとしてみてください。
4. 設定 > VK Blocks でVK Blocks 設定の中身が表示されているか確認してください。

**Comment by drill-lancer** [comment]
問題の発生する箇所

https://github.com/vektor-inc/vk-blocks-pro/blob/5b0bd8887a87f9460a7892e85001e4b5b7a6bfe2/src/blocks/_pro/blog-card/api/fetch-url-data.js#L29-L67

上記の async の部分

https://github.com/vektor-inc/vk-blocks-pro/blob/5b0bd8887a87f9460a7892e85001e4b5b7a6bfe2/src/utils/store/index.js#L47-L81

上記の resolvers の部分

上記を解消する必要があります。

**Comment by drill-lancer** [comment]
どうも babel をゴニョゴニョするのがよさそうです。

**Comment by mtdkei** [comment]
ありがとうございました。Closeします。
