### ISSUE TITLE
[ 共通余白設定 ] 2xs と 2xl を追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1987]
- [x] デフォルトCSS（とりあえず数値はおまかせ）
- [x] 管理画面
- [x] ツールバー
- [x] レスポンシブスペーサー

**Comment by mtdkei** [comment]
@kurudrive 
念のため確認ですが、スペーサーを確認したところ、すでにX-T9には2xsの変数が用意されているようでしたので、こちらを活用する予定です。
--wp--custom--spacing--xx-small: 0.375rem;
