### ISSUE TITLE
[ Outer ] コンテナ内側のスペース設定と最小高さ設定のUIコンポーネントを共通化

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1993]
モバイル / タブレット / PC の数値指定はここに限らず複数出てくるので、今後UI自体を改善する際の効率も考えると共通コンポーネントした方が良いのではないかと思いますがどうです？

https://github.com/vektor-inc/vk-blocks-pro/pull/1967

**Comment by mtdkei** [comment]
UIコンポーネントがあった方が後々最初の高さを設定したいブロックが出てきた時に実装しやすいように感じました。
