### ISSUE TITLE
[ Outer ] 区切りの種類が増えたら嬉しいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1997]
以前よりVK Blocks ProでOuterを使うときに区切りの種類がもう少しあったらと感じることが時折ありました。

追加区切り線の例:
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/96a5cb49-c21a-41f1-8589-588017d98529)
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/cc599c4c-cf4f-4af9-8802-0de58585f85a)
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/852b2121-6f63-4edf-84f2-d4a2d379d4a1)

ただ、区切り線の多すぎるのもどうかなあと思うので、ご意見等いただけたらと思います。

参考サイト:
https://elefantastic.tokyo/shapes/
https://shapedividers.com/

**Comment by goutetsuguma** [comment]
区切りの種類がもっとあるとパターンの幅も広がりますね！Elementorのシェイプ充実してますね、、！
ギザギザ・三角・本・ピラミッドあたりはよく使われそうなので、入ってると嬉しいです！

**Comment by kurudrive** [comment]
ユーザー側が追加・停止を選べる形式がいいかな...

**Comment by mtdkei** [comment]
- [ ] ギザギザ
- [ ] 三角
- [ ] 本
- [ ] ピラミッド

**Comment by mtdkei** [comment]
マージされたのでCloseします。またOuter区切りの希望がありましたら…！
