### ISSUE TITLE
「リスト項目」を選択しているときにリスト項目を囲う「リスト」に戻るボタンが欲しいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#1999]
ブロックエディタでリストブロックの「リスト項目」を選択しているときに、リスト項目を囲う「リスト」に戻るボタンが欲しいです。

参考例(SWELL) :
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/af623acb-53db-47df-abea-e9c69e081efe)

「リスト」を選んでるつもりが実際には「リスト項目」を選んでいる場合があり、スタイル設定などで「あれ？」となることがあります。
上記のようにボタンがあるとスムーズに戻ることができます。

**Comment by sysbird** [comment]
おぉ、SWELLにはそのようなボタンがあるのですね
ツールバーから戻れるので、とくに不便を感じてませんでした

![parent](https://github.com/vektor-inc/vk-blocks-pro/assets/4631838/4655abb5-3b7f-48d2-b6ce-c081ff1c8489)

**Comment by mtdkei** [comment]
ご意見を伺った上でひとまずCloseします。ありがとうございました。
フォーラム等で要望があった場合にまた検討させていただきます。
