### ISSUE TITLE
ブロック一覧の最上部にベクトル製品のブロックが表示されるようにしてほしいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2000]
ブロックを挿入する際に+ボタンを押したときに表示されるブロック一覧の最上部に、ベクトル製品のブロックが表示されるようにしてほしいです。

参考例(SWELL) :
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/01e9fdde-ecd4-4b3d-93bf-f21a03b95a91)

**Comment by drill-lancer** [comment]
@kurudrive 
順番は下記で OK でしょうか？
 VK Blocks ⇒ VK ブロックレイアウト => ( VK EXUNIT Blocks ) ⇒ コア

**Comment by kurudrive** [comment]
@drill-lancer ほぃ。それで。ってこれまだ @mtdkei さん着手してなかったっけ？

**Comment by mtdkei** [comment]
@kurudrive 
こちらは着手してないです。

**Comment by drill-lancer** [comment]
@kurudrive 
Deprecated Blocks は VK ブロックレイアウトと ( VK EXUNIT Blocks ) の間ですか？
それともコアの後でしょうか？

**Comment by kurudrive** [comment]
@drill-lancer え？そんなカテゴリー （ Deprecated Blocks ）存在しなくない？
今回新規に作って分けるって事（・ｗ・？

**Comment by drill-lancer** [comment]
@kurudrive 
存在自体はしているみたいです。使ってないだけかもですが・・・

https://github.com/vektor-inc/vk-blocks-pro/blob/60433f80a55370f054508a76803ca3d12db0d98b/inc/vk-blocks/blocks.php#L46-L57

**Comment by kurudrive** [comment]
@drill-lancer あー、作ってあるけど使われてはいないって感じか。

* カテゴリーで非推奨にわけてもユーザーが気づかない（だから今ラベル自体に非推奨表記してる）
* もしかして非推奨から通常に復帰するブロックが出てくるかもしれない

なので、カテゴリー自体削除でいいかな。

**Comment by mtdkei** [comment]
マージされましたのでCloseします
