### ISSUE TITLE
[ ボタン ] 角丸の設定をできるようにしたいです

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2001]
・ボタンのデザインがもっと選べると良いなと思います。
border-radius（角丸）を設定できるだけでも良いと思います！（カスタムCSSで追加していますが、CSSの知識のないクライアントさんなどだと設定できると使いやすくなると思います）

参考例(コアのボタンブロック):
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/5c929a20-a5a6-4d01-ab5d-0be7e755874c)

**Comment by kurudrive** [comment]
たぶん border サポートするだけでいけるんじゃないかな？

とは思いつつ、どうなんでしょうね...

**Comment by mtdkei** [comment]
@kurudrive 
私もそう思ったのですけど、以下のようになってしまいますね。
![image](https://github.com/vektor-inc/vk-blocks-pro/assets/21466284/1903e7b1-5939-4ce6-ae53-2892199f9cf6)
HTMLとしては以下のような感じです。
`<div class="wp-block-vk-blocks-button vk_button vk_button-color-custom vk_button-align-left has-border-color" style="border-color:#cf2e2e;border-radius:10px"><a class="vk_button_link btn has-background has-vk-color-custom-3-background-color btn has-text-color has-vk-color-custom-5-color btn-md" role="button" aria-pressed="true" rel="noopener"><div class="vk_button_link_caption"><i class="fa-solid fa-phone vk_button_link_before" style="font-size:20px" aria-hidden="true"></i><span class="vk_button_link_txt">aaaaaaaa</span><i class="fa-solid fa-circle-exclamation vk_button_link_after" aria-hidden="true"></i></div></a></div>`

**Comment by kurudrive** [comment]
あぁ...じゃあ角丸だけ独自実装した方がはやいか...（・ｗ・；

**Comment by mtdkei** [comment]
マージされましたのでissueをCloseします。ありがとうございました！

**Comment by ChiakiKouno** [comment]
とても遅くなってしまいましたが…
アンケートからのIssue化、そして実装とマージまで素晴らしい流れでした、ありがとうございました！！
