### ISSUE TITLE
[ カテゴリーバッジブロック ] タクソノミーの選択が表示されなくなってる...なぜ...

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2004]
初期実装のプルリクを見る限りタクソノミーの指定ができるはずなのですが...

https://github.com/vektor-inc/vk-blocks-pro/pull/1887/files

どこかでデグレったのかWordPressの仕様変更の影響なのか...

**Comment by mthaichi** [comment]
@kurudrive 複数タクソノミーがないとプルダウンが表示されないです。複数タクソノミーがあるときには私の環境で表示されておりました。

**Comment by kurudrive** [comment]
たぶん 制作実績のタームが選択できない
https://app.instawp.io/launch?t=x-t9-pro--vk-ab-testing&d=v2

**Comment by mthaichi** [comment]
@kurudrive  これは再利用ブロックなので、今のままでは使えないのかと。再利用ブロックの外側なら選択できます。
コアのpost-termブロックのようにバリエーションで展開する感じでしょうか。ちょっと試してみます。

**Comment by kurudrive** [comment]
close as completed
