### ISSUE TITLE
VK Blocks を有効化していると VK Blocks Pro を有効化できないのを直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2016]
1.73.0.0 の組み合わせでも

重大なエラーを引き起こしたため、プラグインを有効化できませんでした。

になってしまう

https://github.com/vektor-inc/vk-filter-search-pro/pull/371
https://github.com/vektor-inc/vk-filter-search-pro/issues/370

昔はこうならないようになってたはずなので、
テストの追加もよろしくお願いいたします。
G3 Pro Unit とか VEKUAN あたりで PHPUnit の tests/bootstrap.php あたりに .org のテーマやプラグインのインストールをしてるのがあるはず。
そのあたりとか参考に VK Blocks をダウンロードして、PHPUnit でアクティベートした上で、VK Blocks Pro を関数で有効化する感じで、アクティベートする関数の返り値でテストできるはず...たぶん

**Comment by mtdkei** [comment]
@kurudrive 
VK Blocks Proの直下にあるPHPにvk-blocks-pro.phpはなく、[vk-blocks.php](https://github.com/vektor-inc/vk-blocks-pro/blob/master/vk-blocks.php)があるのですが、その部分が関係してたりしますかね？あえてそのようになさってますか？

**Comment by kurudrive** [comment]
> VK Blocks Proの直下にあるPHPにvk-blocks-pro.phpはなく、[vk-blocks.php](https://github.com/vektor-inc/vk-blocks-pro/blob/master/vk-blocks.php)があるのですが、その部分が関係してたりしますかね？

@mtdkei たぶんあまり深い意味はないと思います。で、このファイル名自体は特に問題なかったはず...

@drill-lancer だよね？

**Comment by mtdkei** [comment]
@kurudrive 
わかりました、ありがとうございます！
