### ISSUE TITLE
[ タブブロック ] タブカラーを指定したときにアクティブでないタブはグレーになってほしい

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/vk-blocks-pro#2017]
- タブ01：タブカラーを指定
- タブ02：タブカラーを指定していない

上の状態でタブ01がアクティブな場合は、以下のように想定どおりの表示になります。
- タブ01：指定したカラーで表示
- タブ02：グレーで表示

ただ、タブ02をアクティブにすると、以下のようになってしまいます。
- タブ01：指定したカラーのまま
- タブ02：デフォルトのブルーで表示

https://github.com/vektor-inc/vk-blocks-pro/assets/59037734/3337e978-9e83-4846-9d3b-feade4a0a1b2

以下のお知らせ記事内「タブカラーの指定」のところで挙動を確認できます。（非公開）
https://www.vektor-inc.co.jp/product-update/vk-blocks-pro-1-73-0-add-tab-block/

以下のように、タブカラーを指定しない時（デフォルト）と同じ動きになると、わかりやすくてよいのではと思います。

タブ02をアクティブにした時
- タブ01：グレーになってほしい
- タブ02：タブ01で指定したカラーで表示してほしい

**Comment by mtdkei** [comment]
マージされましたのでCloseします
