### ISSUE TITLE
[ タブブロック ]スタイルでラインを選んだ時にデフォルトで表示される枠線の上部が表示されない

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/vk-blocks-pro#2018]
タブブロックを挿入し、スタイルで「ライン」を選んで表示を確認すると、枠線の上部？が表示されないようです。

https://github.com/vektor-inc/vk-blocks-pro/assets/59037734/67a8d3ec-eab7-4351-b38d-3480b05c79d7

以下のお知らせ記事内「タブのスタイル」のところで確認できます。（非公開）
https://www.vektor-inc.co.jp/product-update/vk-blocks-pro-1-73-0-add-tab-block/

※Asaigneesどなたがよいのか、、ひとまず入れてみました、よろしくお願いします...！

**Comment by mtdkei** [comment]
マージされましたのでCloseします
