### ISSUE TITLE
[ 投稿リストブロック ] 存在するカスタム分類がすべて表示される現状を改善したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2028]
現状存在する全タクソノミーが表示されてしまうので、

A. 該当する投稿タイプのものだけが表示されるようにする
B. タグのように入力方式にする

個人的には A の方式の方がいいと思ってます。

**Comment by mtdkei** [comment]
マージされましたのでCloseします
