### ISSUE TITLE
［ 固定ページブロック ］固定位置を左・右にしたときにカバーブロックなどの下に隠れて編集がしづらい場合があるかもしれません

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2030]
固定位置を左・右にしたときに上部からの固定位置が50vh の場合などに、「固定ページブロック」がカバーブロックなどの下に隠れて編集がしづらい場合があるかもしれません。
もし可能であれば編集画面では他のブロックよりも重なり順を上にするか、もしくは編集画面では編集位置は固定で動かなくする（注意書きで「編集画面では固定位置ブロックの固定位置は変わりません。フロント画面でご確認ください」などと書いておく？）などしますと編集がしやすいかもしれません。

デモサイトで触ってみました
https://demo.dev3.biz/lightning-g3-pro/wp-admin/post.php?post=5513&action=edit

いったんissueをあげましたが、私の使い方ミスの可能性もあります🙇

**Comment by mtdkei** [comment]
ありがとうございます！先程同様の確認をしたので修正します。

**Comment by mtdkei** [comment]
マージされましたのでCloseします
