### ISSUE TITLE
ブロック一覧にVK ブロックが最上位にきますが、設定などで順番を最上部or標準で選べるようにしたいというご意見をいただきました。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2046]
[こちらのプルリク](https://github.com/vektor-inc/vk-blocks-pro/pull/2024)でブロック一覧にVK ブロックが最上位にくるようになりましたが、設定などで順番を最上部or標準で選べるようにしたいというご意見をいただきました。
実装できるのかどうかがわかりませんでしたので、いったんissueをあげさせていただきました。
いったん「相談」とさせていただきます。

https://vws.vektor-inc.co.jp/forums/topic/1-75-1-0-%e3%81%a7%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e8%bf%bd%e5%8a%a0%e6%99%82%e3%81%abvkblocks%e3%81%8c%e5%85%88%e9%a0%ad%e3%81%ab%e8%a1%a8%e7%a4%ba%e3%81%95%e3%82%8c%e3%82%8b%e3%82%88%e3%81%86?view=all#post-93676

**Comment by mtdkei** [comment]
マージされましたのでCloseします。
