### ISSUE TITLE
[アクセシビリティ] :before、:after 疑似要素で content を設定しないようにする

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2049]
* 目次ブロック
  * OPEN、CLOSE が:before 要素で設定されているので、実態を用意する
  * いま` input` で対応しているので、`js `を使う方式にする
 * FAQ(新 / 旧)
    * 「Ｑ」「A」 が不擬似要素になっているので、実態を用意する

**Comment by mtdkei** [comment]
すべてマージが完了したため、Closeします。ありがとうございました。
