### ISSUE TITLE
【機能追加要望】EditorsKitのようにカバーやカラムブロック、グループ全体にリンクを貼れる機能が欲しい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#2052]
（[2023年度ユーザーアンケートより](https://docs.google.com/spreadsheets/d/18vSJNPUzZQBburRxyZwlxohAQqCW8T2REZHUEu-S2pw/edit?gid=1698155874#gid=1698155874&range=W57)）

**Comment by mtdkei** [comment]
@ChiakiKouno 
こちらの件ですが、以下にプルリクを出しているところです。現在確認待ちとなっております。
https://github.com/vektor-inc/vk-blocks-pro/pull/2023

**Comment by kurudrive** [comment]
関連
https://github.com/vektor-inc/vk-blocks-pro/issues/1922

**Comment by mtdkei** [comment]
全体リンクがあったらいいと思うブロック

- [ ] カバー
- [ ] カラムブロック
- [ ] グループ
- [ ] Outer

他にもあれば上記に追加します。

**Comment by ChiakiKouno** [comment]
@mtdkei 
ありがとうございますー！私の感覚的に全体リンクがあると嬉しいなと思うものは今出していただいているブロックたちでとてもよくカバーできていると思いました！他にも思いついたらお知らせしますね。

> なんとなく最初はVK製品から手をつけてコアの方は後のほうがいいかな
確かにコアは後の方が良いかもですね（コアで実装されたりするかもしれないし）
Outerが対応してくれたのでもう何でもほうりこめる感🙌 ああ、コアのグループも進行してくださっている◎

**Comment by mtdkei** [comment]
こちら全てマージされましたのでCloseします。ありがとうございました。
(空のaタグ対応については別のissueで確認します。)
