### ISSUE TITLE
【アンケートより】構造化データのマークアップを強化してほしい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#2053]
[2023年ユーザーアンケートより](https://docs.google.com/spreadsheets/d/18vSJNPUzZQBburRxyZwlxohAQqCW8T2REZHUEu-S2pw/edit?gid=1698155874#gid=1698155874&range=W99)
構造化データのマークアップを強化してほしい。ページごとで設定したい場所やイベントFAQなど

**Comment by kurudrive** [comment]
* イベント -> 作る人によるのでベクトルでの対応は無理じゃない？
* FAQブロック -> 構造化データでなにか改善できそうな気がする。要調査・対応

**Comment by mtdkei** [comment]
構造化データの出力機能を実装した方がいいかもしれないものをChatGPTで出力してもらって整理しました。とりあえずFAQブロックは #533 でも上がっていたので作っています。

- [ ] Classic FAQ / New FAQ (構造化データ: FAQPage)
FAQPage構造化データを使用することで、検索エンジンに質問と回答のペアを伝えることができます。
- [ ] Breadcrumb [ Pro ] (構造化データ: BreadcrumbList)
BreadcrumbList構造化データを使用することで、検索エンジンがページの階層構造を理解し、検索結果にパンくずリストを表示できるようになります。
- [ ] Post list [ Pro ]
- [ ] Selected Post List [ Pro ]
(構造化データ: BlogPosting / Article)
記事を一覧表示するブロックに対して、BlogPostingまたはArticleの構造化データを適用することで、記事情報を検索エンジンに提供できます。
- [ ] Staff (not recommended) (構造化データ: Person)
Person構造化データを使用して、スタッフのプロフィール情報（名前、役職、写真など）を検索エンジンに提供できます。

**Comment by mtdkei** [comment]
何かしらの構造化データを追加したら出力制御をAdmin側で設定できたらいいかもしれない。
(ユーザーによってはすでに構造化データプラグイン等を使っている可能性があるので。)
