### ISSUE TITLE
[ 画像ブロック ] 正円 スタイルが欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2057]
コアの機能でできるが手数が多いため

**Comment by goutetsuguma** [comment]
今日の終礼で話していたことメモ
正円はコアの機能でできるが、手数が多いのでエンドユーザーにとってはスタイルから変更したい。
そもそもスタイルの中にあれだけ種類がたくさんあるのになぜか正円がない。

**Comment by mtdkei** [comment]
マージされてましたのでCloseします。
