### ISSUE TITLE
固定表示ブロックで「X秒後に非表示」という機能をつけたい

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2058]
X秒後にブロックが非表示になる設定ができたら、固定表示ブロックを応用してポップアップやローディングが作れるのではないかと思いました。パターンの幅も広がりそうかなと思うのですがどうでしょうか？

※ ご意見を伺うために皆さんを入れています。実際の作業はこちらで行う予定です。

**Comment by sysbird** [comment]
おもしろいです！
ちらっと広告バナーを表示したりできそう

**Comment by ChiakiKouno** [comment]
私もあると面白いと思いました！
同じ設定画面で、逆の設定で、X秒後に「表示」という機能も併せてできたりする…でしょうか？（メルマガ登録とかLine登録とかに誘導するような？）すみません、あるといいなくらいで、別検討でも全然構いません○

**Comment by mtdkei** [comment]
@sysbird @ChiakiKouno 
ご意見ありがとうございます。6.6が落ち着いたらひとまず作ってみます。
Chiakiさんの
> 同じ設定画面で、逆の設定で、X秒後に「表示」という機能も併せてできたりする…でしょうか？（メルマガ登録とかLine登録とかに誘導するような？）すみません、あるといいなくらいで、別検討でも全然構いません○
も合わせて考えてみます！

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
