### ISSUE TITLE
［目次ブロック］Windowsで、見出しにインライン画像が入っていると、目次ブロックでOBJがついてしまうのを治せるのかどうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2070]
Windowsで見た時、見出しにインライン画像が入っていると、目次ブロックで見出しの前に「OBJ」がついてしまうようでした。（macでは確認できず空欄になっています。）
cssが書けない方は、見出しにインライン画像で装飾をつけてる人がおられますので、もし可能でしたら治せたら良いのかもしれないと思いissueにしました。

https://vws.vektor-inc.co.jp/forums/topic/%e7%9b%ae%e6%ac%a1%e3%81%ab%e8%a6%8b%e5%87%ba%e3%81%97%e3%81%ae%e3%82%a4%e3%83%b3%e3%83%a9%e3%82%a4%e3%83%b3%e7%94%bb%e5%83%8f%e3%81%aeobj%e3%81%8c%e8%a1%a8%e7%a4%ba%e3%81%95%e3%82%8c%e3%82%8b

**Comment by mtdkei** [comment]
対応できそうなのでプルリクあげます。

**Comment by goutetsuguma** [comment]
MargeされたのでCloseします、ありがとうございました！
