### ISSUE TITLE
【要望】［スライダーブロック］「幅広」サイズがあると嬉しいとのご要望

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2081]
もともとスライダーブロックは「幅広」サイズに対応していなかったのですが、「幅広」サイズが欲しいとのご要望がありました。

ほしいとおもった背景は以下の理由だったと思います

* スライダーブロックで、アイテムに「画像」を入れた時に「全幅」のみだと、困る場合がある（画像のサイズがうまくいかないと言っていた気がします）
* 現在はグループブロックを幅広にして、中に全幅のスライダーブロックを入れて対応している

**Comment by ChiakiKouno** [comment]
メモ：[2024年6月28日の質問相談会で上がったIssue](https://docs.google.com/spreadsheets/d/1Yvk3AN4pWn2tjL7DBe0HZm4OvvWOWhfp9ub76bAjmpQ/edit?gid=559583442#gid=559583442&range=B5)

くのうさん、Issue化ありがとうございます！

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
