### ISSUE TITLE
入力したライセンスキーを読み取れないようにしたい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2084]
2024年6月の勉強会にて、入力したライセンスキーを読み取れないようにしたいというご要望がありましたので、issueにします。

[プラグイン版](https://www.vektor-inc.co.jp/product-update/lightning-g3-pro-unit-vk-blocks-pro-license/
)もありますが、停止したら表示されるため、このプラグインとは別の話となります。

[質問スプレットシート](https://docs.google.com/spreadsheets/d/1Yvk3AN4pWn2tjL7DBe0HZm4OvvWOWhfp9ub76bAjmpQ/edit?gid=559583442#gid=559583442&range=B6)

[ディスコード](https://discord.com/channels/1010092469863587892/1087967567223726150/1257207491335422033)

**ライセンス入力欄があるプラグイン**

- [ ] G3 Pro Unit
- [ ] VK AB Testing 
- [x] VK Blocks Pro
- [ ] VK Filter Search Pro Global Edition

---

■ 本当は以下に入力フォーム出力メソッドをもたせた方が良いようにも思うが、急ぎではないので各リポジトリで対応でも可

https://github.com/vektor-inc/vk-license-helpers/blob/main/src/VkLicenseHelpers.php

**Comment by drill-lancer** [comment]
今見てます
