### ISSUE TITLE
【アンケートより：未レビュー】横スクロールするパーツも欲しい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-blocks-pro#2104]
[2023年度ユーザーアンケート](https://docs.google.com/spreadsheets/d/18vSJNPUzZQBburRxyZwlxohAQqCW8T2REZHUEu-S2pw/edit?gid=1698155874#gid=1698155874&range=X22)より

> スマホとPCでレイアウトを変えたくないとおっしゃるユーザー様がいるので…。
> 見た目のレイアウトが変わらないように、横スクロールするパーツも置いて欲しい。
> https://retval.jp/blog/scrollable-table/

ブロックではなくパターンでの提供なのかな、とか、判断がつきませんでした。一旦こちらにissueを立てさせていただきます。

**Comment by mtdkei** [comment]
マージしましたのでCloseにします。ありがとうございました。

**Comment by ChiakiKouno** [comment]
@mtdkei さん、実装ありがとうございました！すばらしい〜！！！

すみません、最近あまり新規実装からお知らせまでの流れを確認できていなかったので、ちょっとお聞きしたいです🙇‍♀️
このように新規機能がついた場合、以前だと、石川さんが本番配信してから、「お知らせ待ち」のラベルをつけて、それを確認した @kaorock72 さんが随時お知らせ記事とツイートをしてくださるという流れだったと思うのです（おそらく）が、今回の場合だとどうなる感じでしょうか？どこかにお知らせ待ちになるnoticeが佐々木さんに伝わるようになっておりますでしょうか？
（既に伝わっている流れになってたらすみません💦）

**Comment by kaorock72** [comment]
@ChiakiKouno @mtdkei そういえば最近はお知らせ待ちまでの流れが曖昧になっていまして、、、石川さんがたまに「お知らせ待ち」のラベルをつけてメンションされることもあるんですが、つけないことの方が多くw
そのため、Githubでそろそろこの機能がリリースされるんだろうなとチェックしておきつつ、製品更新情報でリリースを確認したらお知らせを書く...みたいな感じでやっておりますーー

**Comment by ChiakiKouno** [comment]
なるほどー！！！佐々木さんのお気遣いでもってたんですねw ありがとうございます！ぜひこの機会に流れを見直してみましょう :)
