### ISSUE TITLE
[目次]jsでエラーが出ている

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2106]
`/wp-content/plugins/vk-blocks-pro/build/vk-table-of-contents-new.min.js` でエラーが出ている
たぶん目次ブロックがあるかないか判定必要

※ 分割読み込みしていない場合に目次がないページで発生
![table-of-contents-new](https://github.com/user-attachments/assets/1794bf1c-42ac-4fbb-a6da-8e47d1c29396)

**Comment by mtdkei** [comment]
マージされているようでしたのでCloseします。ありがとうございました。
