### ISSUE TITLE
[ ブログカード ] 編集画面でブログカードアイキャッチ画像など子ブロックが表示されない

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2116]
※ WP6.6でVK Blocks Proが表示されない問題でちょろっと出てたと思いますが忘れないために書いておきます。

編集画面上でブログカードの子ブロックとして用意されている以下が表示されません。
- ブログカードアイキャッチ画像
- ブログカードタイトル
- ブログカード抜粋
- ブログカードサイトロゴ
- ブログカードサイトタイトル

なお、リストビューには表示されます。ブロックとしては認識されているようです。

![image](https://github.com/user-attachments/assets/ebe9a20a-eaa7-4751-ad91-3026018ed049)

**Comment by drill-lancer** [comment]
おそらく下記がうまく動いていないのが原因かと

https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/blocks/_pro/blog-card/api/fetch-url-data.js

**Comment by mtdkei** [comment]
編集画面上でブログカードの子ブロックが表示されない件ですが、調査の結果、以下のような事がわかりました。

ローカルではなくネット上のサイトを検証してみたところ、編集画面上で概ね表示されておりました。表示されていない場合でもVK Blocks Pro 1.79.0から1.80.0にすると表示されるようになりました。
また、ローカルでは1.80.0になっていても表示されてなかったのですが、VK Blocks Proを一旦削除し入れ直したところ、表示されるようになりました。

上記の対応により、VK Blocks Proに何かしらのアクションを起こすとブログカードが表示されるようになりました。
原因はわからないのですが、ひとまずCloseにします。

**Comment by mtdkei** [comment]
マージされましたのでCloseします。
