### ISSUE TITLE
Katawaraなどでグリッドカラムカードを使うと「このブロックでエラーが発生したためプレビューできません。」と表示される

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2117]
グリッドカラムカードを使うと「このブロックでエラーが発生したためプレビューできません。」が出ます。
https://vws.vektor-inc.co.jp/forums/topic/%e3%81%93%e3%81%ae%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%81%a7%e3%82%a8%e3%83%a9%e3%83%bc%e3%81%8c%e7%99%ba%e7%94%9f%e3%81%97%e3%81%9f%e3%81%9f%e3%82%81%e3%83%97%e3%83%ac%e3%83%93%e3%83%a5%e3%83%bc#post-97015

ただ、テーマによってエラーが出るものと出ないものが異なります。

## 上記のエラーが起こるテーマ
- Lightning G2
- Katawara
- Lightning Pro
- TT3

## 上記のエラーが起こらないテーマ
- Lightning G3
- X-T9
- TT4

## 上記を確認した時のVK Blocks Proの状態
- Githubのdevelopブランチ
- Githubのmasterブランチ
- WordPressの管理画面からプラグインを追加し最新バージョン(1.79.1.1)にアップデート

## Google Chrome > 検証 > Console のエラー
```
react-dom.min.js?ver=18.3.1:2 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at block-build.js?ver=f0e7794f80765b7c907a:1:160234
    at Nn (block-build.js?ver=f0e7794f80765b7c907a:1:160296)
    at Ls (block-build.js?ver=f0e7794f80765b7c907a:3:124588)
    at hu (react-dom.min.js?ver=18.3.1:2:60308)
    at xi (react-dom.min.js?ver=18.3.1:2:119597)
    at bs (react-dom.min.js?ver=18.3.1:2:108749)
    at vs (react-dom.min.js?ver=18.3.1:2:108677)
    at gs (react-dom.min.js?ver=18.3.1:2:108540)
    at as (react-dom.min.js?ver=18.3.1:2:105347)
    at is (react-dom.min.js?ver=18.3.1:2:105736)
co @ react-dom.min.js?ver=18.3.1:2
a.componentDidCatch.t.callback @ react-dom.min.js?ver=18.3.1:2
Wa @ react-dom.min.js?ver=18.3.1:2
ki @ react-dom.min.js?ver=18.3.1:2
bi @ react-dom.min.js?ver=18.3.1:2
yi @ react-dom.min.js?ver=18.3.1:2
(anonymous) @ react-dom.min.js?ver=18.3.1:2
ws @ react-dom.min.js?ver=18.3.1:2
is @ react-dom.min.js?ver=18.3.1:2
Hl @ react-dom.min.js?ver=18.3.1:2
(anonymous) @ react-dom.min.js?ver=18.3.1:2Understand this error
```

**Comment by mtdkei** [comment]
テーマによってエラーが出たり出なかったりするのですが、以下のように同環境でテーマだけを切り替えると下記のようにエラーの状況も変わることがわかりました。

- Katawara → TT4 に変えると「このブロックでエラーが発生したためプレビューできません。」と表示されなくなります。
- Lightning G3 → G2 に変えると「このブロックでエラーが発生したためプレビューできません。」と表示されます。

こちらでは上記までは分かったのですが、修正できるところまでは至ってないので、よろしければ @kurudrive、@drill-lancer、@mthaichi のどなたかに見ていただけたら幸いです。

**Comment by mthaichi** [comment]
@drill-lancer @kurudrive @mtdkei 
https://github.com/vektor-inc/vk-blocks-pro/blob/f5441bf6cdcc2e0095c435059f46f675bbe15972/src/components/advanced-color-gradient-control/index.js#L26

useSettings('color.gradients.theme')[0]　がundefined になっているので、

この１行を
```	
const themeGradients = [...(useSettings('color.gradients.theme')?.[0] || [])];
```
としたら、とりあえずエラーはでない気がします。
Katawaraの時にパレットが取得できないだけで。

す、すみません。外しているかもしれません。

わたくし、これからお出かけしなければならず、妥当性も含めて見て頂ければ🙏

**Comment by kurudrive** [comment]
@drill-lancer 僕別件で急ぎの作業してるので確認よろしくお願いいたします (￣人￣)

**Comment by mtdkei** [comment]
マージされましたのCloseします。ありがとうございました。
