### ISSUE TITLE
[outer] 余白 (上下)に「標準の余白を使用」を指定した時＋αの条件で、余白が消えてしまう

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-blocks-pro#2119]
Outerで余白 (上下)に「標準の余白を使用」を指定した時、かつ余白（左右）に「アウターエリア内に余白を追加する」以外を選んだ時に余白が消えてしまいます。

おそらくここで
.vk_outer-paddingVertical-use のpaddingを削除しているのが原因です。
https://github.com/vektor-inc/vk-blocks-pro/commit/e35dccd1b7e9192acc084ea663fb7a18181836b1

VK Blocksをアップデートすることで、Outer内のフロントの余白が全部詰まってしまうので、早急な修正が必要かと思います。

**Comment by goutetsuguma** [comment]
@mthaichi 
このプルリクで解決すると思いますが、いかがでしょうか？
https://github.com/vektor-inc/vk-blocks-pro/pull/2114
別の問題でしたらすみません

**Comment by sysbird** [comment]
そうですね #2114
で解決されたように見えますが、修正箇所が異なるのが気になります
当 Issue が原因でしたら、少し検討したほうがよさそうです

**Comment by mtdkei** [comment]
@sysbird
https://github.com/vektor-inc/vk-blocks-pro/pull/2114 で修正箇所を変えているのは、
[[ outer ] 余白指定を sass の変数ではなく CSS変数に変更
](https://github.com/vektor-inc/vk-blocks-pro/commit/e35dccd1b7e9192acc084ea663fb7a18181836b1)
の修正で意図的に sass の変数を消している様子があるため、変更されたCSS変数に合わせて修正したつもりでしたでした。ややこしくてすみません。

**Comment by sysbird** [comment]
@mtdkei 
ありがとうございます！
こちらこそ読み取れず(書いてあるのに)お恥ずかしい
#2114 のほうをマージしますね

**Comment by mthaichi** [comment]
あ、そうかそうか。よく見ていなくて、すみません。
ありがとうございます！

**Comment by sysbird** [comment]
@mthaichi いえいえありがとうございます
私が discord に書いただけで issue 化してなかったですね
プルリクをマージしたので、close します〜
