### ISSUE TITLE
[ Outer ] 上下余白で標準の余白を使用に設定してあったものが完全に余白なしになってしまう

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2120]
![スクリーンショット 2024-07-18 16 12 55](https://github.com/user-attachments/assets/70e00087-c0a6-4dfb-80c4-f026d8b43311)

**Comment by kurudrive** [comment]
@mtdkei 確認よろしくお願いいたします (￣人￣)

**Comment by mtdkei** [comment]
@kurudrive 
https://github.com/vektor-inc/vk-blocks-pro/pull/2114 にて対応できていると思います。

**Comment by kurudrive** [comment]
@mtdkei あー、ありがとうございます！見かけた記憶はあったのですがマージ済みでしたね。
助かりました！
