### ISSUE TITLE
コアブロックの拡張でstyle.scssを使用しているブロックではフロントエンドにCSSが反映されない

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2123]
VK Blocks Proにコアブロックの拡張機能を追加していますが、その中でstyle.scssを使用しているブロックで、かつ「分割読み込み」をONにしているとフロントエンドにCSSが反映されません。

## 対象のコアブロック
- 見出し
- 画像
- テーブル

## 現象の条件
上記のブロックにスタイルを設定すると、編集画面ではこう見えますが、
![image](https://github.com/user-attachments/assets/9892c145-8baa-4f5c-a020-10c78111f647)

フロントエンドでは反映されません。CSSの設定が負けているとかではなく、そもそもCSSの出力がされていないような状況です。
![image](https://github.com/user-attachments/assets/5be9014f-5c15-431e-ba1d-b6b66d9b2310)

style.jsを使用しているブロック(例えばリストブロック)では同じようにスタイルを設定すると正常にフロントエンドでもデザインが反映されます。
![image](https://github.com/user-attachments/assets/c6e12b86-a58c-4331-bb8f-f52069066ee3)

## スクリーンショット
編集画面
![image](https://github.com/user-attachments/assets/806049d5-30eb-461c-b234-e5c524b2f185)

フロントエンド
![image](https://github.com/user-attachments/assets/fdcb4fd2-3a8a-48da-b701-e1238856932d)

**Comment by mtdkei** [comment]
マージいただきましたのでCloseします。ありがとうございました。

**Comment by sysbird** [comment]
@mtdkei 
たいへんおそれいります〜
分割読み込みのとき VK Bklocks のブロックが編集画面で崩れるときがあります
確認したのは、アイコン、ステップ、タイムライン、新FAQ、目次です
複数環境で確認しました
どうもこちらの影響のかんじ(masterでは再現しない)がしますので、ご確認いただけますでしょうか
 #2130

再現するブロックのコードを添付します
[bunkatsu.txt](https://github.com/user-attachments/files/16420555/bunkatsu.txt)

お手数ですがよろしくお願いします

**Comment by mtdkei** [comment]
@sysbird 
ありがとうございます。確認、修正させていただきます。

**Comment by mtdkei** [comment]
@sysbird 
ご確認いただきありがとうございました。
改めてこちらをcloseします。
