### ISSUE TITLE
[分割読み込み]キーカラーが反映されない場合がある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2128]
* Lightning でアイコンブロックにキーカラーを設定
* 他のテーマで見たとき色がつかない
* フロントエンドのみ
* 分割読み込みのとき
* WP 6.5、6.6とも
* このとき インラインstyle  が抜けているもよう
* ベタ塗り
* 再現パターンの例 [ご利用までの流れ](https://patterns.vektor-inc.co.jp/vk-patterns/flow_app-product-introduction/)

追記:
他のブロックでも発生
ightning でキーカラーを設定した箇所 は x-t9 では紺色(デフォルトで)で表示されるはずが、分割読み込みしているときは 黒で表示される
再現パターン
[採用情報_数字で見る会社案内](https://patterns.vektor-inc.co.jp/vk-patterns/recruit_company-guide/)
[採用までの流れ_横並び](https://patterns.vektor-inc.co.jp/vk-patterns/recruit_flow_item-side/)

**Comment by sysbird** [comment]
発生しない場合もあるので、
アイコンブロックで、途中でアイコン色 → アイコン色 ＋ 背景色 に仕様変更した影響かもしれない

**Comment by sysbird** [comment]
キーカラーに関するスタイル ` .has-vk-color-primary-color` などは
`src/blocks/button/style.scss `
に書いてある
そのためページ内に VKボタンブロックがある場合だけキーカラーが表示される現象のよう

**Comment by mtdkei** [comment]
@sysbird 

> キーカラーに関するスタイル  .has-vk-color-primary-color などは
> src/blocks/button/style.scss 
> に書いてある
> そのためページ内に VKボタンブロックがある場合だけキーカラーが表示される現象のよう

トリさんのこの書き込みが大変参考になりました。
上記の設定を変えてみましたので後ほどプルリクを上げてみます。
もし作業を進めておられたならストップしますので、その際はおっしゃっていただけたら幸いです。

**Comment by sysbird** [comment]
> 上記の設定を変えてみましたので後ほどプルリクを上げてみます。

@mtdkei 
ありがとうございます！
具体的に対応してませんので、引き続き作業してもらえると助かります〜

**Comment by sysbird** [comment]
対応していただいたので閉じます
