### ISSUE TITLE
投稿リストのブロックで投稿取得件数が-1になっており、Memory Overflowが発生してしまう

### ISSUE THREAD

**Issue by fumikito** [vektor-inc/vk-blocks-pro#2129]
https://github.com/vektor-inc/vk-blocks-pro/blob/51b2f8d9654c230ba3f3dc3a469b14fb02af4b3b/inc/vk-blocks/view/class-vk-blocks-postlist.php#L198

上記の部分、ブロック内で `WP_Query` を発行しているのですが、このとき投稿の取得件数が `posts_per_page => -1` となっています。

投稿の件数が20万件近くあるサイトで実行したところ、一度に取得する件数が多すぎてメモリオーバーフロー（256MB）になってしまいました。メモリリミットをこれ以上上げるのはあまり現実的ではないので、投稿の件数を絞るなどの対応は可能でしょうか。

現在はプラグインの該当箇所を書き換えて利用しています。
よろしくお願いします。

**Comment by kurudrive** [comment]
お世話になりますー！イシカワでございます！
対応検討いたしますので恐れ入りますがお待ちくださいませ。
逆にオススメ・都合の良い処理方法がありましたらリクエストください！

**Comment by fumikito** [comment]
@kurudrive @mtdkei  よろしくお願いします。特に注文とかはないのですが、ここの部分でWP_Queryを一度取得してから、ソートやシャッフルをしてもう一度WP_Queryを発行していますよね。

https://github.com/vektor-inc/vk-blocks-pro/blob/51b2f8d9654c230ba3f3dc3a469b14fb02af4b3b/inc/vk-blocks/view/class-vk-blocks-postlist.php#L194-L246

なので、最初の `new WP_Query( $args )` だけで完結するとよいのでは、と思いました。ページング、ソートなどはWP_Queryにやらせるのがよいと思います。

また、投稿が非常に多いサイト（10年運営していて投稿が30万件ぐらいある）だと、「日付でソートして最新8件」とかでさえ重くなることがあります。ソート対象が30万件あると、 [ファイルソート](https://qiita.com/Flipper0407/items/c24231693ec37aacd7c8) が発生することが多いからです。

おそらくこのブロックはトップページなどで使われることが多いと思われるので、「期間」の部分に「1年以内」など期間で絞り込めると嬉しいです。まあ、ブログを2年放置したら何も表示されなくなってしまうんですが……

![スクリーンショット_2024_07_25_16_27](https://github.com/user-attachments/assets/3c9485d6-bcde-4fc9-a399-1961a5efb095)

**Comment by mtdkei** [comment]
@fumikito
こちらこそよろしくお願いいたします。また、ご指摘やご提案をありがとうございます。
ご連絡の内容をもとに投稿リストブロックのposts_per_pageが-1になっている件について、対応策を検討いたします。現在、20万件のダミーの投稿を生成中ですので、少々お待ちいただけたら幸いです。
よろしくお願いいたします。

**Comment by waviaei** [comment]
@kurudrive @mtdkei 

@fumikito からの提案と併せて下記もご確認、検討ください。`posts_per_page` で指定する件数が少ない（100件とか、数百件とか）サイトと、永続的（persistent）オブジェクトキャッシュではない環境だとあまり表面化しづらいイシューですが。

投稿が非常に多い件数の場合はDBへのクエリそのものも時間が掛かり、メモリも食うのですが、post、term、postmeta の3つのオブジェクトキャッシュも場合によっては非常に時間とメモリを食います。このうち特に postmeta のキャッシュのアップデート（確認＋書き込み）は値のシリアライズとアンシリアライズも呼び出すので、ボトルネックとなっているケースが多々出て生きています。もしも postmeta のキャッシュのアップデートが、このブロックが `WP_Query` を呼び出す毎に行う必要がなければ `update_post_meta_cache` を `false` に指定していただけると処理時間とメモリ食いが更に良くなるのではと思います。

`tax_query` もない場合は `date_query` を `false` で良いかもしれません。

**Comment by mtdkei** [comment]
@waviaei
ご確認、ご提案ありがとうございます。大変勉強になりました。
投稿数が非常に多いサイトでのパフォーマンス改善のため、ご提案の以下の対策を実施してみます。
1. update_post_meta_cache を false に設定し、postmeta キャッシュのアップデートを無効化。
2. tax_query がない場合は date_query を無効化。
引き続きよろしくお願いいたします。

**Comment by kurudrive** [comment]
@fumikito @waviaei 
大変お待たせいたしました。
1.81.0.1 にて修正いたしましたのでアップデートの上ご確認くださいませ。
よろしくお願いいたします。

**Comment by fumikito** [comment]
@kurudrive ありがとうございます！

**Comment by fumikito** [comment]
@kurudrive @mtdkei 

ご報告大変遅くなりましたが、プロダクション環境でアップデートを行い、問題が解消していることを確認しました。
ありがとうございます〜！！！！
