### ISSUE TITLE
[ スライダー ] 再利用ブロックで使用するとエディタがクラッシュするっぽい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2135]
* 再利用ブロックでスライダーを配置
* 固定ページで配置・保存
* 再読み込みしたり、もう一つ配置しようとすると固まる

https://vws.vektor-inc.co.jp/forums/topic/%e5%86%8d%e5%88%a9%e7%94%a8%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%82%92%e3%83%9a%e3%83%bc%e3%82%b8%e5%86%85%e3%81%ab%e9%85%8d%e7%bd%ae%e3%81%97%e3%82%88%e3%81%86%e3%81%a8%e3%81%99%e3%82%8b%e3%81%a8#post-97841

**Comment by drill-lancer** [comment]
どうやらこの部分が無限ループしてエラーになっているようです。
https://github.com/vektor-inc/vk-blocks-pro/blob/51b2f8d9654c230ba3f3dc3a469b14fb02af4b3b/src/blocks/slider-item/edit.js#L75-L87
上記に条件をつけると解消できると思います。

**Comment by mtdkei** [comment]
マージいただいたのでCloseします。
