### ISSUE TITLE
[ グリッドカラムカード ] カラムヘッダーメディアエリアやカラムフッターボタンエリアのデフォルトを「表示」にしたい

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2136]
グリッドカラムカードを普通に挿入すると以下のようになると思います。
![image](https://github.com/user-attachments/assets/24ec4a47-1882-4224-86e3-0262ec5b147d)

この時に、グリッドカラムカードアイテムヘッダーやグリッドカラムカードアイテムフッターの中にブロックを入れることができないので「ん？」となることがあります。

カラムヘッダーメディアエリアやカラムフッターボタンエリアを「表示」にすれば出てくるのですが、どこにカード要素があるのかわからない時があります。
以下のような意見もあるので、デフォルトを「表示」にしたほうがわかりやすい気がしました。
https://x.com/chibicoo/status/1816284437102907846

**Comment by goutetsuguma** [comment]
確かに気づきにくいですね、「表示」の方が親切だと思いました！
グリッドカラムカードという名前ですし、表示されてる方がカードレイアウトって感じもしますし。

**Comment by mtdkei** [comment]
@goutetsuguma 
ご意見ありがとうございます。おっしゃる通り「表示」のほうがグリッドカラムカード感がある気がします。
後ほどプルリクをあげようと思いますので実際に実装して見てまたご確認いただけたら幸いです。

**Comment by mtdkei** [comment]
MergeされましたのでCloseします。ありがとうございました。
