### ISSUE TITLE
スライダーに高さを設定していて中に画像を設置し、中の画像の高さがスライダーの高さよりも大きい時に、編集画面で下のブロックに重なる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2139]
https://docs.google.com/spreadsheets/d/1Yvk3AN4pWn2tjL7DBe0HZm4OvvWOWhfp9ub76bAjmpQ/edit?gid=741541397#gid=741541397&range=6:6

**Comment by mtdkei** [comment]
マージしましたのでCloseします。ありがとうございました。
