### ISSUE TITLE
[分割読み込み]x-t9 のときキーカラーが表示されない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2140]
Lightning でキーカラーを設定した箇所 は x-t9 では紺色(デフォルトで)で表示されると思いますが、
分割読み込みしているときは 黒で表示されます
WP6.5、6.6
たとえば下記のパターンで発生します
[採用情報_数字で見る会社案内](https://patterns.vektor-inc.co.jp/vk-patterns/recruit_company-guide/)
[採用までの流れ_横並び](https://patterns.vektor-inc.co.jp/vk-patterns/recruit_flow_item-side/)

#2128 と関係があるかもしれない

**Comment by mtdkei** [comment]
@sysbird 
issueを立ててくださりありがとうございます！
こちらの環境では編集画面だけですが、分割読み込みがONの時にキーカラーが表示されない現象が起きました。

**Comment by sysbird** [comment]
#2128 と同じ原因っぽいのでこちらは close
