### ISSUE TITLE
[ カテゴリーバッジ ] サイトエディタでぐるぐる回ったままになってしまう

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2151]
![スクリーンショット 2024-08-02 15 09 25](https://github.com/user-attachments/assets/1b96828a-4553-481b-9044-3088cbf95f10)

**Comment by sysbird** [comment]
私もちょうどいま、投稿画面で発生してます
[ヒーローエリア_投稿リスト1件づつスライド表示](https://patterns.vektor-inc.co.jp/vk-patterns/hero-area-postlist-one-by-one-slider/)

**Comment by mtdkei** [comment]
マージされたようなのでCloseします。
