### ISSUE TITLE
[ ブログカード ] 6.6 で編集画面で編集不可能になる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2152]
既知の不具合ですがそのままというわけにもいかないので...

URLの変更とかも不可能になってしまう

https://recruit.vektor-inc.co.jp/job-category/engineer/

**Comment by mtdkei** [comment]
@kurudrive 
すみませんが、以前いくつかの環境で確認した時に再現できなくなってしまいました。(詳細は以下の最後のコメントに書いた通り)
https://github.com/vektor-inc/vk-blocks-pro/issues/2116
そのため、こちらの作業は他の方にお任せできればと思います。

**Comment by drill-lancer** [comment]
@kurudrive 
これに関してはすごく面倒な因果関係がありまして・・・

@wordpress/scripts が 28 系の場合：
 6.6 の編集画面でブログカードブロックが正常動作するが 6.5.5 以下でブロックが使えなくなる
 6.5.5 でコンソール画面を見ても特にエラーらしきものは見当たらず
 
 VK Blocks Pro においてはエラーが出ないのでなんとも言えませんが、VK Filter Search Pro では何かしらのエラーが出るので
 そのエラーを解消すれば解消される可能性があります。
 
@wordpress/scripts が 27 系の場合：
6.5.5 以下でブロックが使えるようになるが 6.6 の編集画面でブログカードブロックが正常動作しなくなる

**Comment by drill-lancer** [comment]
@mtdkei 
一時的に @wordpress/scripts を 28 系にしたことがあるため、
おそらくその時に再現できなくなっていたのかと思います。
ですが、今は 6.5.5 でブロックが読めないので @wordpress/scripts は 27 系を採用しています。
なのでいまは再現すると思います。

**Comment by drill-lancer** [comment]
@wordpress/scripts を 28 系を使う際に参考になりそうなもの
https://github.com/WordPress/gutenberg/issues/62202

**Comment by drill-lancer** [comment]
マージされたので Close
