### ISSUE TITLE
【アコーディオン】スマホやタブレットでアコーディオンを開いてスクロールしていると、アコーディオンが勝手に閉じてしまう

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2155]
スマホやタブレットなど、アコーディオンを開いてスクロールしているとアコーディオンが勝手に閉じてしまいます
調べたところ`resize`部分が原因と出てきたので、以下のウィンドウサイズが変わった時に実行の行を削除したところ、正常に動くようになったのですが、この行を削除してしまうと「デバイスごとに初期状態を設定」でそれぞれ開閉状態を変更している場合に、フロント画面でウィンドウの幅を変更してもリロードしないと設定した初期状態にならなくなってしまいます。個人的には、リロードして変更できているので問題ないような気がしますが、確認する時にリロードする手間はできてしまうので、どうなのか判断できなかったためissueにしました。

https://github.com/vektor-inc/vk-blocks-pro/blob/51b2f8d9654c230ba3f3dc3a469b14fb02af4b3b/src/blocks/_pro/accordion/view.js#L53

**Comment by mtdkei** [comment]
@goutetsuguma 
ご連絡ありがとうございます。
おっしゃる灯油、ユーザーにとって画面サイズを変えることはそんなにないと思いますので削除してプルリクを出してみます。

**Comment by goutetsuguma** [comment]
マージしたのでcloseします
