### ISSUE TITLE
[ 投稿リスト他 ] X-T9 などでボタンの位置「右」を指定しても位置が左のままになる（Lightning は問題なし）

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/vk-blocks-pro#2159]
複数の環境で X-T9 や TT4 などテーマを変更して確認しました。

- WordPress 6.6.1
- VK Blocks Pro 1.80.1.0
- X-T9 1.26.2
- TT4 1.2

投稿リストで、編集画面・フロントともにボタンの位置「右」を指定しても左のままとなるようです。
Lightning だとボタンが右に表示されます。

- 表示タイプ：カード / カード（線なし）/ カード（水平）/ メディア
- 表示要素：「ボタン」にチェック
- ボタンの位置：「右」にしても位置が変わらない
※「中央」は問題なし

[ベクトルのサイト](https://www.vektor-inc.co.jp/)のトップページ下部にある「スタッフブログ」が投稿リストです。ボタンを表示させて「右」を指定しても位置が変わらないのを確認できると思います。

投稿リストのほか、選択投稿リストと子ページリストでも同じ症状になるようです。
ちなみに、カードブロックのボタンは問題ありませんでした。（カードブロックにも表示位置の設定がありますが、投稿リストとはUIが異なるからでしょうか）

【X-T9 1.26.2】

「右」を指定しても`.text-right`がなさそうです。

<img width="1307" alt="スクリーンショット 2024-08-06 17 04 38" src="https://github.com/user-attachments/assets/45c98c4c-38ac-49d8-adbc-c526a176283c">

「中央」だと以下が適用されるようです。
`.text-center {
    text-align: center;
}`
vk-blocks-pro/build/bootstrap_vk_using.css

【Lightning 15.26.2】
Lightning では問題なし。「右」を指定すると以下が適用されます。
`.text-right {
    /* text-align: right !important; */
}`
lightning/_g3/assets/css/style.css

<img width="1307" alt="スクリーンショット 2024-08-06 16 19 45" src="https://github.com/user-attachments/assets/bfffe8a8-7377-471e-9aef-648dd43af365">

**Comment by goutetsuguma** [comment]
マージしましたのでCloseします
