### ISSUE TITLE
[スライダー]編集画面で「ブロックのリカバリー」が出ることがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2160]
全幅のスライダーを通常幅に変更したときに、再編集しようとすると「ブロックのリカバリー」が表示されます
develop、master
ローカル環境とテストサイトで確認
![s-item](https://github.com/user-attachments/assets/d06d3b43-7d8c-4a7d-bfa8-e6abb6f8dc62)

再現手順
1. 全幅のスライダーを作成(または、パターン[ヒーローエリア_ Lightning風スライダー ](https://patterns.vektor-inc.co.jp/vk-patterns/hero-area-default-slider/)をコピペ)、保存
2. スライダーを通常幅に変更、保存
3. 編集画面をリロード、またはダッシュボードで入り直す
4. 「ブロックのリカバリー」が表示

**Comment by drill-lancer** [comment]
@sysbird 
試してみましたが私の環境ではリカバリーが出ませんが・・・
パターンのほうで修正されたということでしょうか？

**Comment by goutetsuguma** [comment]
わたしは再現手順でリカバリーがでました。
[デモサイト](https://demo.dev3.biz/lightning-g3-pro)でも確認できました。

**Comment by drill-lancer** [comment]
@sysbird @goutetsuguma CC: @kurudrive 
幅の調整ってツールバー「赤枠」と設定画面「青枠」どちらで行ってますか？

![width setting](https://github.com/user-attachments/assets/9b1c8b8d-62dd-463e-9086-7c3a96b15df5)

青枠の方は廃止しようかと思っていますがどうでしょうか？

**Comment by goutetsuguma** [comment]
@drill-lancer 
わたしは「赤枠」の方で幅調整してます。

> 青枠の方は廃止しようかと思っていますがどうでしょうか？

Outerも昔レイアウト設定に幅設定があって、WordPress標準ブロックの仕様に合わせてツールバーからの設定にしたとおもいますので、廃止で良いのではないでしょうかね

**Comment by sysbird** [comment]
マージされたのでclose
ありがとうございましたー
