### ISSUE TITLE
[子ページリスト]ボタンが表示されないことがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2169]
子ページリストブロックの表示要素でボタンをONしているのに ボタンが表示されないことがある
* WP6.5、6.6 
* tt-3、tt-4 のとき発生
* x-t9、Lightning でもたまに発生する気がする
* 編集画面で見えるけどフロントエンドで見えない場合もある → vk-block-test.vs4(Lightning) の p=586
* このときボタンは position: absolute; になってて、要素はあるけど見えないっぽい

**Comment by mtdkei** [comment]
ありがとうございます。
調べてみたら表示タイプを「カード(水平)」にしたら、子ページリストだけでなく、投稿リストや選択投稿リストでも発生するようでしたので、その方向で調査して修正してみます。

**Comment by sysbird** [comment]
> 表示タイプを「カード(水平)」にしたら、子ページリストだけでなく

子ページリストのデフォルトが「カード(水平)」だからそう見えたんですね
気づいてくれてありがとうございます！

**Comment by sysbird** [comment]
対応・マージされたので close
ありがとうございます！
