### ISSUE TITLE
[ネガティブマージン] VKブロックでも使いたいです

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2170]
VKブロックにも ネガティブマージンが設定できたらよいとおもいませんか！？

**Comment by mtdkei** [comment]
ネガティブマージンいいですね！
例えばどのブロックで使えるようになったらいいでしょうかね？

**Comment by sysbird** [comment]
思いついたのは スライダーを使っていたときだったんですが、
グループブロックで囲えば、VKブロックでもなんでもネガティブマージン が使えることに気づきました！

**Comment by sysbird** [comment]
なくても大丈夫そうなので closeしておきます
