### ISSUE TITLE
［分割読み込み設定］有効にすると、カスタムCSSに書いたbefore、after 要素が表示されなくなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2178]
https://github.com/vektor-inc/vk-patterns/issues/355#issuecomment-2276983388

パターンを確認していて、［分割読み込み設定］を有効にすると、カスタムcssに書いたbefore、after 要素がフロント画面で表示されなくなるようでしたのでissue化します

beforeの場合はカスタムcssの識別表示にスタイルが当たっていて編集画面では表示されますが、フロント画面では要素自体がなくなります。

---
![スクリーンショット 2024-08-19 13 27 09](https://github.com/user-attachments/assets/d1f0ad8c-e33a-4564-bc07-bbfdc0331b64)

---
分割読み込み設定を有効にして、例えばこのパターンの見出しの下線などをフロント画面で確認すると症状が確認できます。
https://patterns.vektor-inc.co.jp/vk-patterns/app-product-introduction/

**Comment by mtdkei** [comment]
@goutetsuguma 
私の環境だけかもですが、コアの見出しブロックだけ擬似要素のbeforeやafterが効いてないみたいでした。
カスタムCSS全体での分割読み込みに対応するコードは出来たのですが、どうしても上記の原因が原因が特定できず、一旦「作業中」のラベルは外しました。
勘違いでしたら引き続き作業を行ないますが、もし可能でしたら、 @kurudrive @drill-lancer @mthaichi  どなたかに上記の原因をみていただけたら嬉しいです。

**Comment by mtdkei** [comment]
@goutetsuguma 
Cc: @kurudrive @drill-lancer @mthaichi 

コアの見出しブロックだけ擬似要素のbeforeやafterが効いてない原因がようやくわかりました。
こちらで作業します。

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
