### ISSUE TITLE
［タブブロック］［フォーラムより］先頭の Tab Item を複製するとレイアウトがおかしくなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2181]
フォーラムより

> タブブロックの先頭の Tab Item を複製するとレイアウトがおかしくなります。

先頭の Tab Item を複製するとレイアウトがおかしくなりますが、複製したTab Item をクリックすると正常に戻るようでした。

https://vws.vektor-inc.co.jp/forums/topic/%e3%82%bf%e3%83%96%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%81%ae%e5%85%88%e9%a0%ad%e3%81%ae-tab-item-%e3%82%92%e8%a4%87%e8%a3%bd%e3%81%99%e3%82%8b%e3%81%a8%e3%83%ac%e3%82%a4%e3%82%a2%e3%82%a6%e3%83%88#post-100036

**Comment by mtdkei** [comment]
マージされたのでCloseします。ありがとうございました。
