### ISSUE TITLE
[ グリッドカラムカード ] 同期パターンにするとフリーズするっぽい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2187]
https://vws.vektor-inc.co.jp/forums/topic/100259

**Comment by drill-lancer** [comment]
https://github.com/vektor-inc/vk-blocks-pro/blob/619e3614ab339eb434ecaf7e7c5e8923455b6c62/src/blocks/_pro/gridcolcard/edit.js#L58-L91

https://github.com/vektor-inc/vk-blocks-pro/blob/619e3614ab339eb434ecaf7e7c5e8923455b6c62/src/blocks/_pro/gridcolcard-item/edit.js#L89-L149

上記２つをコメントしたら正常に動くようになりました。

**Comment by drill-lancer** [comment]
@kurudrive 
親子の値の変更がバッティングしてエラーにバッティングしてエラーになっているような気がします。
多分このあたりの仕様を考え直すことから始めることになりそうです

**Comment by kurudrive** [comment]
close as completed
