### ISSUE TITLE
VK Blocks ボタンブロックで背景色をなくしテキストのみに設定すると、ホバーした時何も見えなくなる

### ISSUE THREAD

**Issue by YukinobuAsakawa** [vektor-inc/vk-blocks-pro#2193]
以下のページの設定のように、ボタンブロックを使う時にテキストのみに設定すると、ホバーした時には文字列が白になって何も見えなくなってしまうことをたまたま見つけました。

- [【無料で使える】WordPressプラグイン VK Blocks のスライダーを紹介](https://www.vektor-inc.co.jp/post/how-to-use-slider-block/)
- [WordPress フォトコントリビューターになろう！ベクトルでもフォトウォークをやってみた](https://www.vektor-inc.co.jp/post/photo-contributor/)

WordPressプラグイン VK Blocks のスライダーを紹介のページで言えば、「プレミアムパターン 学習塾トップ」、「プレミアムパターン 工務店TOP」の部分のリンクボタンが該当します。
なお、テキストの色が、#1c45ab に設定されている時には、現象が発生していないようです。

現象を確認した環境
- WordPress Core Version: 6.6.1
- php_version: 8.0.30 64bit
- MySQL Version: 8.0.30
- Theme: X-T9 

![スクリーンショット 2024-08-27 17 44 50](https://github.com/user-attachments/assets/dc693311-28cc-40fe-9132-8dba801c2d08)

**Comment by sysbird** [comment]
調べます！

**Comment by sysbird** [comment]
x-t9 の修正で対応済みの件かもしれません
[css微修正:vkボタン塗りのhover時とコアOutlineのhover時の白文字が一部除外指定でつかないように調整 #297 ](https://github.com/vektor-inc/x-t9/pull/297)

こちらのリリース待ちでしょうか？

**Comment by kurudrive** [comment]
@YukinobuAsakawa @sysbird 

1.26.3 リリースいたしました。こちらで改善されていると思いますのでアップデートの上ご確認ください！

**Comment by YukinobuAsakawa** [comment]
@kurudrive @sysbird 
お返事が遅くなってすみません🙇
確認しました。該当の問題は解消されました。
ご対応ありがとうございました！
本件はクローズでよろしいかと思います。

**Comment by kurudrive** [comment]
ありがとうございました！
