### ISSUE TITLE
【相談】［投稿リスト］編集画面で投稿のリンクをクリックしてしまうことが何度かあるので、編集画面ではリンクしない方が便利かもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2198]
編集画面で投稿のリンクをクリックしてしまうことが何度かあるので、編集画面ではリンクしない方が便利かもしれないなとたまに思うのですが、みなさんはいかがでしょうか？（ここからリンクして投稿を確認する人はいるのかな）

そもそも投稿リストブロックよりもクエリーループブロックで投稿一覧を作成すれば良い話でもあります。

![スクリーンショット 2024-09-02 10 02 57](https://github.com/user-attachments/assets/6fbd4c85-5c77-4a1b-b5d3-aebc9867f389)

**Comment by mtdkei** [comment]
@goutetsuguma 
確かにユーザー時代に間違えてクリックして困ることが何回かありました。
個人的にはなくてもいいかなと思いますが要路してはどうなんでしょうね。

**Comment by sysbird** [comment]
たぶん編集画面ではリンクしないブロックがほとんどですね
こちらも編集画面ではリンクしないでくれると嬉しいです

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
