### ISSUE TITLE
【意見調整待ち】[ ボタン ] サブテキストをメインのテキストの上か下か選べる機能が欲しいという意見がありました

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2202]
https://x.com/tomonao1966/status/1832423301907673487

**Comment by sysbird** [comment]
ボタンのテキストは改行したり、インライン文字サイズを設定したり、アイコンサイズも変更できるので、そのほうがサブテキストを使うより自由かもしれないです

**Comment by mtdkei** [comment]
@sysbird 
確かに考えてみればそうですね！流石です。
ユーザー向けにそういうパターンやブログ記事か何かを提供できればわかりやすいのかもしれません！
一旦Closeします。

**Comment by sysbird** [comment]
たしかに！
あまり知られてない？から、とりいそぎつぶやいてみよう
