### ISSUE TITLE
パンくずリストの処理の再調整

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2206]
https://github.com/vektor-inc/vk-blocks-pro/pull/2201

ごめんなさい。伝達不足でした (￣人￣)

以下の理由で今回の変更の再調整をよろしくお願いいたします。

* VK Blocks Pro は独立したプラグインなので、可能な限り特定のテーマのためだけの処理を VK Blocks Pro に含めるのは避けたい
  - 他のテーマでは不要なCSSを読み込む事になるため
  - 特定のテーマのためだけの処理が入っていると、事情を知らない人がコードを見た時に理解しにくくなる
  - 事情を知らない人がコードを見た時にその処理を不要だと思って削除してしまう事につながる
* テーマが出力している機能の制御を、ブロック拡張するプラグイン側で行う事がおかしい（ユーザーが見つけにくい）
  - Lightning のパンくずであれば Lightning 本体か Lightning の機能拡張プラグインである G3 Pro Unit 側から制御する
  - VK Blocks のパンくず設定機能はパンくずブロック用なので、逆にテーマ側に影響があるのはよくないようにも思う。

必要に応じて composer のライブラリ側でセパレーターの制御機能・UIを調整実装して、
カスタマイザー用の制御UIを作っておいて、テーマ側からそのUIを呼び出すなど
（テーマ側に直接書いた方が可読性が良ければテーマ側に書くのもあり）

- [x] VK Blocks Pro のパンくずのセパレーター機能がちゃんと動作するように（現状ここはOK）
- [x] テーマ固有の処理（特定のテーマだけのCSSセレクタによるCSSの追加など）をしないように

* VK Blocks Pro のパンくずのセパレーター指定は Lightning や Katawara には影響しなくても良い
* VK Blocks Pro がなくてもセパレーターを変更できるように...は、元々CSS少し書けば変更できる部分なので、UIで実装しなくても良いのかなーという気がします。Lightning自体既に設定UIが多くて、実装しても結局ユーザーが見つけられないとかになりがちですし、実装してしまうとその分コードが多くなったり、不具合の発生につながるのでメンテナンスコストがあがるからです。でも「いやー、それはあった方がいいっすよ！」って事であれば G3 Pro Unit 側から実装いただいてもかまいませんー。Lightning G3 Pro Unit に関してはカスタマイザにパンくずリストの設定はある...けど Lightning レイアウト設定の中か... やるなら Lightning レイアウト設定からは外に出した方が良いですね。
Katawaraは...もともと機能追加はしないという前提での価格設定なので、該当機能が共通ライブラリに実装済みで瞬殺で反映させられるというレベルでなければ、わざわざ実装しなくてもいいかなと思ったりします。

**Comment by mtdkei** [comment]
お手数をおかけしてすみません。見直してみます。

**Comment by mtdkei** [comment]
とりあえずマージしてもらった分は戻して、パンくずが効かない不具合を見直します。

**Comment by sysbird** [comment]
> * VK Blocks Pro は独立したプラグインなので、可能な限り特定のテーマのためだけの処理を VK Blocks Pro に含めるのは避けたい

@kurudrive 
これ気になってました
テーマ (Lightning / x-t9) のほうには Outer の対応 CSS など書いてあるので、逆もOKかと思い確認してました
テーマに、VK Blocks のCSS 書くのはアリでしょうか？

**Comment by mtdkei** [comment]
マージされたのでCloseします。ありがとうございました。

**Comment by kurudrive** [comment]
@sysbird @goutetsuguma @mtdkei 

> テーマ (Lightning / x-t9) のほうには Outer の対応 CSS など書いてあるので、逆もOKかと思い確認してました
テーマに、VK Blocks のCSS 書くのはアリでしょうか？

テーマ側に VK Blocks の上書きCSSを書いているのは、
そのテーマ固有の仕様によって処理が異なる事に対する補正や、
見た目を扱う テーマ に最適化した表示にするためです。
