### ISSUE TITLE
無料版にデプロイがこけるので助けて (￣人￣)

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2209]
@drill-lancer よろしくお願いいたします (￣人￣)

**Comment by drill-lancer** [comment]
@kurudrive 
[pre_1.84.0.3](https://github.com/vektor-inc/vk-blocks-pro/tree/pre_1.84.0.3) で通るようになりました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
