### ISSUE TITLE
【誰か再調査】分割読み込みに指定してなくても個別のブロックのCSS読み込むようになってない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2218]
1. 分割読み込みを指定してない
2. 適当に VK Blocks のブロックを配置
3. ソースを開くと <link rel='stylesheet' id='vk-blocks/tab-css' などを読み込んでしまってる
4. でも <link rel='stylesheet' id='vk-blocks-build-css-css' も普通に読み込まれてる。
5. 4 の CSS の中身に 3 のCSSの中身が含まれてる

今のWordPressが分割読み込み以外の方法の指定が聞かなくなってるかも...

**Comment by mtdkei** [comment]
@kurudrive 
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/blocks/icon/index.php
にある
```
	if ( ! is_admin() ) {
		wp_register_style(
			'vk-blocks/icon',
			VK_BLOCKS_DIR_URL . 'build/icon/style.css',
			array(),
			VK_BLOCKS_VERSION
		);
    }
```
を
```
	if ( ! is_admin() && VK_Blocks_Block_Loader::should_load_separate_assets() ) {
		wp_register_style(
			'vk-blocks/icon',
			VK_BLOCKS_DIR_URL . 'build/icon/style.css',
			array(),
			VK_BLOCKS_VERSION
		);
    }
```
にしたら、
```
<link rel='stylesheet' id='vk-blocks/icon-css' href='http://example.com/wp-content/plugins/vk-blocks-pro/build/icon/style.css?ver=1.85.0.0' media='all' />
```

が分割読み込みがONの時にだけ読み込まれるようになりました。
ブロックのindex.phpを一つずつ変更すればいいのですが、もう少し共通化できなものもかと思ってます。
できなさそうならそのまま作業しちゃいますが、何かアイディアがあれば嬉しいです。

**Comment by kurudrive** [comment]
@mtdkei あーなるほど...普通に前から効いてなかったっぽいデスネ....。

ぱっと見 index.php をそれぞれ書き換える感じで良いのではないかと思いますがどうでしょう？
@mthaichi @drill-lancer

**Comment by mtdkei** [comment]
https://github.com/vektor-inc/vk-blocks-pro/blob/7f9ba73708bac20a72a93b901310fe54b4681c74/inc/vk-blocks/class-vk-blocks-block-loader.php#L317

ひたすら過去の`inc/vk-blocks/class-vk-blocks-block-loader.php`をビルドした結果、上記のプルリクの時から、現在のWordPressではブロック別のCSSとblock-build.cssのCSSが出るようにっているようでした。
```
<link rel='stylesheet' id='vk-blocks-build-css-css' href='http://vk-lightning.local/wp-content/plugins/vk-blocks-pro/build/block-build.css?ver=1.85.1.1' type='text/css' media='all' />
```

上記に書いてある
```
if ( function_exists( 'wp_should_load_separate_core_block_assets' ) && ! empty( $vk_blocks_options['load_separate_option'] ) ) {
```

を修正前の

```
if ( function_exists( 'wp_should_load_separate_core_block_assets' ) && isset( $vk_blocks_options['load_separate_option'] ) ) {
```

に戻したところ、二重には読み込まなくなりましたが、block-build.cssは生成されず、個別のブロックのcssだけを読み込む状況でした。

**Comment by mtdkei** [comment]
ひたすら過去の`inc/vk-blocks/class-vk-blocks-block-loader.php`をビルドした結果、以下のプルリクの時から、
 
> https://github.com/vektor-inc/vk-blocks-pro/blob/7f9ba73708bac20a72a93b901310fe54b4681c74/inc/vk-blocks/class-vk-blocks-block-loader.php#L317
 
現在のWordPressではブロック別のCSSと以下のblock-build.cssのCSSが出るようにっているようでした。

```
<link rel='stylesheet' id='vk-blocks-build-css-css' href='http://vk-lightning.local/wp-content/plugins/vk-blocks-pro/build/block-build.css?ver=1.85.1.1' type='text/css' media='all' />
```

修正された以下のコードを

```
if ( function_exists( 'wp_should_load_separate_core_block_assets' ) && ! empty( $vk_blocks_options['load_separate_option'] ) ) {
```

修正前の以下のコードに戻したら

```
if ( function_exists( 'wp_should_load_separate_core_block_assets' ) && isset( $vk_blocks_options['load_separate_option'] ) ) {
```

二重には読み込まなくなりましたがblock-build.cssは生成されず、個別のブロックのcssだけを読み込む状況でした。

**Comment by mthaichi** [comment]
「分割読み込みが無効になっているのに、個別CSSが読み込まれる」問題については、おそらくこれが原因かなと。コア側で deprecated になっている仕様でした。

https://github.com/WordPress/wordpress-develop/blob/835f864d4ea376eb79844eb6a941250762de3c12/src/wp-includes/class-wp-block-type.php#L261C1-L273C4

で、

https://github.com/vektor-inc/vk-blocks-pro/blob/31ce8897e4ca1b17596db8af720782395ad94e45/inc/vk-blocks/class-vk-blocks-block-loader.php#L199-L214

ここの `$args['style']  = null;`  を `$args['style_handles']  = array();`  に変えると元通りの挙動になりました。
これについては、妥当性をもうちょっと検討したうえで、修正すればよいかなと。　

その上で、個別のブロックの問題があれば、個別対応ってことでいかがでしょうか。

**Comment by mtdkei** [comment]
マージされましたでCloseします。ありがとうございました。
