### ISSUE TITLE
テーブルのヒントがデグれって使えなくなっている

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2221]
@drill-lancer 

https://github.com/vektor-inc/vk-blocks-pro/commit/a189242ed02755399eb38dd1822b181bc54e3679　で revert しちゃってるからだと思うけどこれは何か理由があって？

https://github.com/vektor-inc/vk-blocks-pro/pull/2197/files

**Comment by kurudrive** [comment]
@drill-lancer 

あぁ...たぶん"取り消したのが最新の操作"なので、その後でテーブル関連の変更を develop を後からmasterにマージしようが、そこはもう消された方が最新なので何もしないという状態ですね。

と、言うわけで https://github.com/vektor-inc/vk-blocks-pro/pull/2197/files の変更部分をdevelop に再度手動で反映させておいてくださいー  (￣人￣)

**Comment by drill-lancer** [comment]
@kurudrive 
手動で直しておきました＆フロントで効かなかったようだったので効くように変更しました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
