### ISSUE TITLE
[ 固定表示 ] 「下部からの固定表示」という項目を追加したい

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2226]
現在の設定では「上部からの固定位置」しかないため
https://patterns.vektor-inc.co.jp/vk-patterns/18641/
のようなパターンの時にカスタムCSSで
```
  bottom: 0;
  top: unset !important;
```
 をかくことになってしまうため。

**Comment by kurudrive** [comment]
close as completed
