### ISSUE TITLE
［カテゴリーバッチ］編集画面のブロック一覧に「Pro」マークをつける

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2233]
[カテゴリーバッチ](https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-blocks/vk-blocks-blocks/category-badge/)はPro版なので、編集画面ブロック一覧画面に「Pro」マークをつける。

https://github.com/vektor-inc/vk-blocks-pro/blob/master/editor-css/_editor_before.scss

▼ このマークをカテゴリーバッチにも追加する
![スクリーンショット 2024-09-26 18 39 17](https://github.com/user-attachments/assets/aa73f254-3a2b-4adf-b7bb-869a0abd051b)

**Comment by mtdkei** [comment]
マージされていましたのでCloseします。ありがとうございました。
