### ISSUE TITLE
[ スライダー ] 複数表示するときの注意書きがあったほうがよいかな

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2234]
表示枚数 + 1 のスライドアイテムが必要です
※ Swiper の仕様

https://github.com/user-attachments/assets/8fd75bd3-ba53-409c-8889-95c56caaec26

**Comment by kurudrive** [comment]
現状でもアラートは表示されるようになっている

![スクリーンショット 2024-10-03 14 07 08](https://github.com/user-attachments/assets/46c25d66-8124-4306-86c1-c938ab3b439a)

これは表示されている枚数 + 1 が最低必要だからこのようにしている。

しかしながら、「アクティブスライドを中央にする」が有効の場合、1.5 に指定しても初期表示では3枚表示されているので、Swiper 的には +1 枚の4枚必要という事になる。
つまり、アクティブスライドが中央じゃない場合は現行のメッセージで良いが、アクティブスライドが中央 の場合は

> アクティブスライドが中央 の場合は、配置されたスライドアイテムの数は、1ビューに表示したいアイテム数＋2以上である必要があります。

を表示する。

※ メッセージを表示するロジックも調整する必要がある

**Comment by mtdkei** [comment]
マージしましたのでCloseします。ありがとうございました。
