### ISSUE TITLE
[ タブ ] タブブロックにgooglemapのiframeを設置した時、編集画面でアクティブになっていたiframeしか表示されなくなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2235]
タブブロックを使って、各タブアイテムにグーグルマップのiframeの埋め込みコードを「カスタムhtml」ブロックに埋め込み。編集を更新したときにアクティブになっていたタブアイテムしかiframeのマップが表示されない。

[デモサイト：実際の症状をログインして確認できます。](https://demo.dev3.biz/lightning-g3-pro/tab-test/)

[元の質問はこちら](https://docs.google.com/spreadsheets/d/1Yvk3AN4pWn2tjL7DBe0HZm4OvvWOWhfp9ub76bAjmpQ/edit?gid=627965319#gid=627965319&range=B6)

いったん、good first issueにします。
（調査して実装が難しそうであれば相談）

**Comment by mtdkei** [comment]
すみません、good first issueに気づかずにちょっと作業しちゃってました。
確かにデモサイトや他のサーバー上では再現できたのですが、なぜか自分のローカルでは再現できないのでbuildしてから生成されたものを自サーバー上のサイトに移して確認してました。
viewを書き換えたらできるようでしたので調整していきます。

**Comment by goutetsuguma** [comment]
調整ありがとうございます！マージしましたのでCloseします

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
