### ISSUE TITLE
コアの個別CSS処理の削除

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2243]
https://github.com/vektor-inc/vk-blocks-pro/pull/2241 からのひっこし　↓

以前[[ core/heading, core/image, core/table ] 分割読み込み時にフロントエンドにCSSが反映されない現象を修正 ](https://github.com/vektor-inc/vk-blocks-pro/pull/2130)というプルリクを出していました。
こちらのプルリクをビルド後、/inc/vk-blocks/class-vk-blocks-block-loader.php の core/heading, core/image, core/tableの読み込み対応部分を削除しても分割読み込みのON/OFFの影響を受けずにCSSが読み込まれました。

そのため、一応ブロックの読み込み問題に関係してそうなのでこちらのプルリクで該当箇所を削除してもいいでしょうか？(むしろ削除しないと分割読み込みがオフの時にbuild-cssとブロックごとのコアのcssがそれぞれに読み込まれます。)

別のプルリクの方が良さそうでしたらこちらがマージされた後プルリクを立てます。

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
