### ISSUE TITLE
[LinkToolbar] 編集画面でコンソールエラー

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2246]
アイコンブロックの対応をしてて気づきました
例えば、LinkToolbar 対応済みのグループブロックで リンクを設定し、編集画面上でクリックした際にコンソールエラーが表示されます
表示されないときもあります
対象ブロックを何度かクリックすると出ます
グループにリンクを設定して、余白多めにしておくと確認しやすいです
ローカル環境のほか、パターンライブラリでも再現

もしかしたらリンクに飛ばないようにしているなにかの処理でしょうか？

----------
クロスオリジン要求をブロックしました: 同一生成元ポリシーにより、https://example.com/ にあるリモートリソースの読み込みは拒否されます (理由: CORS ヘッダー ‘Access-Control-Allow-Origin’ が足りない)。ステータスコード: 200
----------

**Comment by mtdkei** [comment]
ありがとうございます。
調べてみたところ、リンク設定時に外部サイトに対してタイトルやファビコンなどの情報を取得しようとする際に発生しているもののようでした。直してみます。

**Comment by goutetsuguma** [comment]
MergeしましたのでCloseします、ありがとうございました！
