### ISSUE TITLE
[ table ]スクロールヒントの部分が、「非表示設定」を設定した時に非表示になるように

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2248]
> テーブルに対して
> 「テーブルの水平方向スクロール」をオンにし
> ブレイクポイントを「モバイル」とし
> 「スクロールメッセージを表示」をオンにした状態で
> 
> そのテーブルを非表示にした時に、モバイル（スマホ）で表示すると
> テーブルは表示されないが、スクロールメッセージだけが表示されます。
> 

https://vws.vektor-inc.co.jp/forums/topic/%e3%83%86%e3%83%bc%e3%83%96%e3%83%ab%e3%82%92%e9%9d%9e%e8%a1%a8%e7%a4%ba%e3%81%ab%e3%81%97%e3%81%9f%e6%99%82%e3%80%81%e3%82%b9%e3%82%af%e3%83%ad%e3%83%bc%e3%83%ab%e3%83%a1%e3%83%83%e3%82%bb%e3%83%bc?view=all#post-101400

**Comment by mtdkei** [comment]
マージいただきましたのでCloseします。ありがとうございました。
