### ISSUE TITLE
[ スライダーブロック ] develop ブランチ（1.86.0）だと vektor-inc.co.jp のスライダーブロックの中身が上揃えになってしまうのを直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2259]

**Comment by sysbird** [comment]
/wp-content/plugins/vk-blocks-pro/build/slider/style.css
が読み込まれていないようです

**Comment by mtdkei** [comment]
確かに指定のcssが読み込まれていないようでした。
以下のブランチで変更していただいた内容を元に戻すと読み込まれました。
https://github.com/vektor-inc/vk-blocks-pro/pull/2245/files

ただ、これを元に戻すと今度は分割読み込みが OFF でも分割読み込み用のスタイルが読み込まれて、build-cssと二重にcssが出力されるようです。

今はその原因がわからないので開発の方を新たに追加させていただきました。

**Comment by mtdkei** [comment]
確かに指定のcssが読み込まれていないようでした。
以下のブランチで変更していただいた内容から元に戻すと読み込まれました。
https://github.com/vektor-inc/vk-blocks-pro/pull/2245/files

ただ、これを元に戻すと今度は分割読み込みが OFF でも分割読み込み用のスタイルが読み込まれて、build-cssと二重にcssが出力されるようです。

調査中ですが今はその原因がわからないので開発の方を新たに追加させていただきました。
@drill-lancer @mthaichi

**Comment by mtdkei** [comment]
先ほどわかったことですが、どうやら
`/build/block-build.css?ver=1.86.0.0`
よりも
`/vendor/vektor-inc/vk-swiper/src/assets/css/swiper-bundle.min.css?ver=11.0.2`
の方が優先されているために、issueの現象が起きていました。

検証ツール上で
```
<link rel="stylesheet" id="vk-swiper-style-css" href="http://vk-lightning.local/wp-content/plugins/vk-blocks-pro/vendor/vektor-inc/vk-swiper/src/assets/css/swiper-bundle.min.css?ver=11.0.2" type="text/css" media="all">
```
の後に
```
<link rel="stylesheet" id="vk-blocks-build-css-css" href="http://vk-lightning.local/wp-content/plugins/vk-blocks-pro/build/block-build.css?ver=1.86.0.0" type="text/css" media="all">
```
を挿入したところ、issueのような現象は無くなりました。

ただし、上記は分割読み込みがOFFの時だけの対応となります。
トリさんのおっしゃっていた
> /wp-content/plugins/vk-blocks-pro/build/slider/style.css
> が読み込まれていないようです

の原因はわかりません。

**Comment by goutetsuguma** [comment]
マージしましたのでCloseします。ありがとうございました！
