### ISSUE TITLE
[ リンクコンポーネント ] tel:を入力するときにhttp://がつかないようにしたい

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2264]
https://vws.vektor-inc.co.jp/forums/topic/%e3%80%90%e6%a9%9f%e8%83%bd%e8%bf%bd%e5%8a%a0%e8%a6%81%e6%9c%9b%e3%80%91%e3%82%b0%e3%83%ab%e3%83%bc%e3%83%97%e3%83%bb%e3%82%ab%e3%83%90%e3%83%bc%e3%83%bb%e3%82%ab%e3%83%a9%e3%83%a0%e3%81%ae%e3%83%96

**Comment by mtdkei** [comment]
tel:の時はそのまま返すようにすればいいのでアンカーリンク(#)や内部リンク(/)と同じ処理にすればできると思います。

**Comment by MasayaMORIMOTO** [comment]
こちらの件、 mailto: リンクへの対応は不要でしょうか？
（ mailto: でも http:// がつきます）

**Comment by drill-lancer** [comment]
@MasayaMORIMOTO 
後々お問い合わせが来る可能性があるので今のうちに mailto:  も対応しておくのもアリだと思います。

**Comment by kurudrive** [comment]
@MasayaMORIMOTO mailtto もよろしくお願いいたします (￣人￣)

**Comment by mtdkei** [comment]
マージされたようですのでCloseします。ありがとうございました。
