### ISSUE TITLE
[WP 6.7] ブロック名が翻訳されないように見える

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2269]
WP 6.7 上でブロック名とブロックの説明が翻訳されないように見えます
とりいそぎメモしておきますので、もし私だけでしたらご指摘お願いします
![block](https://github.com/user-attachments/assets/5a410549-93d3-4377-878c-0e601a145883)

**Comment by sysbird** [comment]
他にも英語/日本語と混在してる箇所があるので、コアの beta2版の問題かもしれないです

**Comment by kurudrive** [comment]
@mthaichi 
言語ファイルは ja.mo などのファイル名じゃないとダメになったようです。

**Comment by mtdkei** [comment]
@mthaichi @sysbird  (CC: @kurudrive )
調べるヒントになるかわかりませんが、偶然見つけたので共有します。
アラートブロックですが、Alertブロックそのものを出そうとすると英語でしか出てこないのですが「Success」「Info」「Warning」「Danger」の方は `/アラート` と入力した時に出てきました。
![image](https://github.com/user-attachments/assets/54c32e12-770a-4dcf-9083-bd6895f68dcb)

**Comment by mtdkei** [comment]
@mthaichi @sysbird @kurudrive 

	// 翻訳を実行
	add_action(
		'plugins_loaded',
		function () {
			// Load language files.
			$path = dirname( plugin_basename( __FILE__ ) ) . '/languages';
			load_plugin_textdomain( 'vk-blocks-pro', false, $path );
		}
	);
	
	を

	// 翻訳を実行
	add_action(
		'plugins_loaded',
		function () {
			// 確実にプラグインのディレクトリ内から翻訳ファイルを読み込む
			$path = plugin_dir_path( __FILE__ ) . 'languages';
			load_textdomain( 'vk-blocks-pro', $path . '/vk-blocks-pro-ja.mo' );
		}
	);	
	
	にしたら日本語になりました。こちらでプルリク出してみます。

**Comment by mtdkei** [comment]
https://github.com/vektor-inc/vk-blocks-pro/pull/2316 をマージしましたのでこちらはCloseします。ありがとうございました。
