### ISSUE TITLE
[ 目次 ] npm run build:cacheやnpm run build:devを行うとエラーになります

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2273]
developブランチ上での目次ブロックが新規追加・設置済みに関わらずエラーになります。

![スクリーンショット 2024-10-21 12 28 03](https://github.com/user-attachments/assets/2a3d8107-e3a4-4bcf-864f-6b40270e25eb)

フロントエンドでもこのように見出しを読み取れてません。

![スクリーンショット 2024-10-21 12 30 03](https://github.com/user-attachments/assets/f2e7bd46-ad35-4de5-9a1a-c1c4539cc9c9)

なお、すでに目次ブロックがこのエラーが起こる前から設置済みの場合、フロントエンドでは正常に機能されていました。

![image](https://github.com/user-attachments/assets/1a362981-5574-446e-9bcf-402b4e920587)

masterブランチででは正常でした。

![スクリーンショット 2024-10-21 12 32 57](https://github.com/user-attachments/assets/33153a1c-fda9-4599-847a-763584afa23d)

![スクリーンショット 2024-10-21 12 32 29](https://github.com/user-attachments/assets/5ccc59cc-01f0-4d5a-9d8e-c7e890a2efc1)

**Comment by mtdkei** [comment]
すみません！composer installしたら直りました。
こちらCloseします。

**Comment by mtdkei** [comment]
複数のローカル環境で同じ現象が引き続き起こっているのでreopenしました。現在はdevelopだけでなくmasterでも起こります。
どうやら`npm run build:cache`や`npm run build:dev`を実行するとissueの現象になるようです。`npm run build`では正常に表示されました。

**Comment by mthaichi** [comment]
Memo: 目次テーブルを react-dom-serverを使わずに構築すれば良し。
