### ISSUE TITLE
[ Outer ]スタイルの色からテキスト>色が選べるように

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2276]
グループブロックのように ブロックの設定の「スタイル」＞「色」「テキスト」のカラーが選べると便利そうだと思いました。背景はOuterブロックの独自の設定項目がありますので、今回はテキストのみがほしいですが難しいでしょうか。独自設定になるのでしょうか

![スクリーンショット 2024-10-22 15 25 06](https://github.com/user-attachments/assets/88a102f7-9197-4809-a156-fa5871067cf1)

▼欲しいと思ったきっかけ
スライダーブロックのアイテム内にOuterブロックをフェードで入れた場合、中の文字は同じ定型文を使うので同期パターン（旧再利用ブロック）で囲うと運用する際に便利ですが、[このパターンの場合](https://patterns.vektor-inc.co.jp/wp-admin/post.php?post=18846&action=edit)Outerからテキストの色が設定できないため、見出しや段落ブロックから色を変えています。そうしますと、再利用ブロックを編集する際にテキストが白色で見えづらいため、（色を変えれば良いのですが）もしOuterブロックからテキスト色が変えれたら、編集しやすそうと思ったためです

![スクリーンショット 2024-10-22 18 12 52](https://github.com/user-attachments/assets/0031df3a-27d1-4074-80d4-833702e475ff)

**Comment by mtdkei** [comment]
@goutetsuguma 
コアで実装できそうでした。こんな感じでいかがでしょう？OKでしたらやってみます！
![スクリーンショット 2024-10-23 16 09 50](https://github.com/user-attachments/assets/551f5499-eea2-49fb-bc70-8bbaf8de3892)
![スクリーンショット 2024-10-23 16 10 25](https://github.com/user-attachments/assets/9f74a157-7750-496a-853f-2bb7fa5e0b73)

**Comment by goutetsuguma** [comment]
@mtdkei 
CC @kurudrive 

ありがとうございます！コアのでできるのですね！良いと思いました！

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
