### ISSUE TITLE
[分割読み込み] x-t9 のとき画像のスタイルが反映されない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2287]
* 分割読み込み/ON
* テーマ/x-t9

のとき画像のスタイルが当たらないようです
下記オプションのきなみ

追記: tt-3、tt-4でも当たらないので、もしかしたらブロックテーマのときかもしれない(?)
確認してる環境は WP 6.6.2

↓↓↓
![image-style](https://github.com/user-attachments/assets/df816b80-9a5a-4115-b5dd-d5eff5416e19)

**Comment by mtdkei** [comment]
Lightningだと
`<link rel='stylesheet' id='vk-blocks/core/image-css' href='http://HOGEHOGE.local/wp-content/plugins/vk-blocks-pro/build/extensions/core/image/style.css?ver=1.89.0.0' type='text/css' media='all' />`
が生成されてますが、X-T9では生成されてないようでした。
コアのテーブルや見出しブロックも画像と同じ状況でした。

**Comment by mtdkei** [comment]
また、トリさんの推察通り、KatawaraやLightning Proでも引き起こされま線でしたのでブロックテーマでの何かが噛み合ってない？のかも知れません。

**Comment by mtdkei** [comment]
調整の方向が見えてきたのでこちらで作業します。

**Comment by goutetsuguma** [comment]
調整ありがとうございました！MergeしましたのでCloseします
