### ISSUE TITLE
[ カバー ]編集画面で装飾なしの見出しを2つ入れてリンクを設定、保存して再び編集画面へ行くとコンテンツ位置が効かなくなる（編集画面のみ）

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2290]
あまりない条件かもしれませんが、念の為issueにします。

再現手順

- カバーブロックを設置してリンクを設定する（コンテンツ位置は何もしないので中央になっている状態）
- 見出しを設置して、スタイルを装飾なしにして、複製して2つにする
- 保存してフロント画面を確認し、再び編集画面に戻るとコンテンツ位置が効かなくなっている（編集画面でのみ）

リンクを解除してももどりませんでした。

![スクリーンショット 2024-11-01 11 46 00](https://github.com/user-attachments/assets/e862fda8-59c0-44c9-ba59-c757e757c499)

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ご意見、ご調整いただきありがとうございました。
