### ISSUE TITLE
分割読み込みがOFFの時、developブランチで、VK Blocks のレスポンシブスペーサーを設置すると、Lサイズなどのサイズでも高さがでない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2296]
設定 > VK Blocks > 分割読み込み設定 の 「分割読み込みを有効にする」 にチェックが入っていない場合に、developブランチで、VK Blocks のレスポンシブスペーサーを設置すると、Lサイズなどのサイズでも高さがでないような気がしましたのでissueにします。私の環境の問題でしたらすみません
確認したところ、分割読み込みがOFFの時の時、編集画面で block-build.css が読み込まれていないのかもしれないです。

![スクリーンショット 2024-11-07 14 42 15](https://github.com/user-attachments/assets/e6b80520-f69e-4968-a1a5-a17fcdf83de4)

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
