### ISSUE TITLE
[ WP 6.7 ] Blog Cardブロックが縦に伸びる

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-blocks-pro#2312]
テンプレートがlightning時、
Blog Cardブロックの大画像&画像下文字で縦長になる。
![screencapture-localhost-8888-2024-11-12-19_44_50](https://github.com/user-attachments/assets/09febf84-cc56-4b07-ad85-3efe3d8a25dc)

**Comment by kurudrive** [comment]
@akito-38 このブランチに切り替えてエラーが出ないようにしても同じ不具合は発生しますか？
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1130

**Comment by akito-38** [comment]
@kurudrive 
こちら、改めて確認したところ問題無さそうでしたので、クローズしておきます。
すみません。
