### ISSUE TITLE
カテゴリーバッジ / タグ ブロックを配置しても表示されない。

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-blocks-pro#2313]
投稿詳細入力画面でカテゴリーバッジ / タグ ブロックを配置しても、実際のページで表示されない。

**Comment by mtdkei** [comment]
ありがとうございます。
Closeしたプルリク#2153 のコードなぜかmasterブランチに入っていたので元に戻して確認してみます。

**Comment by mtdkei** [comment]
> ありがとうございます。
> Closeしたプルリク#2153 のコードなぜかmasterブランチに入っていたので元に戻して確認してみます。

この件は関係なさそうでした。

**Comment by mtdkei** [comment]
https://github.com/vektor-inc/vk-blocks-pro/blob/develop/src/blocks/_pro/post-category-badge/edit.js
にて
```
// post_tagとタグタイプのタクソノミーを除外して返す
				return allTaxonomies
					? allTaxonomies.filter(
							(_taxonomy) =>
								_taxonomy.slug !== 'post_tag' &&
								_taxonomy.hierarchical
						)
					: [];
```
とあるので、カテゴリーバッジ / タグ ブロックが出力されてしまうのが問題な気がしてきました。

**Comment by akito-38** [comment]
@mthaichi 
ありがとうございます。
こちら調べてみます。

**Comment by mtdkei** [comment]
マージされていましたのでCloseします。ありがとうございました。
