### ISSUE TITLE
GithubのActionで必ずPlaywright Testsが引っ掛かってしまう

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2315]
GithubのActionで必ずPlaywright Testsが引っ掛かるようになってしまいました。
以下、GithubのActionのテスト用にreadme.txtだけ変更したプルリクです。
6.7の翻訳の修正ができません。みていただけたらと思います。
https://github.com/vektor-inc/vk-blocks-pro/actions/runs/11808826995/job/32898076687?pr=2314

**Comment by kurudrive** [comment]
どれどれ...

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
