### ISSUE TITLE
タクソノミーブロックの表示を日本語表記にしてほしい etc

### ISSUE THREAD

**Issue by MasayaMORIMOTO** [vektor-inc/vk-blocks-pro#2335]
https://vws.vektor-inc.co.jp/forums/topic/103866

**Comment by MasayaMORIMOTO** [comment]
@kurudrive 
ドロップダウンの右側の矢印が消える件は、デザイン班に対応いただくとのことでしたので、
適切な Assignees の設定をお願いできればと思います。

**Comment by goutetsuguma** [comment]
@kurudrive 
CC @MasayaMORIMOTO 

ドロップダウンの右側の矢印が消える件は、おそらくテーマがLightningだからかなと思いました。
（X-T9とか　TTシリーズのテーマに変えると矢印がでます）
一応テーマ側で`none` が指定されていました。
Lightningテーマ側の修正となるとは思います。
これを select { -webkit-appearance: menulist; appearance: menulist; } とかにする矢印はでますが、
一応今までは none となっていたので、それでも問題なさそうかを確認する必要はありそうかなと思いました

> input:where(:not([type=checkbox],[type=radio])),
> select {
> 	-webkit-appearance: none;
> 	appearance: none;
> }

https://github.com/vektor-inc/lightning/blob/5b66a8879babfd2ec4812d7b93682c4a613bc4b0/_g3/assets/_scss/_common.scss#L151-L155

**Comment by mtdkei** [comment]
ドロップダウンの右側の矢印が消える件は https://github.com/vektor-inc/lightning/issues/1205 にてissueを立てましたので、本件はCloseします。ありがとうございました。
