### ISSUE TITLE
[ 投稿リストスライダー ] 背景指定機能を一旦削除したいです

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2339]
背景色を指定すると以下のようになってしまう

![スクリーンショット 2024-11-25 23 03 39](https://github.com/user-attachments/assets/b95358f0-6b9e-43c3-acd6-46d944113aa7)

スライダー下のナビゲーションにかかったり、上下の余白が違ったりして微妙になってしまうので、背景を指定するのであればナビゲーションのところまで含んでいた方が良いが、そこに色をつけるなら枠線や背景画像が...などになってくるので、そこはカバーやグループに任せれば良いと思われる。

現状のままリリースするととりあえず上記SSのような状態で使用されてしまうので、背景指定機能を一旦削除よろしくお願いいたします。
 (￣人￣)

**Comment by kurudrive** [comment]
@drill-lancer cc: @mtdkei @goutetsuguma 

> 背景色を追加したのは下記を理由とするものです。
背景色機能を無効化したとしてこちらに関する対応はいかが致しましょう？
サイトの背景色が白とは限ららないので何かしらの対応が必要かと思われます。
https://github.com/vektor-inc/vk-blocks-pro/pull/2266#issuecomment-2448907897

現状だと
* 背景に色がついても余白サイズに違和感を感じるのとナビゲーションと被るような形式だとやはりデザイン的に微妙なので実用は厳しい
* 余白のサイズは使用者によても判断がわかれるが、現状では指定できないので、背景色を使う人からはどのみち余白や枠線や背景画像などを指定したいと言われる（それらが実装されるまで背景色指定機能はあっても使われない）可能性が高い
* 背景色に関する各種設定機能はコアの機能で block.json だけでできるなら良いが独自実装するとまたどんどんメンテコストが上がっていく

という理由で

> そこはカバーやグループに任せれば良いと思われる。

という判断です (￣人￣)

**Comment by mtdkei** [comment]
マージされていたようですのでCloseします。ありがとうございました。
