### ISSUE TITLE
[ 固定表示 ] 表示タイプの「表示及び非表示までの時間を指定」に指定して、時間指定して戻すと壊れるっぽい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2340]
このブロックでエラーが発生したためプレビューできません。が発生してしまう。

何度かやると再現すると思うけどどうでしょう？

https://github.com/user-attachments/assets/1633301f-fd07-4e60-a865-0d9339b0ab62

**Comment by mtdkei** [comment]
こちら確認します！

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
