### ISSUE TITLE
[ 投稿リスト] TT4やTT5 テーマで見出しの上に余白が開く（投稿リストスライダーも同様）

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2344]
投稿リストスライダーを確認してて気づいたのですが、TT4やTT5 テーマで表示タイプが「テキスト1カラム」以外のタイプですと、見出しの上に余白が空くようでしたのでissueにします
X-T9 と Lightningでは問題ありません。

![スクリーンショット 2024-11-26 14 29 29](https://github.com/user-attachments/assets/87e31c85-052c-41d4-b30b-303a0ae135bd)

**Comment by mtdkei** [comment]
マージされておりましたのでCloseします。ありがとうございました。
