### ISSUE TITLE
[ 投稿リストスライダー ] 編集画面で Read more のボタンの文字が黒なので白にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#2353]
![スクリーンショット 2024-11-28 1 16 08](https://github.com/user-attachments/assets/5420fe19-c5d1-4db0-8301-ffb591e59e3a)

**Comment by mtdkei** [comment]
マージされていたようなのでCloseします。ありがとうございました。
