### ISSUE TITLE
プラグイン「Search Exclude」使用時、投稿リストブロックの分類絞り込み条件をORで「該当の投稿はありません。」となる

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2364]
https://vws.vektor-inc.co.jp/forums/topic/%E3%80%8Csearch-exclude%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%80%8D%E4%BD%BF%E7%94%A8%E6%99%82%E3%80%81%E6%8A%95%E7%A8%BF%E3%83%AA%E3%82%B9%E3%83%88%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF

**Comment by mtdkei** [comment]
調べてみたところ、プラグイン「Exclude from Search Results」を入れていると、絞り込みでORにしててもANDが効いてしまうようでした。

投稿一覧のカテゴリー設定。
![image](https://github.com/user-attachments/assets/da8556b5-0abb-4851-9961-3b837cde0883)

投稿リストの編集画面。分類絞り込み条件のカテゴリーが複数でOR。
![image](https://github.com/user-attachments/assets/db9bf9c7-c59f-4d25-9ac7-fa81bf665396)

プラグイン「Search Exclude」がONの時に投稿リストのフロントエンド。
![スクリーンショット 2024-12-10 10 44 59](https://github.com/user-attachments/assets/67c91414-c4cd-4387-88b3-cf72f7173cbe)

プラグイン「Search Exclude」がOFFの時に投稿リストのフロントエンド。
![スクリーンショット 2024-12-10 10 44 48](https://github.com/user-attachments/assets/8856b469-d189-4d23-8321-d19bbe372b06)

**Comment by kurudrive** [comment]
これ VK Blocks Pro で指定て投げたクエリを このプラグインが pre_get_posts で上書きしてくるので無理ですね（＝ｗ＝
