### ISSUE TITLE
[投稿リストブロック・投稿リストスライダー] 条件に「先頭固定表示の投稿」があってもよいかもしれない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2366]
コアのクエリーループブロックでは、「先頭固定表示の投稿」を [含める / 除外 / 限定] が選べるので、VK の投稿リストブロック、投稿リストスライダーにもあってよいかもしれないと思いました
が、「先頭固定表示の投稿」あまり使わないかもですので、優先度低めで

**Comment by goutetsuguma** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/2288
ありがとうございます！こちらのissueと同じかもしれませんので貼っておきます

**Comment by sysbird** [comment]
あらやーね、
こちら閉じますーー
