### ISSUE TITLE
[ 吹き出し / 枠線ボックス ] リストやアラートのカラーが意図通りでない不具合がある

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-blocks-pro#2378]
https://vws.vektor-inc.co.jp/forums/topic/%e5%90%b9%e3%81%8d%e5%87%ba%e3%81%97%ef%bc%9e%e3%83%aa%e3%82%b9%e3%83%88%e3%81%ae%e3%83%86%e3%82%ad%e3%82%b9%e3%83%88%e8%89%b2%e3%80%81%e6%9e%a0%e7%b7%9a%e3%83%9c%e3%83%83%e3%82%af%e3%82%b9%ef%bc%9e

以下でもご確認いただけます。(ログインしてください。)
https://demo.dev3.biz/lightning-g3-pro/page-6095/

**Comment by kurudrive** [comment]
close as completed
