### ISSUE TITLE
[Outer] アクセシビリティ対応テキストがある場合は、aria-label 属性はいらないかもしれない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-blocks-pro#2380]
本日12/19 のお知らせにあった、リンクツールバーにaタグのアクセシビリティやSEOに対応できるよう設定追加(ここではOuterのみ) #2362 について、リンクツールバーに a タグのアクセシビリティや SEO に対応できるよう設定追加 (グリッドカラム) #2367 を確認中に絡んで確認しました

* Accesibility link description がある場合は、aria-label 属性はいらないのでは?
* `target="" ` 空の場合は出力しないほうがいいかもしれない
* `rel="" ` 空の場合は出力しないほうがいいかもしれない

**Comment by mtdkei** [comment]
@sysbird 
ありがとうございます！

今の所、他のブロックが aria-label に依存している現状のため、Outer においても暫定的に aria-label を残している状態でした。ただおっしゃる通りOuterブロックではいらないので削除の方向で考えてみます。

また、target=""  と rel=""  においてはおっしゃる通りです。こちらはリンクコンポーネントの件のため、上記とは別方向で処理を進めていくことになるかと思います。

上記2点をもしやってくださる方がいればお願いしたいですが、急ぎであれば対応します。

**Comment by sysbird** [comment]
@mtdkei 
ありがとうございます！
ぜんぜん急ぎじゃないですーー

**Comment by sysbird** [comment]
@mtdkei 
aria-label、target=""、rel=""  はリンクコンポーネントでの対応になりますか？
そうしますと、各ブロックでアクセシビリティ対応テキストを対応している途中ですので、それが済んでからのほうがよいでしょうかね

**Comment by mtdkei** [comment]
@sysbird 
ありがとうございます。今確認している感じだと各ブロック対応の内容だったのでOuter側で対応してみてます！

**Comment by sysbird** [comment]
対応ありがとうございました
マージされたので閉じます
