### ISSUE TITLE
[ 投稿リストスライダー ]複数設置した時、片方のページネーションの種類や複数表示設定を変えると、全部が連動して変わってしまうかもしれない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2385]
投稿リストスライダー を複数設置した時、片方のページネーションの種類を変えると、全部が連動して変わってしまうかもしれないです。

【追記】ページネーションの種類だけでなく、複数表示設定も連動して変わってしまうようでした。

こちらのページでも確認できます。
https://demo.dev3.biz/lightning-g3-pro/6136-2/

**Comment by mtdkei** [comment]
マージされているようでしたのでCloseします。ありがとうございました。
