### ISSUE TITLE
[ 投稿リストスライダー ] 表示タイプをメディア にして、ページネーションの種類をスライドの枚数 で、ページネーション部分が少し上の線とかぶってしまう

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#2386]
表示タイプをメディア にして、ページネーションの種類をスライドの枚数 にすると、ページネーション部分が少し上の線とかぶってしまうようでした

（ブロックの余白で下にSサイズとかつければ良いのだけど、最初から余白がある方が親切かなと思ったのでメモ）

![スクリーンショット 2024-12-24 17 07 15](https://github.com/user-attachments/assets/745f92c1-56f9-4648-a376-7aafcbb72abf)

**Comment by mtdkei** [comment]
マージされているようでしたのでCloseします。ありがとうございました。
