### ISSUE TITLE
【確認待ち】VK Block Pro のカルーセルのレスポンシブ強化

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-blocks-pro#469]
https://vws.vektor-inc.co.jp/forums/topic/vk-block-pro-のカルーセルのレスポンシブ強化

■ 利用プラグインとバージョン
VK Block Pro 1.1.0

■ 機能追加要望

VK Block Pro 1.1.0 で追加されたカルーセルを試してみました。

試したものを該当URLに貼りましたので、ご参照ください。

カルーセルのアイテムをブロックエディターで差し替えできるようになって、更新作業がしやすくなります。

ありがとうございます。パソコン画面で見ていれば、もう大・大・大満足です!!

早速ですが、このカルーセルを多くの場面で使ってもらえるように、機能強化を提案させてください。

<strong>画面幅ごとに画像の枚数を指定できるようになるとすごくうれしいです。</strong>

パソコンの画面幅だと5枚くらい並べたくなりますが、スマホ画面に5枚は多すぎます。

スライダーアイテムエリア内の余白をなくしてみましたが、3枚 が上限と感じます。

文字入れしたバナーにも使いたいと思うのですが、可読性を考えると画像の枚数を1枚にしたいです。

ご検討の程よろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer @shimotmk @goutetsuguma 

そうですね、ブレイクポイントは redme.md に書いてあるとおり

スマホ
`@media (max-width: 575.98px)`

タブレット
`@media (min-width: 576px) and (max-width: 991.98px)`

PC
`@media (min-width: 992px)`

で良いと思います。

**Comment by kurudrive** [comment]
定期的に必要な要望が出てくるので優先度を中に上げました。

**Comment by drill-lancer** [comment]
リリースされたので Close
