### ISSUE TITLE
グループブロックのスタイル「スティッチ」で .wp-block-group__inner-container を使わないスタイリングをする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#606]
テーマ内に theme.json を置くと、グループブロックの中に自動生成される `<div class=".wp-block-group__inner-container"></div>` が出力されないようになるため、ここのスタイルアテると効かなくなる。

■ 対象ファイル
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/utils/common.scss

なので、ナシでもいけるように before after 使うなど代用検討

テーマファイル内に theme.json を置いた時と置かない時で確認しつつテスト・検討

```適当な theme.json の例
{
    "version": 1,
    "settings": {
    }
}
```

**Comment by kurudrive** [comment]
@shimotmk ありがとうござます！

**Comment by mtdkei** [comment]
グループブロックのスタイル「スティッチ」で .wp-block-group__inner-container を使わないスタイリングに対応したのでClose
