### ISSUE TITLE
［相談］【Outer】カバー 固定（iPhoneでは固定されません）でiPhoneで背景画像が拡大する問題

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-blocks-pro#607]
```
background-attachment: fixed;
background-size: cover;
```
の同時指定はiOSで不具合が起こるので、注意書きで（iPhoneでは固定されません）としていますが、iPhoneでみると背景画像が拡大されてしまうので、もういっそのことタブレット以下(max-width: 991.98px)のサイズでは固定されない仕様としたほうがいいのかな？とも思いました。（iPhoneじゃない人からは何か言われるかな、、、？どうかな、、、）

案としては
カバー 固定（iPhoneでは固定されません）の表記を
カバー 固定（タブレットサイズ以下では固定されません）

みたいにして、

@media (max-width: 991.98px){
.vk_outer-bgPosition-fixed {
background-attachment: unset;
}
}

**Comment by kurudrive** [comment]
無理 close
