### ISSUE TITLE
【リリース・お知らせ待ち】ブログカードブロックが必要かも

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#749]
ベクトレでベクトレ内のURLを貼ると、iframe？で読み込んでしまって微妙になる。

普通ブログカードに変換されるはずだけどこの違いはなんだろう？

安定表示させるにはブログカード専用のブロックがあった方が良いかも。

![Edit-レッスン-‹-ベクトレ-—-WordPress (1)](https://user-images.githubusercontent.com/3272660/132932242-44d2d67e-dfa2-40b1-88d3-7c329b4f8f05.png)

**Comment by shimotmk** [comment]
@vektor-inc/vektor-inc
Blog Cardブロックの試作品を作ってみました！
ブランチ #1778
zip [vk-blocks-pro.zip](https://github.com/vektor-inc/vk-blocks-pro/files/12224890/vk-blocks-pro.zip)

インナーブロックとしてカスタマイズできるBlog Card 1と完全固定のBlog Card 2があります
個人的にはBlog Card 1でもそこまでカスタマイズが難しくないかと思っているので完全固定のBlog Card 2は要らないと思うのですが、どうでしょうか？

お時間ある時に使い心地などご意見ある方いただきたいです。

**Comment by kaorock72** [comment]
ありがとうございます！
Blog Card 1を触ってみたところ、たしかにカスタマイズが簡単でした。自分好みのブログカードをノーコードで実現できるのがとてもいいです〜！個人的にも早く使いたいな〜って思いました。

あと、6.3 RC2の環境だと、画像のアスペクト比を簡単に変更できちゃうのも嬉しいです。好みに調整したブログカードを非同期パターンとして登録すれば、使い回しできてよさそうです。

Blog Card 2も触ってみました。わたしも完全固定のBlog Card 2はとくに要らないかなぁと感じました。

ほか、触りながらふと思ったことは以下2点です。
ほかの方のご意見もでてきた時に、あわせて参考にしていただけたらと思います。

- Blog Card 2は、3つのパターンから選んだあと、右の設定サイドバーで後からパターンを選び直せるようです。Blog Card 1も同じようにする予定でしょうか。（やっぱり「大画像 & 画像下文字」のパターンにしたいときなどに便利かもと思ったので。）
でも、コアのカラムブロックでは、あとからパターンを選び直すことはできなかったかと思うので、その動きと合わせるなら、Blog Card 2は今のままでよいかも？とも思いました。
<img width="1323" alt="スクリーンショット 2023-08-02 17 14 59" src="https://github.com/vektor-inc/vk-blocks-pro/assets/59037734/df0cd55a-8912-4ba0-b930-98ee0075adbe">

- 最大文字数を減らしたあとで元に戻したいときは、最大文字数のスライダーをmaxにすればOKという認識でよいでしょうか。（文字数を元に戻したいときは「リセット」などがあると分かりやすそう？）

それでは、引き続きよろしくお願いいたします！

**Comment by mthaichi** [comment]
@shimotmk 試してみました。私は 1 がいいかなあと。

1 のレイアウトの自由度の高さは良いですね。CSSを使わずにある程度のことができるのが良いと思います。自分好みのデザインを作ってパターンに登録とかもできますよね。「画像は不要」という人にも対応可能かと。

初心者の方：URLとプリセットのレイアウトを選んで終わり。
中級者の方：自分好みにレイアウトを変えて、パターン登録して使い回す。
上級者並びに業者の方：カスタムCSSやカスタムブロックスタイルも使ってあれこれできる。

こういう棲み分けができるのかなーと。

埋め込みのスタイルをチューニングしたいニーズは高いと思います。標準の埋め込みってちょっと尺取りすぎな気がしまして。そういう人も1であれば手軽に対応できるのではないでしょうか。

あと細かいところですが
- 初心者向けに4つ目のパターン画像無しレイアウトがあってもいいのかなと。
- 見出しブロック同様にタイトル部分のスタイルを選べると最高です。

**Comment by shimotmk** [comment]
ありがとうございます！

> Blog Card 2は、3つのパターンから選んだあと、右の設定サイドバーで後からパターンを選び直せるようです。Blog Card 1も同じようにする予定でしょうか。

ツールバーの置換ボタンを押して開始パターンを選び直すことができます！
![replace](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/69c34106-63aa-40d2-91f3-9d5e00cbeff2)

いきなり変えてしまうとインナーブロックのカスタマイズがなくなるので現時点では置換ボタンを押す形にしています。

>  最大文字数を減らしたあとで元に戻したいときは、最大文字数のスライダーをmaxにすればOKという認識でよいでしょうか。（文字数を元に戻したいときは「リセット」などがあると分かりやすそう？）

抜粋ブロックと同じようにしたのですが、確かに最大文字数は変わるのでリセットつけました！

**Comment by shimotmk** [comment]
ありがとうございます！

> * 初心者向けに4つ目のパターンとして画像無しレイアウトがあってもいいのかなと。

画像なしのレイアウトどんな感じのパターンですかね。大画像 & 画像下文字から画像抜くだけですかね？
HTML貼っていただけたら。。

> * 見出しブロック同様にタイトル部分のスタイルを選べると最高です。

コアの見出しブロックは文章の中の見出しでこのブロックのタイトルはURLに対するタイトルで少し意味が違うので同じスタイルにするケースは少ないかなと思いました。もしスタイルを付けたいならユーザーさんに任せれば良いかなと思いました！

**Comment by kaorock72** [comment]
> ツールバーの置換ボタンを押して開始パターンを選び直すことができます！

わ、ここにありましたか！選び直せました。画像付きで説明ありがとうございます〜！

> いきなり変えてしまうとインナーブロックのカスタマイズがなくなるので現時点では置換ボタンを押す形にしています。

了解です！

> 抜粋ブロックと同じようにしたのですが、確かに最大文字数は変わるのでリセットつけました！

さっそくリセットつけてくださりありがとうございます！なるほど、抜粋ブロックと同じにされていたのですね

**Comment by mthaichi** [comment]
@shimotmk

> 画像なしのレイアウトどんな感じのパターンですかね。大画像 & 画像下文字から画像抜くだけですかね？ HTML貼っていただけたら。。

はい、抜くだけでもいいです。
画像抜くには、カラム解除しないといけないじゃないですか。それは初心者の方は大変そうなのでプリセットであると嬉しい！と思いました。

自分的には以下のようなイメージです。（デザインはこの通りじゃなくてもいいです。私はセンス無いので・・・。）

![image](https://github.com/vektor-inc/vk-blocks-pro/assets/1535140/2a05d44b-3e77-44e9-8fe9-e2f805bfef1e)


```
<!-- wp:vk-blocks/blog-card {"url":"https://www.vektor-inc.co.jp/post/wordpress-6-3-dev-note-note/"} -->
<div class="wp-block-vk-blocks-blog-card"><!-- wp:group {"style":{"spacing":{"padding":{"top":"18px","bottom":"18px","left":"12px","right":"12px"}},"border":{"radius":"5px","color":"#e0e0e0","width":"1px"}},"backgroundColor":"white","className":"is-style-vk-group-solid vk_block-margin-sm\u002d\u002dmargin-bottom","layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-vk-group-solid vk_block-margin-sm--margin-bottom has-border-color has-white-background-color has-background" style="border-color:#e0e0e0;border-width:1px;border-radius:5px;padding-top:18px;padding-right:12px;padding-bottom:18px;padding-left:12px"><!-- wp:vk-blocks/blog-card-title {"level":4,"className":"vk_block-margin-0\u002d\u002dmargin-top vk_block-margin-0\u002d\u002dmargin-bottom","style":{"typography":{"fontSize":"17px"}}} /-->

<!-- wp:vk-blocks/blog-card-excerpt {"excerptLength":44,"className":"vk_block-margin-xs\u002d\u002dmargin-bottom vk_block-margin-xs\u002d\u002dmargin-top"} /-->

<!-- wp:group {"style":{"spacing":{"blockGap":"6px"}},"className":"vk_block-margin-0\u002d\u002dmargin-top","layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center","justifyContent":"left"},"fontSize":"small"} -->
<div class="wp-block-group vk_block-margin-0--margin-top has-small-font-size"><!-- wp:vk-blocks/blog-card-site-logo {"style":{"layout":{"selfStretch":"fixed","flexSize":"15px"}}} /-->

<!-- wp:vk-blocks/blog-card-site-title /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:vk-blocks/blog-card -->

```
 
> > * 見出しブロック同様にタイトル部分のスタイルを選べると最高です。
> 
> コアの見出しブロックは文章の中の見出しでこのブロックのタイトルはURLに対するタイトルで少し意味が違うので同じスタイルにするケースは少ないかなと思いました。もしスタイルを付けたいならユーザーさんに任せれば良いかなと思いました！

Blog Card Title ブロックは見出しレベルが選べるじゃないですか。
単純にそれが選べるならスタイルもと思った次第です。
見出しレベルをH3に設定すると余計な装飾がつくので、装飾無しにしたいなーという感じです。
まー、H4のままで、フォントサイズ変えれば、見た目的には合わせられるので、絶対欲しいって感じでもないですね。

**Comment by mthaichi** [comment]
> はい、抜くだけでもいいです。 画像抜くには、カラム解除しないといけないじゃないですか。それは初心者の方は大変そうなのでプリセットであると嬉しい！と思いました。

「大画像」を選んで、画像を削除すれば、結構理想に近い感じでした。
初心者の方々が、そこに気がつけるかなってとこですね。

**Comment by shimotmk** [comment]
@mthaichi 
ありがとうございます！

> 「大画像＆画像下文字」を選んで、画像を削除すれば、結構理想に近い感じでした。
初心者の方々が、そこに気がつけるかなってとこですね。

流石にブロックを削除することは誰でもできると思っています。画像を抜くだけであればそのバリエーションは要らないかなと

https://github.com/vektor-inc/vk-blocks-pro/issues/749#issuecomment-1665046364
なるほど、書いてもらったHTMLを見て思ったのはやはりバリエーションを追加したいニーズがあると思ったのでカスタムバリエーション機能があったら良いと思いました。

とはいえ少し時間がかかりそうなので後からにしたいです

**Comment by mthaichi** [comment]
@shimotmk 
> 流石にブロックを削除することは誰でもできると思っています。画像を抜くだけであればそのバリエーションは要らないかなと

私の頭なので参考にならないかもですが、「大画像＆画像下文字を選んでから」画像を抜くというのは、ぱっとは思いつきませんでした。

ブロックを挿入したときに、レイアウトをマニュアルで変えられることに気が付けない人も多いのではないかと思います。たとえば、レイアウトの説明文に「レイアウトが自由に変えられるブログカードブロック」とあれば、埋め込んだあとに編集できるんだと気がつけるとおもいます。

簡単に作れるとはいっても、最初に選べるレイアウトが一つ増えれば、それはそれで製品のバリューになるのではないかと私は思いますので、画像なしも選べるようにしてほしいなーというのが私の思いです。が、本当に「画像なし」にそれほどのニーズがあるのかと言われると、リサーチしたわけでもなく、絶対あるとは言えず、僕の思いにしか過ぎないので、他の方のご意見もお聞きしたい感じですね。
 
> [#749 (comment)](https://github.com/vektor-inc/vk-blocks-pro/issues/749#issuecomment-1665046364) なるほど、書いてもらったHTMLを見て思ったのはやはりバリエーションを追加したいニーズがあると思ったのでカスタムバリエーション機能があったら良いと思いました。

カスタムバリエーション機能あると便利ですね。
最初にエディットしたレイアウトを使いまわしたいというニーズはあるのではないかと思います。
まずは @kurudrive さんの示した仕様を満たしていれば、いったんリリースして後付けでもよいのでないでしょうか。

**Comment by kurudrive** [comment]
@shimotmk 確認しました。ありがとうございます。すばらしいです。さすがです。

Blog Card 2 は僕の環境ではスタイルがうまくあたらなかったのですが、1 でレイアウトの選択・切り替えについて、僕の想定していたよりもずっと使いやすかったので 1 で良いと思います。

> 流石にブロックを削除することは誰でもできると思っています。画像を抜くだけであればそのバリエーションは要らないかなと

抜くだけなら良いのですが、やはり
画像の左右のレイアウトからスタートして画像を抜く人が想定されて、空のカラムが存在するのでGapも発生してしまう
という事態は想定されるので、最初の選択肢の中に画像なしバージョンはあった方が良いように思います。

フォーラムとか見てるとほんとにブロックエディタの使い方わかってない人が多いので...。

とは言え画像なしレイアウトは後付けでも良いです。

そして見出しのスタイル機能は...デザインを指定するという意味では不要だと思いますが、
確かにテーマ側のスタイルの影響を受けてしまうからリセットするという意味ではあった方が良いですが...こちらも必須ではないかな...

僕としては機能面は今の状態でリリースでも良いと思いました。

@goutetsuguma さんなどに必要なアイコンなど順次依頼して進めていただければ！

**Comment by shimotmk** [comment]
@goutetsuguma 
すみません。
お手隙の際で良いので以下のアイコン作成お願いしても良いですか？

ブロック
・Blog Card
・Blog Card Excerpt
・Blog Card Featured Image
・Blog Card Site Logo
・Blog Card Site Title
・Blog Card Title

バリデーションアイコン
・leftImageRightText
・leftTextRightImage
・largeImageAndImageLowerCharacter

ここの部分です
![icon](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/0a620131-ac81-4254-a61d-b348ae3d080a)

あと初期に配置されるバリデーションテンプレートの調整があればしていただきたいです。
一応参考にしたのはLightningのブログカードです
https://lightning.vektor-inc.co.jp/setting/seo/

**Comment by goutetsuguma** [comment]
@shimotmk  

デザインも自由に変えれて新しいタブでも開けるしすごく使いやすいです！

> 確かにテーマ側のスタイルの影響を受けてしまうからリセットするという意味ではあった方が良いですが...こちらも必須で はないかな...

→ わたしも石川さんと同じで、リセット機能があったら良いなと思いました。でも初めは h5 で配置されるので、h5のの見出しに装飾をがっつり付けている方はあまりいないかな？とも思うので、のちのちあると良いなと思うくらいです！

【ふと思ったところ】

- 配置を置き換えるとBlog Card(外の枠)のスタイルは変わらないのですが、見出しとか抜粋の文字数は最初の数値にもどるようでした。あまり後から配置をなん度も変える方はいらっしゃらないと思うのですが、もしかするとスタイルが維持できると良いのかも？と思いましたが、他の方のご意見を聞いたり、実装が難しい場合もあると思いますので、もし実装するとしても後々で良いと思います！

- おそらくテーマ側のことだと思うのですが、X-T9テーマで見ると「Blog Card Title」の「スタイル設定」の「色」には「テキスト」と「背景」が表示されるのですが、Lightningテーマにすると「テキスト」と「背景」と「リンク」が表示されました。
X-T9では「リンク」が表示されなかったのですがたぶんテーマ側に関係あることですかね、、？
（テーマによってはaタグに色が付いてしまうこともあると思うので、リンクの色が変えれるのは良いなと思い、きいてみました）

**Comment by goutetsuguma** [comment]
@kurudrive 
石川さんへ、svgアイコンを変更していますので、よければご確認お願いいたします🙇‍♂️
https://github.com/vektor-inc/vk-blocks-pro/pull/1778　にアイコンはコミットしてあります。

**Comment by shimotmk** [comment]
@goutetsuguma 
ありがとうございます！

> 配置を置き換えるとBlog Card(外の枠)のスタイルは変わらないのですが、見出しとか抜粋の文字数は最初の数値にもどるようでした。あまり後から配置をなん度も変える方はいらっしゃらないと思うのですが、もしかするとスタイルが維持できると良いのかも？と思いましたが、他の方のご意見を聞いたり、実装が難しい場合もあると思いますので、もし実装するとしても後々で良いと思います！

これは現時点ではコアの仕様上無理です。
とはいえ、ユーザーも困る可能性もあるのでメッセージを調整しておこうと思います

![variation](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/1e4056de-444e-4a9a-a85b-c553b61c9294)

---

>  おそらくテーマ側のことだと思うのですが、X-T9テーマで見ると「Blog Card Title」の「スタイル設定」の「色」には「テキスト」と「背景」が表示されるのですが、Lightningテーマにすると「テキスト」と「背景」と「リンク」が表示されました。
X-T9では「リンク」が表示されなかったのですがたぶんテーマ側に関係あることですかね、、？
（テーマによってはaタグに色が付いてしまうこともあると思うので、リンクの色が変えれるのは良いなと思い、きいてみました）

そうですね。X-T9側の設定なのでブロック側からは操作できないです。

---

バリエーションのアイコンはVKのマークは付けないほうが良いですかね？
一応今後バリエーションをユーザーが追加できるようにしようとしているのですが、プラグインが追加したバリエーションなのかユーザーがカスタマイズしたものかわかる様にしたいなと思いまして。

![variation](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/1e4056de-444e-4a9a-a85b-c553b61c9294)

---

以下の調整は必要でしょうか？
微調整 段落と同じスタイルになるように詳細度を落とす
https://github.com/vektor-inc/vk-blocks-pro/pull/1778/commits/9c10bb24b3f54030068d0bb3f23abf9728af3979

blog-card-excerptブロックはコアのexcerptブロックを参考にしています。
https://github.com/WordPress/gutenberg/blob/9c5ce7eb6f5c76064209f741951917532cdd781d/packages/block-library/src/post-excerpt/style.scss#L8-L11

**Comment by kurudrive** [comment]
@goutetsuguma アイコン確認しました。良いと思いますー！ありがとうございます！

**Comment by goutetsuguma** [comment]
@shimotmk 

返信ありがとうございます！

> これは現時点ではコアの仕様上無理です。
> とはいえ、ユーザーも困る可能性もあるのでメッセージを調整しておこうと思います

→承知しました、ありがとうございます！

> そうですね。X-T9側の設定なのでブロック側からは操作できないです。

→ こちらも承知しました、ありがとうございます！

-----

> バリエーションのアイコンはVKのマークは付けないほうが良いですかね？
> 一応今後バリエーションをユーザーが追加できるようにしようとしているのですが、プラグインが追加したバリエーションなのかユーザーがカスタマイズしたものかわかる様にしたいなと思いまして。

→なるほど、ユーザーが追加できるのすごい便利ですね🤩VKマークつけたいと思います、調整しましたらお知らせしますね🙇‍♂️

> 以下の調整は必要でしょうか？
> 微調整 段落と同じスタイルになるように詳細度を落とす

→Lightningでみた時に、Lightningテーマ側の段落の下の余白が打ち消されてしまっているようでしたので調整しましたが、不要に思いました（余白はテーマで変わるので0で良いですね）コア側と同じにした方が良いと思いましたので、こちらもあとで直します。（自分で余白をつけたい場合はつけてバリエーション追加したら良いですね）

**Comment by goutetsuguma** [comment]
@shimotmk 

バリエーションのアイコンにVKマークつけましたのでご確認お願いいたします！

あ、あと今気づいたのですが、以下の行の`leftImageRightText`　と　`leftTextRightImage`がありますが、
`leftImageRightText`の方が「右 画像」になって、leftTextRightImage`の方が「左 画像」になるのですが、この関数名（であってますかね？）は逆なのかなと思いましたがどうなのでしょうか、、？わたしの思い違いでしたらすみません🙏
（とくに動作的には問題ありませんが、少し気になりましたのでおききしました。）

https://github.com/vektor-inc/vk-blocks-pro/blob/9549279e64ad8d694bc9ea2a176c0d318de8837c/src/blocks/_pro/blog-card/icons.js#L5


https://github.com/vektor-inc/vk-blocks-pro/blob/9549279e64ad8d694bc9ea2a176c0d318de8837c/src/blocks/_pro/blog-card/icons.js#L20

**Comment by shimotmk** [comment]
@goutetsuguma 
アイコンありがとうございます！

leftとRightを間違えていますね、、
なおしておきます🙈

**Comment by shimotmk** [comment]
@goutetsuguma 
お手隙の際で良いので以下のアイコン作成お願いしても良いですか？

カスタムバリエーション機能のアイコンを設定しなかった時のデフォルトのアイコンを作っていただきたいです。
ブランチ #1815

アイコンの設定箇所は
`src/extensions/common/custom-block-variation/icons.js`
の`export const VariationIcon = 'embed-generic';`の箇所を
https://github.com/vektor-inc/vk-blocks-pro/blob/master/src/blocks/_pro/blog-card/icons.js#L5-L18
のようにすれば変わると思います

わからなければ言っていただければと思います。
他何かユーザー目線でわからないことなどあったら言ってください
よろしくお願いします🙇‍♂️

**Comment by goutetsuguma** [comment]
@shimotmk 
CC @kurudrive 

おつかれさまです！確認しました！めちゃくちゃすごい機能ですね！細かいデザインしたい方にはありがたい機能です！

あと、ユーザー目線で、Figmaに改善案をだしてみました。主に初心者向けに説明文章など追記したような案になります🙇‍♀️
間違っている点もあると思いますので、ご指摘いただけますと嬉しいです。

https://www.figma.com/file/4bdwFjwkn6vOphzECs2X2P/%E3%83%90%E3%83%AA%E3%82%A8%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E8%A8%AD%E5%AE%9A%E7%94%BB%E9%9D%A2%E3%81%AE%E6%94%B9%E5%96%84%E6%A1%88?type=design&node-id=402%3A225&mode=design&t=YyLaU6MQ70GtlzMU-1

-----

【アイコンについて相談です、、】
アイコンについて、、苦戦しておりましす、、、涙

「インサーター」に表示されるアイコン(48×48)と、ブロックのバリエーションピッカーに表示されるアイコン(24×24)がありますよね。
現在、ブログカードのインサーターに表示されるアイコンとブロックのバリエーションピッカーに表示されるアイコンは、別で作成していました。

↓ブロックのバリエーションピッカーに表示されるアイコン
![スクリーンショット 2023-09-28 12 00 33](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/7b8781c5-7e9a-4570-9d30-bbcac1320dd4)
↓「インサーター」に表示されるアイコン(48×48)
![スクリーンショット 2023-09-28 12 00 45](https://github.com/vektor-inc/vk-blocks-pro/assets/5525368/039c740a-5b7b-43a5-94cc-f4d573a96bda)


質問なのですが、「インサーター」に表示されるアイコン(48×48)と、ブロックのバリエーションピッカーに表示されるアイコン(24×24)は、別々にSVGアイコンを作成して、それぞれ表示させることはできるのでしょうか、、？

変なこと聞いていたらすみません、、、🙇‍♀️

[Figma　VK Blocks Iconデータ
](https://www.figma.com/file/Y5AqJ0EmIbxbVJo8JMC0Kg/VK-Blocks-Icons?type=design&node-id=1%3A281&mode=design&t=t7sky9AJeuDZs6mn-1)

**Comment by shimotmk** [comment]
@goutetsuguma
確認ありがとうございます！
figmaを参考にある程度調整しました。
細かなCSSなどの調整があれば要素が固まってから @goutetsuguma さんにお願いしたいです。

キーワードの箇所に関しては設定方法が間違っていたので改修しました。ありがとうございます！以前のオプション値が残っていたら削除しないとエラーになると思うの削除してください

vk-blocks.phpに以下のコードを書いてプラグインを一度無効化すると設定が削除されます
```PHP
register_deactivation_hook( __FILE__, 'vk_blocks_uninstall_function' );
function vk_blocks_uninstall_function() {
	delete_option( 'vk_blocks_options' );
}
```

キーワードはインサーターやスラッシュコマンドで使えます
説明部分はarial-label以外にもインサーターの説明部分で表示されます

![variation1](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/a4485fbc-100b-46b6-a89b-4a9d1fe4bf9f)
![variation2](https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/525d1202-5b23-40c6-8096-55a6ae379b82)

インサーターを選んだ時のカテゴリー選択ですが、カテゴリーを選択しなかった場合作ろうとしているバリエーションのブロックのカテゴリーになるので必須ではないです。
例えばブログカードバリエーションの場合VK Blocksになるはずです。

アイコンについてはもしかするとコアのバグかもしれません。なので現時点では以下のどちらかの方法かなと
1.今の状態でコアのdashiconsを利用する
https://developer.wordpress.org/resource/dashicons/#embed-generic
2.インサーターかバリエーションピッカーで表示されるアイコンのどちらかにサイズを合わせて片方をCSSなどで調整する
のどちらかになるかなと思いました。

私はどちらでも良いのですが、2の方法で探っていただくことは可能ですか？もし @goutetsuguma さんの方で今のままでも問題なさそうであれば1の方法でも良いかと思っています。

**Comment by goutetsuguma** [comment]
> 細かなCSSなどの調整があれば要素が固まってから @goutetsuguma さんにお願いしたいです。

→承知しました！

> キーワードはインサーターやスラッシュコマンドで使えます

→なるほど、承知しました！
私の環境だけかもしれないのですが、登録済みのバリエーションを「編集」をクリックして、「キーワード」に文字を入れた時だけ、「変更を保存」のボタンが押せない状態になりました。他の場所は修正すると問題なく保存ボタンが押せました。

> 例えばブログカードバリエーションの場合VK Blocksになるはずです。

→VK Blocksになっていることを確認しました！

----

アイコンの件ですが、svgにwidthとheightが自動ではいるのでsvgを調整する必要がありそうでした。viewBox属性 でXとY軸、幅と高さを調整できそうかなと思い、やってみたのですが、ちょっと難しそうでした、、。🙇‍♀️

すみませんが、1の現状のコアのdashiconsを利用する方法で調整できますでしょうか？

**Comment by shimotmk** [comment]
@goutetsuguma 
> 私の環境だけかもしれないのですが、登録済みのバリエーションを「編集」をクリックして、「キーワード」に文字を入れた時だけ、「変更を保存」のボタンが押せない状態になりました。他の場所は修正すると問題なく保存ボタンが押せました。

キーワードの入力欄は、半角コンマまたはエンターキーで区切ると変更を保存することができます
タグと同じコンポーネントを利用しています

https://github.com/vektor-inc/vk-blocks-pro/assets/42362903/ba7ac413-dc25-4065-b960-0abdc468b623

> すみませんが、1の現状のコアのdashiconsを利用する方法で調整できますでしょうか？
アイコンの場所に embed-generic がすでに入っているイメージですかね？

そうです！現状の状態のことを言っています

モーダル内のフォームなどでCSSなどの調整があればお手隙の際にお願いしたいです

**Comment by goutetsuguma** [comment]
@shimotmk 
CC @kurudrive 

> キーワードの入力欄は、半角コンマまたはエンターキーで区切ると変更を保存することができます
> タグと同じコンポーネントを利用しています

なるほど！理解できました🙇‍♀️

アイコンについてもembed-genericのアイコンが入ることが確認できました！

たまに「バリエーション設定」の登録済みに、登録したバリエーションが表示されないことがありましたが、「キャッシュをクリア」ボタンを押すと解決できました！

ブロックのバリエーションからもインサーターからも呼び出せるので、すごく便利ですね！

cssも微調整いたしました。

**Comment by shimotmk** [comment]
#1778
