### ISSUE TITLE
[ 吹き出しブロック ] 初期状態の画像設定

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#838]
ミステリーマン（WordPressのユーザー初期画像）で良いので設定しておく

↓こういうの

![blank-profile-picture](https://user-images.githubusercontent.com/3272660/138273305-6ffbd18f-8115-47b3-86a2-98dee31d2772.png)

**Comment by mtdkei** [comment]
ご作業いただきマージしましたので、こちらでCloseします。ありがとうございました。
