### ISSUE TITLE
管理画面のReact化

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#901]
React化しつつ、浜野さんのテーブルブロックみたいに、管理画面に移動しなくても共有設定をポップアップで変更できるものは変更出来るようにするなどユーザービリティを向上したい。

https://qiita.com/TetsuakiHamano/items/a562d34e9836c6ef81d5

**Comment by shimotmk** [comment]
リリースされたのでCloseします

**Comment by shimotmk** [comment]
- [ ] 無料版で不要になったファイルを削除する
https://github.com/vektor-inc/vk-blocks/tree/master/inc/vk-blocks/admin
